armory3d/armory

- Sources/armory/trait/NavAgent.hx
Fixes angle jumping/popping.
Never rotates 180+ degrees, always rotate the shortest path.
> Fix turning tween

- Shaders/compositor_pass/compositor_pass.frag.glsl
- Shaders/compositor_pass/compositor_pass.json
- Sources/armory/object/Uniforms.hx
- blender/arm/props.py
- blender/arm/props_ui.py
3D LUT color grading. Maybe it's only necessary to only have the StringProperty like lensflare in order to not clutter the UI.
Todo: LUT size handling (resolution dependent handling +  UE4/Unity LUT compatibility), currently only 512x512 LUTS.
> Implement LUT-based color-grading

- Sources/armory/trait/SimpleMoveObject.hx
Simple script to move an object around using the keyboard with WSAD+QE.
Can be used for testing and debuging.
> Simple move object bundled trait

- blender/arm/utils.py
This fixes the problem launching Kode Studio from Blender on Mac.
> Fix for #492 ln -s fails on mac when the link already exists

- Sources/armory/logicnode/CompareNode.hx
- Sources/armory/logicnode/GateNode.hx
- blender/arm/logicnode/arm_nodes.py
- blender/arm/logicnode/logic_gate.py
- blender/arm/logicnode/value_compare.py
Logic Nodes: Added ability to add an arbitrary number of inputs to Gate nodes, but only in the "And" or "Or" mode. This addresses #390.
Also added a Compare Node that can compare 2 inputs and return a bool. (==, !=, <, <=, >, >=)
> LogicNodes: Compare and Multi-value And/Or Gate

- Sources/armory/trait/FollowCamera.hx
Currently this could happen:
1. FollowCamera updates first, picked the old position of target
1. Target update its position then
1. Camera appears lagging one frame behind.
Using LateUpdate should fix it.
> FollowCamera: use LateUpdate to avoid sync issues

- Sources/armory/trait/internal/WasmScript.hx
I got latest this morning and after refreshing the gate node I could not build for iOS, I saw all the other WASM checking where wrapped in #if js
> Add #if to WasmScript - was breaking iOS builds

- Sources/armory/logicnode/ObjectNode.hx
The objectName was never ever set anywhere so the line
`value = objectName != "" ? iron.Scene.active.getChild(objectName) : tree.object;
`
would always return tree.object.
Thus using the set method had no effect at all as it set the value, which was then overridden because objectName was not set.
One might also consider to remove the value variable completely as I don't see it being used anywhere in thi script.
> adjusted ObjectNode to work with SetVariable Node

- Sources/armory/logicnode/SendObjectEventNode.hx
- blender/arm/logicnode/action_send_object_event.py
This is a pull request for an addirion for "send object event" node. This will send a event to a specific object.
Compared with send event node, this will send events to a different object.
Compared with send global event node, this will not corrupt the "Global namespace".
sample file: 
[send_obj_node.zip](https://github.com/armory3d/armory/files/2186152/send_obj_node.zip)
> add send object event node

- blender/arm/material/cycles.py
- blender/arm/material/cycles_functions.py
This pull request enables the HueSaturationValue Node to function properly based on its color and factor inputs. Previously it only used its hue, saturation and value inputs to generate a color. It was not possible to use it to modify an incoming color or texture (at least in my testing).
To achieve this, this pull request adds a new function in `cycles_functions.py` to convert an incoming rgb color to hsv, apply the modifications of the hsv node and return the result as an rgb color, mixed with the original color as defined by the factor input. It also changes the `cycles.py` file to read these factor/color inputs (they were already in place but commented out) and then call the new function.
I also added some comments to the function. If you don't like that, feel free to remove these …
> Changed HueSaturationValue node to work with all of its inputs

- blender/arm/logicnode/arm_nodes.py
- blender/arm/nodes_logic.py
Logic node categories are now created dynamically. This allows nodes be added to any arbitrarily named categories without having to maintain a global category list. This is useful because it allows custom logic nodes to be added to custom categories.
> Allow Arbitrary Category Names for Nodes

- Sources/armory/logicnode/LookAtNode.hx
The Look At node previously output a quat for the rotation, which is
inconsistent and incompatible with the other logic nodes such as
Set Rotation.
> Make the Output of the Look At Node Euler Rotation

- blender/arm/props.py
1. Use linked blend file
2. Set the project root path
3. In the file explorer, select your main blend file
4. Press 'F5' to Play
5. Crash an error "NotADirectoryError"
> [Python] Root must be a directory path

- blender/arm/material/make.py
1. Create a new material
2. Set Custom Material (eg.: MyCustomMaterial)
3. Hit F5 to play
4. Crash (Cannot find MyCustomMaterial.json.json)
> Remove double .json extension

- Sources/armory/trait/physics/bullet/PhysicsWorld.hx
Tell me if there is anything wrong with the way I did this. The only thing that I can think of is, because I removed the `distance < 0` check, that the Get Contacts node, or similar code would have to perform that check themselves. I can update the node do that check if that is a possible issue.
Other than that, I did rename the `ContactPair.nor` to `ContactPair.normOnB` because it was more intuitive, which would require a change for any code depending on it. The only class that appears to use it is the `PhysicsBreak` trait, but other API changes have broken that class in the dev branch and I didn't know how to fix them.
> Allow Multiple Contact Points Between Two Physics Objects

- blender/arm/proxy.py
Hey!
I noticed Make Proxy button fails with a stack trace in armory 0.6 alpha (archive downloaded from site) in `armsdk/armory/blender/arm/proxy.py` on line 17.
Looks like `bpy.context.scene.objects.active` is [no longer available](https://docs.blender.org/api/blender2.8/bpy.types.SceneObjects.html#bpy.types.SceneObjects) in Blender 2.8
After a quick search I found people use `context.view_layer.objects.active` [for the same purpose](https://blender.stackexchange.com/questions/126577/blender-2-8-api-python-set-active-object).
I never did extensive testing or research, but this simple fix seems to work for me.
> Update Make Proxy script for Blender 2.8

- blender/arm/props_bake.py
- blender/arm/props_ui.py
From forum topic:
http://forums.armory3d.org/t/cnt-bake-traceback-error-comes-always/2451?u=zicklag
In [this](https://github.com/armory3d/armory/compare/master...katharostech:bug_armory-bake?diff=split&expand=1#diff-6c28ad04114826c2ba032cdea128c144L1037) line I removed the scene context for the Armory bake object search, which means that objects in the current or any scene will be included in the object search. I did this because there seems to be some kind of bug where you can't select the object from the dropdown when you use the `bpy.context.scene` as the search object.
> Fix Armory Bake Python Error

- Sources/armory/trait/physics/bullet/PhysicsWorld.hx
Make sure that the Get Contacts node doesn't return the same object multiple
times.
**Edit:** Actually wait to merge this. I just realized that I should be putting the "don't return same object twice" logic in the PhysicsWorld, not in the logic node.
> Get Contacts Node Returns Each Contact Once

- Sources/armory/logicnode/OnUpdateNode.hx
- blender/arm/logicnode/event_on_update.py
I added a dropdown to the On Update node to let you select between On Update, On Late Update, and On Physics Pre-Update. If you would rather these be separate nodes, just tell me and I'll split it out and update the PR.
> Add Late Update and Physics Pre-Update To The On Update Node

- blender/arm/props_traits.py
- blender/arm/utils.py
- blender/arm/write_data.py
At the moment there is no way of visually splitting your trait files using subfolders directly from Blender, therefore all the haxe trait files will hang from "Sources/arm".
It would be beneficial specially for maintenance if users were able to split their projects into subfolders that map features/scenes or whatever makes more sense for the creator. Therefore this pull request includes functionality that will allow users to put their traits into subfolders by using haxe package syntax (package example.MyClass;)
This way, when the user creates a new haxe trait in blender, if s/he creates a name such as core.MyTrait, a new haxe script will be automatically created in "Sources/arm/core/" with name "MyTrait.hx" containing the correct package syntax "package arm.core;", that will be …
> Added support for script subfolder organisation using haxe package syntax

- Sources/armory/logicnode/CastPhysicsRayNode.hx
...due to too short Rays set by the user.
Suggestion for the fix by zicklag, see here: http://forums.armory3d.org/t/bullet-physics-keeps-freezing-the-games/2925/2
Can confirm its working now.
> fix an exception where hitPointWorld gets null.

- blender/arm/props_traits.py
Change ArmTraitPropList to ARM_UL_PropList following latest blender API changes to fix error in blender: 
```
search for unknown uilisttype ArmTraitPropList
uiTemplateList: List type ArmTraitPropList not found
```
> Fix issue reading trait properties

- Sources/armory/logicnode/ApplyForceAtLocationNode.hx
- Sources/armory/logicnode/ApplyForceNode.hx
- Sources/armory/logicnode/ApplyImpulseAtLocationNode.hx
- Sources/armory/logicnode/ApplyImpulseNode.hx
- Sources/armory/logicnode/TranslateObjectNode.hx
- blender/arm/logicnode/physics_apply_force_at_location.py
- blender/arm/logicnode/physics_apply_impulse_at_location.py
1. The apply force node used applyImpulse for y and z. Fixed now.
2. In all nodes with the "local" option Y+ (instead of X+) is now look (or forward), as it traditionally is.
3. Apply Force/Impulse at Location now has the local option too.
> Fix Force, switch X & Y for local, add option for "at location" nodes

- Sources/armory/logicnode/MergedGamepadNode.hx
- Sources/armory/logicnode/MergedKeyboardNode.hx
- Sources/armory/logicnode/MergedMouseNode.hx
- Sources/armory/logicnode/MergedSurfaceNode.hx
- Sources/armory/logicnode/MergedVirtualButtonNode.hx
- blender/arm/nodes_logic.py
(Sorry for spamming the pull requests...)
I added the ability to map properties (which is especially important for the input nodes, since they would be resetted otherwise) and to map unconnected sockets as well.
I also realized that since the bl_idname is different now, I also had to rename the haxe classes.
> auto replace properties

- Sources/armory/logicnode/RotateObjectAroundAxisNode.hx
this seems to fix the issue in http://forums.armory3d.org/t/fly-through-navigation-controller-how-to-adjust-axis-for-forward-and-back-movement/3038/7 for me.
The error which showed up in the web console stated that inputs[2].get().normalize was not a function.
I guess that inputs[2].get().normalize() might have created issues due to a null value...
It is weird though that this only happened when using the html5 exporter... F5 with Krom and Browser worked fine.
> small fix for rotate around axis node

- Shaders/motion_blur_pass/motion_blur_pass.frag.glsl
- Shaders/motion_blur_veloc_pass/motion_blur_veloc_pass.frag.glsl
When we flip the y coordinate of coord in getVelocity() function, the y of the velocity vector will also get flipped. If we let this on, the result of the motion blur will be weird, creating X pattern blur rather than O pattern blur, noticeable especially when looking down/up and rotating around camera front axis. To fix this, negative the y of velocity vector manually and problem solved.
Before:
After:
> Camera Motion Blur Pattern Fix

- Sources/armory/trait/physics/bullet/PhysicsWorld.hx
I'm not sure why contactPairs stores ids instead of storing the references to the rigidBodies directly, so I added a function that lets you quickly search a rigidbody with the ids you would get by getContactPairs
> Add a function to find a rigidBody by their id

- Sources/armory/trait/physics/bullet/PhysicsWorld.hx
Sorry I added that length check last minute to be sure but didn't test, it seems it doesn't have length prop, but without that check should be fine.
> hotfix, no length property on map

- blender/arm/props_traits.py
This property is used internally only and doesn't need to be exposed to the UI.
Now the UI looks like this:
>  Hide is_object property from user during trait script creation

- Sources/armory/logicnode/CastPhysicsRayNode.hx
- Sources/armory/trait/physics/bullet/PhysicsWorld.hx
This change will allow to get the position of a hit with raycast, the normal and the body, some extra info that otherwise you couldn't obtain because raycast only returns a body, this may break some compat but I think is better than having multiple functions that do the same logic only for obtaining each piece of information separated (to keep compatibility).
>  expand the info raycast returns

- blender/arm/utils.py
if a file is created with a name like "test.folder.scripts.MyTrait" in the new script window, it will be stored in script_props and script_props_defaults with that full name, instead of just "MyTrait".
fixes this: https://github.com/armory3d/armory/issues/1306
> Allow reading props from scripts in subfolders

- blender/arm/make_logic.py
This PR addresses an issue with reroutes.
In the creating outputs stage of the `build_node` function, it previously checked whether an output was linked and then added the result of `build_node` to the outputs array.
While `build_node` correctly handled reroutes as inputs, this didn't seem to work when collecting the outputs.
This PR introduces a new recursive `collect_outputs_from_link` function, which takes an (outgoing) link and recursively adds all non-reroute nodes to an array, which is then returned.
The create outputs in `build_node` was modified to use these instead of the raw links.
For testing I hooked up a keyboard node to a print node through two reroutes.
With the original exporter, this was produced:
`_Keyboard.addOutputs([_Keyboard]);`
As can be easily seen, there is no …
> Improve reroute handling in logic nodes

- Sources/armory/trait/NavAgent.hx
- Sources/armory/trait/NavMesh.hx
- blender/arm/props_traits.py
- blender/arm/props_ui.py
What has changed:
- added back visualization of navmesh generation
- readded navagents moving in the z axis. I tested for a bit and got good results with that small modification, not really sure why it was commented out but will look at it further if the results are not consistent for now.
- added functions to change navmesh generation settings for recast, used in the interface when generating visualization and when running the project
- moved the navmesh generation button for consistency
Depends on:
https://github.com/armory3d/armory_tools/pull/1
https://github.com/armory3d/haxerecast/pull/1
I tried to do some threading to prevent the UI to lock but I couldn't get the importing model part to work with threads so I dropped it for now.
Error catching is missing too, planning to add it in …
> update for navmesh generation

- Sources/armory/trait/internal/CanvasScript.hx
Adding getElements() function to CanvasScript, it can be a handy method for this Trait. Sometimes we would need to iterate all elements attached to a Canvas without having to call one by one using getElement(name:String)
> Add getElements():Array<TElement> function to CanvasScript

- Sources/armory/logicnode/LoadUrlNode.hx
- blender/arm/logicnode/native_loadUrl.py
This node is dedicated to browser (HTML5) compilation.
Python : native_loadUrl.py
Haxe : LoadUrlNode.hx
Example : LoadUrl.blend
A logic node created with reference to the Haxe code on this page.
http://forums.armory3d.org/t/solved-open-web-browser-showing-url/3499
> Logic node that loads url

- blender/arm/props_traits.py
- blender/arm/props_ui.py
- blender/arm/utils.py
Linked to https://github.com/armory3d/armsdk/pull/5
**This PR adds support for Sublime Text (and other custom code editors). I have reworked the selection menu in the user preferences and the detection of the standard code editor.**
- Instead of a folder path, the user must now specify the file path to the executable file in the user preferences, so that user-defined editors are also supported.
- Since Kode Studio is no longer included in armsdk, the methods for automatically searching for this editor inside the SDK folder have been removed
- If the user has defined the environment variables "VISUAL" or "EDITOR", these will be considered first when choosing the default editor.
- If Sublime Text is selected, a simple project file is created.
- Test if Mac ~~and …
> Add Sublime Text as a supported text editor

- blender/arm/props_traits.py
This is for now to prevent the "vertical generation" issue that happens when generating a navmesh representation the first time and failing because of #1377. Not liking the "require a restart" thing as a solution but I didn't find one that is not a workaround yet, so for now this helps...
> Add a restart check in navmesh vis generation

- blender/arm/exporter.py
- blender/arm/props_traits.py
added support for modifiers for navigation meshes in visualization and when playing, 
removed the need to restart blender when creating visualization by calling node directly into the subfolder and fixes https://github.com/armory3d/armory/issues/1377
Depends on this https://github.com/armory3d/haxerecast/pull/4
Example, mesh with multires and boolean modifiers (boolean may allow for less manually obstacle generation)
> nav update 3

- Sources/armory/trait/NavMesh.hx
This is to revert it to the original without the offset because it has inconsistent results with meshes with almost no height, something that I need to investigate why. 
So for now to keep results consistent it stays without the offset.
> Revert offset to the y value when adding a path navmesh

- blender/arm/material/cycles.py
This is to help transition to Blender 2.81.
I tried to tackle obtaining the input value if something was connected but it turned more complicated than I thought, so for starters I added support to the dynamic inputs default values so it compiles with no errors when a mapping node is present.
Please point out any ugly code.
> add initial support to Mapping dynamic inputs

- blender/arm/exporter.py
- blender/arm/make.py
Add a temporary collection to the current scene that links all the foreign objects meshes and collections with meshes from other scenes so the depsgraph can "see" it and then the collection is destroyed. Later the "charged" depsgraph is passed to the exporter.
This is done because the dependency graph requires a scene change in order to be updated with the view layer. So instead of changing scenes to update the dependency graph, the objects are brought to the dependency graph. This behavior and other solutions are discussed with more detail in the issue linked below.
"Zoo" collection only gathers MESH and EMPTY (linked collections) to keep it minimal, but it could be expanded to include other types of objects if required.
Fixes this https://github.com/armory3d/armory/issues/1466
> fix export with a 'zoo collection'

- blender/arm/exporter.py
Ask for `export_uvs` to the original object instead of the evaluated copy. 
Fixes this annoying issue: https://github.com/armory3d/armory/issues/1378.
Reason is, it seems the dependency graph fails to update whenever custom properties are set. 
So for that I think asking the original object in this case could be sufficient to fix it seeing it doesn't seem to be necessary to use the evaluated copy info I think.
> The same could be applied to the other functions that are there in that chunk of code if they don't really require asking the evaluated copy.
Before:
Notice how in the end I change to different workspaces to trigger the dependency graph to update.
After:
> Fix for faulty "missing uv maps"

- blender/arm/utils.py
Since Haxe 4.0.0, there is a new keyword for constant variables called `final` (https://haxe.org/manual/expression-var.html#since-haxe-4.0.0)
This PR allows trait properties also for variables starting with `final` instead of `var`.
> Allow @prop for `final` keyword too

- blender/arm/material/cycles.py
- blender/arm/utils.py
No more pink meshes when using generated textures :)
The generated images are now converted and stored in the same place as converted textures were stored before (`[buildpath]/compiled/Assets/unpacked/`).
> Add support for generated image textures

- blender/arm/exporter.py
- blender/arm/props_traits.py
- blender/arm/props_traits_props.py
- blender/arm/utils.py
Requires https://github.com/armory3d/iron/pull/79
- Trait property code simplified and is hopefully more readable now
- Support for different property types, not strings only
- UI shows proper UI elements for different types
- Added support for Object and Vector properties (also certain object sub-types). Default values of vector types are also allowed
- Show warnings in the UI if a prop type is not supported or the property is invalid
- Removed property support for `final` values again. Found out that this didn't really work, haxe just didn't throw an error
- UI refactor
- Different icons for different types. Might not be the best icons, feel free to change everything from this PR :)
- Properties are also refreshed when their type changes
Screenshots:
@luboslenco If you agree on merging …
> Major refactor of trait properties

- blender/arm/write_data.py
Previously, new canvases weren't initialized with a theme, so an error was displayed.
Linked to https://github.com/armory3d/armory2d/pull/49
Thanks to hreez on discord for the report :)
> Fix annoying error message at first Armory2D start from Blender

- blender/arm/exporter.py
Object names of trait properties are now exported by using `arm.utils.asset_name()`.
> Fix object type trait property export for linked objects

- blender/arm/props_traits_props.py
- blender/arm/utils.py
Trait properties of boolean type were incorrectly interpreted as blank/undefined when they defaulted to `true`.
> Fix bool type trait properties

- Sources/armory/logicnode/AddGroupNode.hx
- Sources/armory/math/Helper.hx
- Sources/armory/math/Rotator.hx
- `Helper` and `Rotator` classes were missing imports and relied on old `Math` class
- `AddGroupNode` didn't initialize group with an instance offset
> Some smaller fixes

- blender/arm/props.py
- blender/arm/props_ui.py
Just a small improvement to prevent an error during compilation.
I've also updated the property description:
> Deactivate "Debug Console" checkbox when Zui is not enabled

- Sources/armory/logicnode/SetRotationNode.hx
Fixes for example the `virtual_gamepad` demo crashing on startup
in Android.
> Fix `armory.logicnode.SetRotationNode` vector type for input

- blender/arm/exporter.py
- blender/arm/material/cycles.py
Applied the same fix that is used for uvs, since it seems to solve the issue of not updating correctly for exporting of vertex colors and tangents too, until it's fixed on Blender's part.
Also added support for the Vertex Color node.
> Fix Vertex Color and Tangent not exporting sometimes

- blender/arm/exporter.py
- blender/arm/props.py
- blender/arm/props_ui.py
Hey Lubos, can you check this out?
I've always had trouble animating characters for armory because I like to work with bone constraints. Usually what I did was export to fbx and then import back into blender. That workflow is a mess, so I made this little modification to bake constraints automatically.
It introduces a new property arm_autobake for the Armature type, and it displays it in the object data properties panel. If enabled, it doesn't export any bone constraint at all, but instead bakes all actions.
Now I dont need to do blender -> fbx -> blender in order to tweak animations. Hopefully this will help someone else too :)
> Action autobaking

- blender/arm/exporter.py
Fix/Workaround for https://github.com/armory3d/armory/issues/1523.
Iron does not allow duplicate names for objects but the now replaced code was still adding exporting objects to collections if their names were already "taken".
Also, objects in collections are now always exported with their full asset name, taking the collection name into account which decreases the rate of name conflicts massively.
In the very rare case that an object from a collection still has the same name as another object in the scene (that object then must be named `[collection_name]_[object_name].blend` for this problem to occur, which is very unusual), a warning is printed to the console and the collection object with the duplicate name is not exported.
---
*Just an idea for the future (off-topic):* Warnings …
> Exporter: better handling of duplicate object names

- blender/arm/utils.py
`subprocess.Popen()` led to a ResourceWarning when using the `open_project_folder()` operator:
```
C:\Program Files\Blender Foundation\Blender 2.82\2.82\python\lib\subprocess.py:858: ResourceWarning: subprocess 15904 is still running
ResourceWarning, source=self)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
```
Replacing `Popen()` with `run()` (new since Python 3.5) solves the issue, calling `Popen()` with stdin, stdout, stderr = `None` would probably also work, but `run()` is recommended.
> Fix ResourceWarning for open_folder()

- blender/arm/exporter.py
Instances from collections of different scenes in the same file were not getting exported. I think this fixes the issue.
[same-file instance bug.blend.zip](https://github.com/armory3d/armory/files/4284816/same-file.instance.bug.blend.zip)
The file should crash on the master branch.
> Same-file collection instance bug

- blender/arm/exporter.py
I made some changes so the action autobaking feature wouldn't crash on collection instances. Here's a demo file, _main.blend_ should crash on master
[colinst-autobake.zip](https://github.com/armory3d/armory/files/4294058/colinst-autobake.zip)
> Support for collection instance with autobaking armatures

- blender/arm/exporter.py
- blender/arm/log.py
- blender/arm/make.py
- blender/arm/props.py
- blender/arm/props_ui.py
Requires https://github.com/Kode/khamake/pull/227 (already merged in the upstream repo).
This PR adds a new `Verbose Output` option to the UI that, when turned off, shows only some basic compile information, warnings and error messages. Most of the time you don't need messages about each asset that get's exported, it just distracts from warnings. When turned on, it shows the same content as before (so `true` is the old default and `false` the new one).
In the best case, the new console output looks like this now:
Also, warnings are now counted during export and a message is displayed both in the console and the UI to inform about warnings.
Console:
UI:
> De-clutter console output and show warnings

- blender/arm/material/cycles.py
- blender/arm/material/cycles_functions.py
The way this fix is done might be against the way the shader was intended to function. Fix # 1 will still apply though, because for some reason the scale input of the noise texture is at id "2" instead of being at id "1". Fix # 2 is not letting the shader use the Z coordinate of its input because that crashes it. I have no idea why. Also changed the shifting parameters of the G and B values because I think that it looks closer to what it looks like in Blender with that.
> Fix noise texture

- blender/arm/exporter_opt.py
Updated the opt_exporter to fit new vertex format.
Fixes geometry not loading in published linux project and crash in published windows projects https://forums.armory3d.org/t/unable-to-build-and-run-default-scene-for-windows-krom/3948.
> Fix geometry not working in published projects

- Shaders/std/mapping.glsl
- blender/arm/material/cycles.py
- blender/arm/material/shader.py
I modified the shader parser so that triplanar mapping of textures is supported.
Currently tested and working with Armory PBR and Principled BSDF.
Normals are supported.
Fixes this https://github.com/armory3d/armory/issues/1292
> Fix support for box/triplanar mapping

- Sources/armory/trait/internal/CanvasScript.hx
I had to make a new PR because I couldn't figure out how to add  a new commit since I didn't push the first PR from a my fork. 
Armory would now set the canvas dimensions every frame to the game's dimensions, so the anchors are where they should be even if the windows gets resized.
> Keep Canvas dimensions the same as the game dimensions

- blender/arm/material/cycles.py
- blender/arm/material/cycles_functions.py
The Wave texture now takes all the values set in Blender into account. Also fixed the Noise texture value output where I forgot to set the scale input id to 2 when I initially tried to fix it.
> Upgrade Wave Texture node + Fix noise texture Value output

- blender/arm/material/cycles.py
- blender/arm/material/cycles_functions.py
Noise texture takes all inputs in Blender into account. Seems to be just as fast as the old method when detail is set to 0 while still not ignoring distortion. Upping the detail reduces performance, but only slightly if you only push it as far as you can see a difference.
> Upgrade noise texture

- blender/arm/material/cycles_functions.py
- blender/arm/material/make_finalize.py
I finally found out why the Z coordinate of 'bposition' was broken, a div by 0 occurred in the vertex shader if the mesh is flat. Fixed that and made the textures 3d again so they don't look stretched on not-flat objects.
> Make procd textures 3d again, fix broken Z coord in bposition

- blender/arm/exporter.py
The Blender crash referenced in the issue happened always when starting 2nd iteration of the loop in line 2041 ( https://github.com/armory3d/armory/blob/master/blender/arm/exporter.py#L2041 ). I'm not really sure, but I bet it had to do with `export_object` modifying `bpy.context.collection.objects` (line 818 — https://github.com/armory3d/armory/blob/master/blender/arm/exporter.py#L818 ), wich in turn could invalidate the reference obtained in line 1926 ( https://github.com/armory3d/armory/blob/master/blender/arm/exporter.py#L1926 ), if I understand a bit of Blender internals — wich I didn't some days ago, so this could be completely wrong :sweat_smile:  .
It no longer happens with this change.
> Fixed memory problem in `ArmoryExporter.execute` [fixes #1604]

- Sources/armory/trait/internal/DebugConsole.hx
- Previously there was a null pointer exception when a scene was selected that had no world
- The outliner look was wrong since https://github.com/armory3d/zui/commit/038c6d4e40716a416583b464bd7461fc756b0a28
> Fix debug console

- blender/arm/exporter.py
Previously, the warning `Armory Warning: No camera found in active scene` was displayed when exporting two or more scenes with different cameras.
For scenes other than the first exported scene, the attribute `o['spawn']` is set to `False` for objects not in the currently exported scene to disable them (makes sense so far):
https://github.com/armory3d/armory/blob/4c3332858ef0f397d898b3050fd86f80e47868eb/blender/arm/exporter.py#L586-L589
The issue with that was that if `spawn` was set to `False`, `camera_spawned` (states whether a camera is found and exported) was set to `False` too, thus revising that information even if a valid camera was found before:
https://github.com/armory3d/armory/blob/4c3332858ef0f397d898b3050fd86f80e47868eb/blender/arm/exporter.py#L715-L716
Just a **_very_** small …
> Fix camera export when multiple scenes are exported

- Sources/armory/logicnode/TraitNode.hx
- blender/arm/exporter.py
- blender/arm/props_traits.py
Traits now have a `Fake User` setting. If set to `true`, the trait will be exported even if it is deactivated. This fixes https://github.com/armory3d/armory/issues/1529.
I've also slightly changed the trait UI:
**Before**:
**After**:
> Add "Fake User" setting for traits + reorder trait UI

- blender/arm/props.py
- blender/arm/props_ui.py
- blender/arm/proxy.py
This PR adds an option to keep the values of trait properties when syncing with a proxy object and makes it the new default behaviour. This is helpful when you change and sync a proxy but you have many objects with different property values that reference that proxy.
> Proxy: Add option to keep local trait properties when syncing

- Sources/armory/logicnode/ArrayLoopNode.hx
- blender/arm/logicnode/logic_array_loop.py
The value output socket of the ArrayLoop node was mistakenly showing a dark green circle (= Integer). This is now light green (= Dynamic). Thanks to "busy guy" on Discord for reporting this.
Also, the node now has an additional `Index` output that outputs the current index of the iteration.
**Example:**
**Output**
```
armory.logicnode.PrintNode:15: 0
armory.logicnode.PrintNode:15: i: 0
armory.logicnode.PrintNode:15: 2
armory.logicnode.PrintNode:15: i: 1
armory.logicnode.PrintNode:15: 45
armory.logicnode.PrintNode:15: i: 2
```
> Fix ArrayLoopNode socket (dynamic value) + add "Index" output

- Sources/armory/trait/internal/DebugConsole.hx
- blender/arm/props_ui.py
- blender/arm/utils.py
- Fixed the look of the debug console outliner
- Now using `arm.utils.safestr()` for sublime text project names
- Added an icon for the "Code Editor" operator so that it is more distinguishable
> A bunch of really small improvements

- Sources/armory/trait/WalkNavigation.hx
Helpful for flying around with the default camera in larger scenes
> WalkNavigation: set flying speed via mouse wheel

- blender/arm/material/cycles.py
- blender/arm/material/shader.py
- Colorramps now use the "factor" value if the input socket is not connected
- Fixed an issue when the factor value was larger than the largest element's value, this fixes https://github.com/armory3d/armory/issues/905 (the output from the test file in that issue still looks off but it is not related to the colorramp anymore)
- Fixed an issue when a color output socket was connected to a float input socket. Now, there is proper automatic rgb to bw conversion copied over from the `RGB to BW` node (this fixes https://github.com/armory3d/armory/issues/1404)
- There were `#todo` comments in the code mentioning `const` for the colorramp element vectors, so they are constant now :)
- Value node outputs are also constant now as value nodes don't have any inputs
- New `Shader.add_const()` method …
> Fix and refactor the colorramp node (+ more)

- blender/arm/material/cycles.py
Fixes https://github.com/armory3d/armory/issues/1674
----
@luboslenco It looks like the ID in `arm_commit` does not use the commit hash but a hash value of the file's content(https://stackoverflow.com/a/1796675/9985959). Do you have any idea on how to improve this (git hooks maybe?) I stumpled upon this because I tried to find out which version @Simonrazer had in his issue above.
https://github.com/armory3d/armory/blob/df30e9b68158265e1fa181d3c2b43c91ece01a80/blender/arm/props.py#L13-L17
> Fix value node when used with material params

- blender/arm/material/cycles.py
Previously there were variables in the fragment shader that were redeclared when using multiple mapping nodes.
> Fix compiling for multiple mapping nodes

- Sources/armory/trait/internal/CanvasScript.hx
This exposes the `Zui.setScale` method trough `CanvasScript` to allow changing the scale factor for the UI elements.
I'm not really sure if this is the right place to put this nor if there would be another way of accessing this setting from Armory at runtime :thinking:
> Added `CanvasScript.setUiScale` method.

- blender/arm/write_probes.py
When `arm_minimize` was false, exported irradiance files got the ending `.json.json` and were not found.
---
@luboslenco Is there a reason that `arm.utils.write_arm()` does not add the `.arm` extension to minimized files but the `.json` extension to not minimized ones? Currently, there are a lot of lines like
```python
ext = '.arm' if bpy.data.worlds['Arm'].arm_minimize else ''
```
all over the codebase to compensate for this.
> Fix irradiance export

- Sources/armory/renderpath/Inc.hx
When testing lights without shadows, the shadow maps were in an invalid state, preventing the lights from rendering at all.
> lights wouldn't render at all if use_shadow / cast_shadow was unchecked

- Sources/armory/logicnode/OnCanvasElementNode.hx
- blender/arm/logicnode/input_on_canvas_element.py
- OnCanvasElementNodes can now listen to hover events (click events are still default), closes https://github.com/armory3d/armory/issues/1701
- Fixed an error when Zui was disabled
- Better variable names
- Performance improvement (previously there were many iterations over all canvas elements on each frame in `canvas.getElement(element)`)
> Refactor OnCanvasElementNode and add hover listener

- Sources/armory/logicnode/PlaySoundRawNode.hx
- blender/arm/logicnode/sound_play_sound.py
- blender/arm/make_logic.py
This PR implements https://github.com/armory3d/armory/issues/1703 and adds even further functionality to the `PlaySoundRawNode`. Thanks to @knowledgenude for the proposal :)
**Screenshot**:
- Fixed boolean type node properties
- New inputs `Pause` and `Stop`
- New outputs `Running` and `Done`
- Setting for enabling loop playback (default `false`)
- `Retrigger` option that will play a sound from the beginning if `Play` is true but the sound is still playing (default `false`)
- Optional sample rate override to compensate for wrong playback pitch and speed (possibly a Kha issue)
- Changed the Node icon (does this even show up in the UI somewhere?)
**Example file**: (adapted from issue https://github.com/armory3d/armory/issues/1704)
[sound_node.zip](https://github.com/armory3d/armory/files/463 …
> Big PlaySoundRawNode update

- blender/arm/props.py
- blender/arm/props_ui.py
- blender/arm/utils.py
This allows to (optionally) specify a scene to launch in player menu.  
I think it's a common workflow to load objects from other scenes into your main 'Game' scene, and pretty annoying to have to switch between scenes just for launching.
> Allow to set custom play scene

- Sources/armory/trait/internal/DebugConsole.hx
Print the position and customParams passed to trace in the DebugConsole log.   
```haxe
trace("A","B","C");
```
Prints:
`my.Class.hx:23: A, B, C`
Instead of just:
`A`
> Proper debug console log output formatting

- Sources/armory/system/Starter.hx
Replace `untyped __js__` with `Syntax.code` and get rid of deprecated compiler warnings.
> Replace __js__ with Syntax.code

- blender/arm/log.py
- blender/arm/make.py
Adds colored terminal output using ansi escape codes.  
There might be some more places to use it, currently added to warnings and errors.   
I've only tested on linux but afaik this should be fine with macos, windows.
> Colored terminal output

- blender/arm/logicnode/arm_nodes.py
- blender/arm/make_logic.py
Not connected custom input sockets now can have arbitrary default values (as long as they can be represented in Haxe syntax), previously they would just have the value `null`.
> Implement custom default values for custom node sockets

- Sources/armory/system/Starter.hx
Allows to build haxe project with static-analyzer (`-D analyzer-module`) enabled to improve code generation for the krom and html5 target. It's the only place where i've found such incompatibility but there might be more. Be aware that this change moves the ammo lib callbacks from haxe to untyped js, so  the compiler can't catch any errors from possible side effects, but works for me.
The generated code with analyzer enabled (without the fix) removes the callback to `print` and `instantiateWasm`:
```js
var loadLibAmmo = function(name) {
kha_Assets.loadBlobFromPath(name,function(b) {
(1, eval)(b.toString());
Ammo({print:print, instantiateWasm:instantiateWasm}).then(loaded);
},null,{ fileName : "Sources/armory/system/Starter.hx", lineNumber : 83, className : "armory.system.Starter", …
```
> Fix building with analyzer-optimize enabled

- blender/arm/nodes_logic.py
Reroutes and frames were always supported by the logic node editor but not available from the add node menu. This PR adds them in the new category "Layout".
The layout category is appended to the end of the list by purpose to mimic the other node editors and to not interfere with the actual logic nodes.
I've also added the possibility to create more layout nodes in the future (maybe Blender gets text areas in the future so we could add a proper comment node) by simply assigning them to the layout category.
> Add reroutes and frames to add node menu

- blender/arm/nodes_logic.py
Not sure why nobody is complaining but wuthout this import i get:
```sh
File "/home/tong/.config/blender/2.83/scripts/addons/armory.py", line 260, in execute
start.register(local_sdk=local_sdk)
File "/home/tong/sdk/armsdk//armory/blender/start.py", line 33, in register
arm.nodes_logic.register()
File "/home/tong/sdk/armsdk//armory/blender/arm/nodes_logic.py", line 196, in register
register_nodes()
File "/home/tong/sdk/armsdk//armory/blender/arm/nodes_logic.py", line 52, in register_nodes
layout_items += [NodeItem('NodeReroute'), NodeItem('NodeFrame')]
NameError: name 'NodeItem' is not defined
```
> Fix NodeItem import

- Sources/armory/trait/physics/bullet/PhysicsWorld.hx
Just enabling the same code used for C++.
This fix for example https://github.com/armory3d/armory_examples/tree/master/physics_raycast not working in C targets — and I think it should fix (or at least improve the situation with) #1706.
> Fixed `armory.trait.physics.bullet.PhysicsWorld.rayCast` for Hashlink.

- blender/arm/write_probes.py
Adds the `--silent` param to the cmft tool call if `arm_verbose_output` is not set, prints the command otherwise.
This is **not** tested on windows.
> CMFT: add --silent param if arm_verbose_output is not set

- Sources/armory/trait/PhysicsDrag.hx
Just enabling the same code used for JavaScript.
> Fixed `armory.trait.PhysicsDrag.update` for Hashlink [fixes #1730]

- blender/arm/exporter.py
Fix for:
```sh
File "/home/tong/sdk/armsdk//armory/blender/arm/exporter.py", line 2656, in add_softbody_mod
out_trait['parameters'] = [str(soft_type), str(bend), str(soft_mod.settings.mass), str(bobject.arm_soft_body_margin)]
NameError: name 'soft_mod' is not defined
```
> Fix softbody export

- blender/arm/utils.py
Fix for:
```sh
File "/home/tong/sdk/armsdk//armory/blender/arm/utils.py", line 539, in asset_name
s = bdata.name
AttributeError: 'NoneType' object has no attribute 'name'
```
This happens on export if a trait has a **unset** prop of type `iron.object.Object`.
> Fix unset object prop

- Sources/armory/system/Starter.hx
Static targets and doc-generation are complaining:
```sh
../armory/Sources/armory/system/Starter.hx:17: characters 8-13 : Warning : Local variable tasks might be used before being initialized
```
> Fix initialize var to null

- blender/arm/make.py
@luboslenco Off-topic, but also regarding the verbose mode: there was a bug in Khamake that didn't show shader errors when verbose mode was disabled. It was fixed a few months ago, but is not yet included in Armory's version of Kha/Khamake. Could you please update that? Thanks :)
> Print compositor flags on export

- blender/arm/write_probes.py
Fixes `UnboundLocalError: local variable 'cmd' referenced before assignment`.
Thanks to @Simonrazer for reporting this.
> Fix write_probes() on Windows

- blender/arm/log.py
- blender/arm/utils.py
- Fixed a bug where colored log output was only working on Windows on subsequent logger calls but not on the first one. This was due to disabled `ENABLE_VIRTUAL_TERMINAL_PROCESSING` flag for the windows console. It can be set via registry but I found a way to enable it for the current session [here](https://github.com/microsoft/WSL/issues/1173#issuecomment-459934080). I improved it further by only setting the required flag instead of overriding the whole user configuration.
The used console API functions are documented [here](https://docs.microsoft.com/en-us/windows/console/getconsolemode), [here](https://docs.microsoft.com/en-us/windows/console/setconsolemode) and [here](https://docs.microsoft.com/en-us/windows/console/getstdhandle).
- Fixed outdated log calls in utils.py. This fixes …
> log.py fixes

- Sources/armory/logicnode/SetSceneNode.hx
@luboslenco Should Iron print more informative error messages than the usual cannot read hxbytes thing or is it bad because of the overhead of try/catch statements? Also, should the game stop with such error messages (does not work on every target)? Currently it just prints out errors every frame if such bugs as the now fixed one occur.
> Fix SetSceneNode when using json export

- Shaders/deferred_light/deferred_light.frag.glsl
- Shaders/deferred_light_mobile/deferred_light.frag.glsl
- Shaders/std/light.glsl
- Shaders/std/light_mobile.glsl
- blender/arm/material/make_cluster.py
- blender/arm/material/make_mesh.py
Fixes https://github.com/armory3d/armory/issues/1737.
The required checks were only implemented for sun lamps on full render path, now each lamp type and the mobile render path supports the `Receive Shadow` material setting (forward rendering only).
> Implement "receive shadow" setting for mobile path + all light types

- Sources/armory/trait/physics/bullet/PhysicsConstraint.hx
Currently https://github.com/armory3d/armory_examples/tree/master/physics_ragdoll doesn't build for C targets — builds and works fine with this fix, tested in Linux and Android.
> Fixes `PhysicsConstraint.init` `Generic6DofConstraint` usage for Hashlink

- blender/arm/nodes_logic.py
Quickly add references to node-variables, and setters. Here is a  showcase:
https://youtu.be/Sx4aoxVHiPo
It is definetly more handy in more complex Node setups, just wanted an quick test to demonstrate this.
Any suggestions? Having the "Set" button spawn two nodes is a bit janky, but I don't know how to make a single node that modifies a node-variable based on its ID.
> UI for quick Node variable access

- blender/arm/props_traits.py
There are a lot of trait related operators that are heavily dependent on the currently selected trait indices for example, those were removed from the operator search menu because they were throwing errors in some cases. I've also given some operators more descriptive names and added tooltips to a few.
> Remove some operators from op search menu + code cleanup

- blender/arm/handlers.py
Fixes https://github.com/armory3d/armory/issues/1781.
It's a bit of a hacky solution because Blender doesn't allow extending already existing operators. There is now a `on_operator_post()` function in handlers.py that allows updating Armory's data after operator executions if the context is correct (that's a Blender limitation). It also gets executed when the operator raises an error which cannot be prevented due to it's hacky nature.
> Copy Armory rigid body settings on Copy from Active

- blender/arm/props_traits.py
- blender/arm/props_ui.py
- blender/arm/proxy.py
Implements https://github.com/armory3d/armory/issues/1783.
This PR adds a new operator to `3DView > Object > Copy Traits from Active Object` and to the search menu that copies all traits and their properties from the last selected object to all other selected objects.
If there are traits on one of the target objects (= a conflict exists), a dialog is displayed that asks if the traits should be overwritten or if they should be kept and the new traits get appended to the end of the trait list:
Additional changes:
- Fixed a bug in `update_trait_group()` that would happen if an object gets reassigned the same trait again
- Fixed a bug/missing feature in `proxy.sync_collection()` that would not take multiple same traits into account
- Cleaned up some imports
> Add CopyTraitsFromActive operator

- blender/arm/material/cycles.py
This PR adds the possiblity to retrieve uniform values via the attribute node. The attribute node now interprets strings of the form
`uniformType uniformName` as a shader uniform. uniformType can be `vec2`, `vec3`, `vec4`, `int` and `float`, although `vec4` and `int` are not likely to be used a lot inside the node editor.
**Example**:
This node setup now generates the following output in combination with an animated point lamp:
> Add shader uniform support for the attribute node

- blender/arm/material/arm_nodes/__init__.py
- blender/arm/material/arm_nodes/arm_nodes.py
- blender/arm/material/arm_nodes/shader_data_node.py
- blender/arm/material/cycles.py
- blender/arm/material/shader.py
- blender/arm/nodes_material.py
- blender/start.py
This PR extends the node support for retrieving uniform values that was merged yesterday by a much more general approach that allows to also retrieve shader inputs from both the vertex shader and fragment shader stages (vertex inputs are passed through to the fragment shader). Thanks to @QuantumCoderQC for the idea of retrieving shader inputs as well!
To accomplish this, I created a new node called `Shader Data` (there was no viewport preview for the attribute node approach so we can use custom nodes instead and if there is a better name for the node, please make a suggestion!) and removed the attribute node support for uniforms again. This new approach also allows to add further sockets and nodes in the future that can handle matrices etc.
I'm not happy with the naming of the UI fields, …
> Add ShaderData node for easier uniform and input access

- Sources/armory/logicnode/ApplyForceAtLocationNode.hx
- Sources/armory/logicnode/ApplyImpulseAtLocationNode.hx
- blender/arm/logicnode/physics_apply_force_at_location.py
- blender/arm/logicnode/physics_apply_impulse_at_location.py
This PR intends to solve issue #1813 
With this PR,
- Location of Force/ Impulse is always defined with respect to the object location. Object rotation is not accounted for. 
- If `Location On Local Axis` is enabled, object rotation is also accounted for. 
- Force/ Impulse is defined with respect to the global axis. 
- If `Force/ Impluse On Local Axis` is enabled, Force/ Impulse will be applied with respect to object local axis.
> Upgrade Apply Force at location and Apply Impulse at location to include object rotation

- blender/arm/write_data.py
This fixes https://github.com/armory3d/armory/issues/1815.
As Armory only supports the native android target, we can change `android` to `android_native` in the khafile (see https://github.com/Kode/kincmake/pull/11).
I've also changed `f` to `khafile` in the code for better readability.
> Fix android target options

- blender/arm/material/arm_nodes/shader_data_node.py
This allows access to envmaps etc., mapping is done using screen coordinates.
@luboslenco Is it possible to somehow access buffers (e.g. the depth buffer) as uniforms in a custom shader without modifying the render path? Me and others would really like to have it available in node materials.
> Add sampler2D access to ShaderData node

- Sources/armory/logicnode/QuaternionNode.hx
- Sources/armory/logicnode/RotateObjectNode.hx
- Sources/armory/logicnode/SeparateQuaternionNode.hx
- Sources/armory/logicnode/SetRotationNode.hx
- Sources/armory/logicnode/VectorFromTransformNode.hx
- blender/arm/logicnode/action_rotate_object.py
- blender/arm/logicnode/action_rotate_object_around_axis.py
- blender/arm/logicnode/action_set_rotation.py
- blender/arm/logicnode/logic_switch.py
- blender/arm/logicnode/value_separate_quaternion.py
- blender/arm/logicnode/value_vector_from_transform.py
- blender/arm/logicnode/variable_quaternion.py
- Made so all nodes outputting a quaternion object also output it as a XYZ (vector) + W (float) combination
- Modernized the interface of the "Action/Rotate Object" node, to align on the newer "Action/Set Rotation" node interface  ("Action/Rotate Object Along Axis" is now depreciated, but still usable)
- Fixed a blender-side-only bug with the "Logic/Switch" node (...which technically could have lead to a compile-time problem if exploited the right way)
- Fixed a bug on the "Action/Set Rotation" node: now, quaternion input is automatically normalized in order to avoid accidental scaling
- Added a "Value/Separate Quaternion" node
- Made so the names of some sockets change in the "Set Rotation" and "Rotate Object" nodes, so they adapt to those nodes' input types.
(Same thing with …
> Improved quaternion and angle handling in logic nodes (+2bugfixes)

- Sources/armory/logicnode/ClearParentNode.hx
This PR partially solves #1830 . `RigidBody` now obeys `keep Transform`. 
However, when `keep transform` is disabled, the object transform does not return to the original transforms. This must be fixed in [Iron](https://github.com/armory3d/iron.git).
> Apply tansform for RigidBody if Keep Transform

- blender/arm/logicnode/action_set_camera.py
- blender/arm/logicnode/postprocess_get_camera.py
- blender/arm/logicnode/postprocess_set_camera.py
- blender/arm/logicnode/value_active_camera.py
Previously there were two nodes equally named `Set Camera` which are now renamed to `Set Active Camera` and `Set Camera Postprocessing` (their get-parts were also renamed to reflect that change). I didn't rename the classes, idnames and files to keep compatibility but in the future they should be renamed too.
> Rename camera nodes (no longer duplicate names)

- Sources/armory/logicnode/SpawnCollectionNode.hx
- blender/arm/logicnode/action_spawn_collection.py
- blender/arm/make_logic.py
Requires https://github.com/armory3d/iron/pull/100
This PR adds a new, often requested node to spawn collections to the active scene:
I've also fixed a bug where `None` would be written into the generated .hx code when a property is `None` (for example when no collection was selected).
**Outputs:**
- Top-Level Objects: All objects in the collection that are direct children of the owner object of the collection's instance
- All Objects: All objects in the collection
- Owner Object: The owning object of the collection's instance (like the empty Blender uses for that purpose).
> Add SpawnCollection node

- Sources/armory/logicnode/SetParentNode.hx
I used @QuantumCoderQC Clear Parent node fix and adapted here. This fixes one more bug from here: https://github.com/armory3d/armory/issues/1830
I don't know if this is a correct fix, but solved a problem for me.
One last bug that stills is the rigid body in "random" places when parented. To fix this, when the rigid body (no matter if active or passive) is parented, it must have Animated checkbox checked. I don't know how to do this. This will solve all problems related to it, except the "Keep Transform" unchecked one.
Just somethings to take in count: if the Animated checkbox is set by "Set Parent", then "Clear Parent" should unset the Animated Checkbox. But when the checkbox was not set by "Set Parent", "Clear Parent" should not touch in there. This make me think about merging this two …
> Fix rigid bodies continuing to move when parented

- Sources/armory/logicnode/RotateObjectNode.hx
(compatibility with RotateObject nodes created with armory pre-17daabeb29dfb0a5cc8b4bef840b02b9f83f409d to be exact)
I just kinda derped the compatibility with already-instanced nodes when I wrote that previous commit. Fixing it now.
> fixed a backwards compatibility problem with a node from before armory 2020.09

- Sources/armory/logicnode/CanvasGetLocationNode.hx
- Sources/armory/logicnode/CanvasGetPBNode.hx
- Sources/armory/logicnode/CanvasGetRotationNode.hx
- Sources/armory/logicnode/CanvasGetScaleNode.hx
- Sources/armory/logicnode/CanvasSetAssetNode.hx
- Sources/armory/logicnode/CanvasSetLocationNode.hx
- Sources/armory/logicnode/CanvasSetPBNode.hx
- Sources/armory/logicnode/CanvasSetRotationNode.hx
- Sources/armory/logicnode/CanvasSetScaleNode.hx
- Sources/armory/logicnode/CanvasSetTextColorNode.hx
- Sources/armory/logicnode/CanvasSetTextNode.hx
This fixes https://github.com/armory3d/armory/issues/1842.
If the element socket of some canvas nodes had an empty name or the element doesn't exist, the game would show a black screen. Now, if an element doesn't exist for a `Set` node, the output is still run but nothing happens. For `Get` nodes, the output is not run at all if the element doesn't exist to prevent the usage of wrong values left over by old elements.
> Fix canvas nodes for invalid element names

- blender/arm/write_data.py
Armory's Kha is usually a bit behind the Kode/Kha version which can make it a bit complicated in some cases for libraries to support both versions. For example, Kha replaced `PipelineCache` with `SimplePipelineCache` (the first is now an interface) but Armory still uses the old version.
This PR adds an "armory" flag so it's easy to just check if Armory is used or not. This also makes it possible to check whether Iron is available.
> Add "armory" flag on export to differ between Armory and Kha

- blender/arm/logicnode/arm_nodes.py
- blender/arm/make_logic.py
Fixes https://github.com/armory3d/armory/issues/1865.
- Fixed a bug where socket names weren't reset for multiple calls of the same operator (see issue linked above)
- Fixed a bug where `None` instead of `null` was written into the generated logic node Haxe code.
> Socket fixes

- Sources/armory/trait/CustomParticle.hx
- blender/arm/material/arm_nodes/Custom_particle_node.py
- blender/arm/material/arm_nodes/shader_data_node.py
- blender/arm/material/cycles.py
- blender/arm/material/make_depth.py
- blender/arm/material/make_inst.py
This PR introduces a new material node; Custom Particle node.
Also requires [Iron/#101](https://github.com/armory3d/iron/pull/101#issue-488258474)
This node can be used to efficiently create arbitrarily complex GPU particle systems as a function of particle index `gl_InstanceID` and `uniform time`.
Node properties:
- Efficiently control what particle parameters are modified at run-time using `pos, rot, scl` checkbox. The code for only selected checkboxes is written to the shader. No unwanted processing.
- Built-in billboard option for spherical billboarding of particles. The local z of each particle always faces the camera.
- Since this node is a material node, multiple particle systems can be set-up in different materials. During run-time, changing material also changes the particle …
> Custom Particle Node

- blender/arm/exporter.py
- blender/arm/lib/lz4.py
- blender/arm/props.py
- blender/arm/utils.py
Fixes #1779.
Link to https://github.com/armory3d/iron/pull/102
This ports the LZ4 encoding from Iron to Python. It is a bit slow (maybe due to the extensive use of numpy, I will run it with a profiler in the next days) so a small warning is printed to the console when compression is used.
> Support for LZ4 compression

- Sources/armory/logicnode/OnApplicationStateNode.hx
- blender/arm/logicnode/event/LN_on_application_state.py
This new event node allows to listen to foreground/background and shutdown events.
At least on Windows there are some interesting observations of how the Kha callbacks work (we should probably document that):
- The foreground callback is called twice if the window was minimized (one call for maximize and one for the focus?)
- The background callback is also called before shutdown
> Add "On Application State" node

- Sources/armory/logicnode/GetObjectNode.hx
- Sources/armory/logicnode/SpawnObjectNode.hx
Fixes https://github.com/armory3d/armory/issues/1889.
The Python part of this PR was accidentally commited already when moving the node definitions into subpackages which led to the above bug. Now it is possible to choose the scene from which to take the object in the `Get Object` node. When the scene selection field is empty, the active scene is used.
I've also fixed a bug that resulted in an invalid cast when any other node other than the `Object` node that returned `null` was connected to the `Spawn Object` node.
@luboslenco Is it much work for you to update Krom? It seems to me that it is very unstable since the Kha update, sometimes the game crashes instantly, sometimes after a while or after spawning an object (happened alot during testing this node but also with other nodes, …
> Get Object node: allow getting objects from other scenes

- blender/arm/nodes_logic.py
See https://github.com/armory3d/armory/issues/1820#issuecomment-699129393
> Prevent exception when node has no bl_description attr and docstring

- blender/arm/nodes_logic.py
- blender/arm/utils.py
Added 2 new operators and modified an existing one to allow inspecting the documentation reference or the source of a node. For the source it tries to guess the version that the user has based on their git folder, but if it fails it will default to master.
Solves this feature request https://github.com/armory3d/armory/issues/1820
> Add 3 new context menu options for nodes to inspect source and wiki

- Sources/armory/trait/physics/bullet/RigidBody.hx
This should work now as expected.
Original issue:
https://github.com/armory3d/armory/issues/1707
> Bullet: Collision margin was inverted.

- Sources/armory/logicnode/CallFunctionNode.hx
Fixes https://github.com/armory3d/armory/issues/1898. You can now call functions from any type.
> Fix CallFunctionNode

- Sources/armory/logicnode/SetActionPausedNode.hx
- Sources/armory/logicnode/SetTilesheetPausedNode.hx
- Sources/armory/logicnode/SetTraitPausedNode.hx
- blender/arm/logicnode/animation/LN_get_action_state.py
- blender/arm/logicnode/animation/LN_set_action_paused.py
- blender/arm/logicnode/animation/LN_set_tilesheet_paused.py
- blender/arm/logicnode/deprecated/LN_pause_action.py
- blender/arm/logicnode/deprecated/LN_pause_tilesheet.py
- blender/arm/logicnode/deprecated/LN_pause_trait.py
- blender/arm/logicnode/deprecated/LN_play_action.py
- blender/arm/logicnode/deprecated/LN_resume_action.py
- blender/arm/logicnode/deprecated/LN_resume_tilesheet.py
- blender/arm/logicnode/deprecated/LN_resume_trait.py
- blender/arm/logicnode/deprecated/LN_set_object_material.py
- blender/arm/logicnode/trait/LN_set_trait_paused.py
I think it is more user friendly and cleaner now. I had misunderstood the speaker functionality, now it is not affected.
* `Pause Trait` and `Resume Trait` merged to `Set Trait Paused`.
* `Pause Tilesheet` and `Resume Tilesheet` merged to `Set Tilesheet Paused`.
* `Pause Action` and `Resume Action` merged to `Set Action Paused`.
* Deprecated `Play Action` and `Set Object Material` by `Play Action From` and `Set Object Material Slot` respectively.
* Renamed `Action State` to `Get Action State`.
> Merged pause/resume nodes

- Sources/armory/logicnode/GetDebugConsoleSettings.hx
- Sources/armory/logicnode/SetDebugConsoleSettings.hx
- Sources/armory/trait/internal/DebugConsole.hx
- blender/arm/exporter.py
- blender/arm/logicnode/miscellaneous/LN_get_debug_console_settings.py
- blender/arm/logicnode/miscellaneous/LN_set_debug_console_settings.py
- blender/arm/props.py
- blender/arm/props_ui.py
- blender/arm/utils.py
1. Adding the ability to customize display, scale (size), shortcuts to the _DebugConsole_ class.
2. Adding a function to _utils.py_ to get Debug Console settings from _Render: Armory_.
3. Added Debug Console settings to the _Armory Project_ interface:
- Enable (default value - False);
- Position (Left, Center, Right, default value - Right);
- Scale Console (from 0.3 to 10);
- Visible.
4. Added transfer of Debug Console settings to _exporter.py_.
5. Added logical nodes to control DebugConsole while the application is running.
> Add Debug Console settings

- Sources/armory/logicnode/GetSystemLanguage.hx
- blender/arm/logicnode/native/LN_get_system_language.py
Get System Language
Category: _Native_
To get the current system language according to the IS0 639 standard.
The _Krom_ platform always returns “_en_”.
> Get System Language - LN

- Sources/armory/logicnode/ScreenToWorldSpaceNode.hx
- blender/arm/logicnode/math/LN_screen_to_world_space.py
Fixes #1866
Modifying the Screen To World Space node
Input parameters:
- _Screen X_ - value of screen coordinates along the X axis (data type _Int_);
- _Screen Y_ - the value of the screen coordinates along the Y axis (data type _Int_).
Options:
- _Separator Out_ - whether or not to separate the output parameters (_vectors_) into components (_XYZ_).
Output parameters:
- _World_ - coordinates of a point in 3D space (data type _Vector_)
- _Direction_ - normalized direction vector from the camera towards the point/cursor indication (data type _Vector_).
- _X, Y, Z_ - components of the corresponding vectors (data type _Float_).
> Modifying the Screen To World Space node

- Sources/armory/logicnode/AnimationStateNode.hx
- Sources/armory/logicnode/GetTilesheetStateNode.hx
- Sources/armory/logicnode/SetActionPausedNode.hx
- Sources/armory/logicnode/SetTilesheetPausedNode.hx
- Sources/armory/logicnode/SetTraitPausedNode.hx
- blender/arm/logicnode/animation/LN_get_action_state.py
- blender/arm/logicnode/animation/LN_get_tilesheet_state.py
- blender/arm/logicnode/animation/LN_set_action_paused.py
- blender/arm/logicnode/animation/LN_set_tilesheet_paused.py
This also fixes previous commits that i did not tested.
Users must recreate the `Get Action State` node because i changed it from "Is Playing" to "Is Paused" to match the `Set Action State` node.
Requires: https://github.com/armory3d/iron/pull/106
Question: do `Action` node works also for tilesheets or there is a need for a `Tilesheet` node too?
> Get Tilesheet State node

- Sources/armory/logicnode/SetVibrateNode.hx
- blender/arm/logicnode/native/LN_set_vibrate.py
- blender/arm/props.py
- blender/arm/props_exporter.py
- blender/arm/props_ui.py
- blender/arm/utils.py
- blender/arm/write_data.py
1. For the new settings to fully function, you need to update the submodules so that this Pull Request (https://github.com/Kode/kincmake/pull/100) gets into _armsdk_. Extended settings via `khafile.js`.
2. Added _Android Settings_ panel:
- invisible until the target platform `android-hl` is added to the list;
- inactive until the target platform `android-hl` is selected in the list.
Options:
- _Orientation_;
- _Compile Version SDK_ - from 26 to 30, default 29;
- _Minimal Version SDK_ - from 14 to 30, default 14;
- _Target Version SDK_ - from 26 to 30, default 29;
- _Permissions_ - a list of permissions. If I will duplicate entries in the list, then only unique entries will be included during export. By default, the list is empty;
- _Android ABI Filters_ - a list of platforms to build for …
> Add Android Settings + LN Set Vibrate

- Shaders/volumetric_light/volumetric_light.frag.glsl
Fixes https://github.com/armory3d/armory/issues/1944.
Depending on the lights used in the scene, `visibility` could be undeclared or it got re-declared in some cases.
- Now, if the scene has no lights, the volumetric light is invisible.
- If multiple sun lights exist, only one is taken into account (which is not great but it's more of a temporary solution until the light system gets reworked (if that ever happens)).
- If multiple point lights exist (which doesn't work on DirectX due to https://github.com/armory3d/armory/issues/1772), volumetric lighting is also invisible which is not good but before it just didn't compile.
> Fix volumetric light for different lamp combinations

- blender/arm/make.py
- blender/arm/make_state.py
- blender/arm/props.py
- blender/arm/props_ui.py
- blender/arm/utils.py
Added a panel with settings:
- _Building APK After Publish_ - to start the build after the project has been successfully published (False by default). Disabled if SDK path is not specified;
- _Emulator_ - list of installed emulators in _Android Studio_ (_AVD Manager_). At the start of Blender, the list is always empty, to fill and update it, you must click the _Refresh_ button. To start the emulator, if you wish, you need to press the _Start_ button (the list of emulators is obtained with the `emulator -list-avds` command, the launch is performed with the `emulator -avd [name]` command). The _Start_ button is disabled if the name of the emulator is not selected from the list;
- _Run Emulator After Building APK_ - launch the emulator after successfully building the APK file. Disabled if no …
> Added settings for building APK

- blender/arm/material/cycles_functions.py
- blender/arm/material/cycles_nodes/nodes_converter.py
All operators are now supported and adapted to Blender's functionality. The only exception so far is the modulo operator, `mod` in GLSL works a bit different than `fmod` used by Blender/OSL when using negative values.
I also removed the `AVERAGE` operator because it was removed from Blender (misleading name, it was averaging the direction via add + normalize and wasn't just (A + B) / 2).
> Fully implement the VectorMath node

- blender/arm/material/cycles_nodes/nodes_color.py
- blender/arm/material/cycles_nodes/nodes_converter.py
- blender/arm/material/cycles_nodes/nodes_input.py
- blender/arm/material/cycles_nodes/nodes_texture.py
- blender/arm/material/cycles_nodes/nodes_vector.py
- Constant factors for the MixRGB node are now inlined (actually I think we could also do this for non-constant factors, there are stored in a variable anyways I think?)
- Fixed some socket indices and replaced the indices for some nodes with string identifiers (I'm not sure about the speed loss/how Blender handles this internally)
- Fixed `Normal` output in the Texture Coordinate node for world shaders
- The Light Falloff node now follows Eevee's implementation
- Implemented the Separate HSV node
- Aligned the Light Path node to Eevee's implementation and fixed some socket indices
> More cycles nodes + improvements

- blender/arm/material/cycles.py
- blender/arm/material/cycles_nodes/nodes_converter.py
- blender/arm/material/cycles_nodes/nodes_texture.py
Fixes https://github.com/armory3d/armory/issues/935.
The output still looks different in Blender, Armory samples the texture around a coordinate (which might be slow because the (procedural) texture has do be recalculated 5 times, I don't know?) and Eevee seems to use partial derivatives to get the normals from the height map which might be a better solution.
> Fix bump node when connected to vector output

- Sources/armory/logicnode/GetObjectTraitsNode.hx
- Sources/armory/logicnode/GetTraitNameNode.hx
- Sources/armory/trait/internal/CanvasScript.hx
- Sources/armory/trait/internal/WasmScript.hx
- blender/arm/logicnode/trait/LN_get_object_traits.py
- blender/arm/logicnode/trait/LN_get_trait_name.py
1. Modification of `CanvasScript` and `WasmScript` classes: added a field to save the name of the script/file in the class.
2. Added logical nodes for working with `Traits`. 
Categories: _Trait_.
- `Get Object Traits` - gets an array of `Traits` for the specified object;
- `Get Trait Name` - get the `Trait` name (the name that appears in the list in `Armory Traits`) and its type (_Canvas_, _Wasm_, _Bundle_, _LogicNode_ or _Haxe_).
> LN for Traits

- blender/arm/logicnode/arm_nodes.py
- blender/arm/logicnode/deprecated/LN_get_mouse_lock.py
- blender/arm/logicnode/deprecated/LN_get_mouse_visible.py
- blender/arm/logicnode/deprecated/LN_mouse_coords.py
- blender/arm/logicnode/deprecated/LN_on_gamepad.py
- blender/arm/logicnode/deprecated/LN_on_keyboard.py
- blender/arm/logicnode/deprecated/LN_on_mouse.py
- blender/arm/logicnode/deprecated/LN_on_surface.py
- blender/arm/logicnode/deprecated/LN_on_virtual_button.py
- blender/arm/logicnode/deprecated/LN_pause_action.py
- blender/arm/logicnode/deprecated/LN_pause_tilesheet.py
- blender/arm/logicnode/deprecated/LN_pause_trait.py
- blender/arm/logicnode/deprecated/LN_play_action.py
- blender/arm/logicnode/deprecated/LN_resume_action.py
- blender/arm/logicnode/deprecated/LN_resume_tilesheet.py
- blender/arm/logicnode/deprecated/LN_resume_trait.py
- blender/arm/logicnode/deprecated/LN_rotate_object_around_axis.py
- blender/arm/logicnode/deprecated/LN_scale_object.py
- blender/arm/logicnode/deprecated/LN_set_mouse_lock.py
- blender/arm/logicnode/deprecated/LN_set_mouse_visible.py
- blender/arm/logicnode/deprecated/LN_set_object_material.py
- blender/arm/logicnode/deprecated/LN_surface_coords.py
- blender/arm/node_utils.py
- blender/arm/nodes_logic.py
- blender/arm/utils.py
Linked to https://github.com/armory3d/armory_tools/pull/5.
- Deprecated logic nodes are now also registered, but not in a menu. This makes it possible to access them for reference generation.
- There is now a `@deprecate()` decorator for the node classes to reduce duplicate code:
```python
@deprecate()
class MyNode(ArmLogicTreeNode):
...
@deprecate('AlternativeNode 1', 'Alternative Node 2')
class MyNodeWithAlternatives(ArmLogicTreeNode):
...
@deprecate('AlternativeNode 1', 'Alternative Node 2', message='This node was deprecated because of XYZ')
class MyNodeWithAlternativesAndMessage(ArmLogicTreeNode):
...
```
Using this decorator will automatically deprecate the node ('is_obsolete = True'), set the correct icon (`ERROR`), change the label and add documentation according to the passed …
> Improve handling of deprecated logic nodes

- blender/arm/handlers.py
- blender/arm/nodes_logic.py
Just smaller fixes:
- Libraries still weren't handled correctly
- Fixed duplicate node registration resulting in errors when Armory was disabled and enabled in one Blender session.
- The regular/Blender add node menu (also for shaders) wouldn't work anymore after disabling Armory until restarting Blender (thanks @knowledgenude for reporting)
> Further improve handling of nodes/menu registration

- blender/arm/exporter.py
- blender/arm/profiler.py
- blender/arm/utils.py
Linked to https://github.com/armory3d/armsdk/pull/16.
Combined with the PR above, you can now choose to run [cProfile](https://docs.python.org/3.7/library/profile.html#module-cProfile) when exporting the scene. This will generate a file called `profile_exporter.prof` in the SDK directory with detailed information about the number of calls and the time taken by the functions called during export. This file can then be opened by tools such as [SnakeViz](https://jiffyclub.github.io/snakeviz/) to get a graphical representation of whats happening during export:
----
**Example use case:** 
This is the result when compiling the celshade example project, which takes a huge amount of time. About 3/4 of the time are taken away for the export of individual objects (and analyzing the results a bit …
> Implement optional profiling for export

- blender/arm/props_traits.py
When opening traits on windows, there were paths in the form `a\\b\\c/d/` which led to errors. Using `os.path.join()` solves these issues. Strangely these errors are pretty new so its probably caused by another new usage of os.path.join somewhere else in the code.
If I'm really bored someday I'll maybe update everything to the more safe os.path.join, for now its just a small fix before the next SDK is released :)
> Fix trait paths

- blender/arm/handlers.py
- blender/arm/logicnode/__init__.py
- blender/arm/logicnode/arm_nodes.py
- blender/arm/nodes_logic.py
Fixes https://github.com/armory3d/armory/issues/1975
- Custom categories are no longer displayed above Armory's default categories
- Fixed wrong category names when using `PKG_AS_CATEGORY` (default) in custom node libraries
- Fixed a bug with variable socket amounts for custom nodes
- More os.path.join
- Libraries are now also loaded when Armory is registered and the file that references the library is already opened. This will only work if the file uses the new registration system for nodes *or* if it is opened the first time in the current Blender session. This is because all modules that are imported by the libraries aren't reloaded, only the main module. Maybe we're able to improve this, but I don't now how powerful the importlib module is.
> Custom nodes + libraries improvements (once more)

- blender/arm/props_ui.py
- blender/arm/utils.py
- Added compare function to `utils.py` module
- Added check of Blender version and display of a message about incorrectness during `Play`, `Build`, `Publish` operations
> Checking Blender version for Armory

- blender/arm/logicnode/arm_nodes.py
- blender/arm/logicnode/array/LN_array_add.py
- blender/arm/logicnode/array/LN_array_boolean.py
- blender/arm/logicnode/array/LN_array_color.py
- blender/arm/logicnode/array/LN_array_float.py
- blender/arm/logicnode/array/LN_array_integer.py
- blender/arm/logicnode/array/LN_array_object.py
- blender/arm/logicnode/array/LN_array_string.py
- blender/arm/logicnode/array/LN_array_vector.py
- blender/arm/logicnode/input/LN_on_swipe.py
- blender/arm/logicnode/logic/LN_call_function.py
- blender/arm/logicnode/logic/LN_function.py
- blender/arm/logicnode/logic/LN_gate.py
- blender/arm/logicnode/logic/LN_merge.py
- blender/arm/logicnode/logic/LN_sequence.py
- blender/arm/logicnode/logic/LN_switch_output.py
- blender/arm/logicnode/math/LN_compare.py
- blender/arm/logicnode/string/LN_concatenate_string.py
turns out, some of the nodes's `__init__` functions didn't call their superclass's `__init__`
Also, I had to make `NodeReplacement.Identity` more generic for the detection of node properties. Not perfect, but until there's a way to track what node attributes are properties used in haxe, this might have to do.
> Some more (late) fixes to the node upgrading

- blender/arm/material/cycles_nodes/nodes_texture.py
The musgrave node no longer has a color output socket and the float output socket was interpreted as the color output.
> Fix musgrave texture node

- blender/arm/make.py
This is so you can easily copy and paste the commands for testing purposes instead of having to build the whole project again.
Alternatively a button to play without build could be added to the blender UI to the same effect.
Tested in Linux for Krom
> Show commands that launch build better and play for debugging

- Sources/armory/logicnode/ValueChangedNode.hx
- blender/arm/logicnode/logic/LN_value_changed.py
* `Changed output`: is activated when the connected value is changed.
* `Unchanged output`: is activated when the connected value returns to the initial.
Does not works with `null`, because the initial value will be defined every time until it is not null. I found this https://lib.haxe.org/p/notifier/ but i don't have the required knowledge to implement (and i don't even know if this is related to the purpose of this node).
Also does not works right for vectors in the test i do:
```
vec = inputs[1].get();
vec == inputs[1].get(); // prints false. I would need to use almostEqual here, but why?
```
Linked issue: https://github.com/armory3d/armory/issues/1009
Example: [TestNode.zip](https://github.com/armory3d/armory/files/5507150/TestNode.zip)
> Value Changed node

- Sources/armory/logicnode/VectorMathNode.hx
Fixed error:
`On static platforms, null can't be used as basic type Float`
> LN Vector Math Fix

- blender/arm/make.py
- blender/arm/props.py
- blender/arm/props_ui.py
- blender/arm/utils.py
Panel `Armory Exporter` - `Android Settings` - `Building APK`:
1. `Rename APK To Project Name`
Renames the APK file from app-debug.apk to [project-name]-[version] .apk. Example, for the project example_ball, the result will be the name example-ball-1.0.5.apk.
2. `Copy APK To Specified Folder`
Copies the final file to the folder specified in Preferences.
Preferences `Render: Armory`:
1. `Copy APK To Folder`
The path to the folder where the final APK file will be copied.
2. `Open Directory After Copy`
Open this folder after copying.
Console messages:
```
Rename APK to example-ball-1.0.5.apk
Copy APK to C:\IDE\Test
```
Related to PR: https://github.com/armory3d/armsdk/pull/19
Use-case:
These settings will allow you to have unique names for files, as well as copy them to the required folder …
> Android Settings More

- blender/arm/material/cycles.py
- blender/arm/material/cycles_nodes/nodes_texture.py
- blender/arm/material/cycles_nodes/nodes_vector.py
- blender/arm/material/make_attrib.py
- blender/arm/material/make_depth.py
- blender/arm/material/make_mesh.py
- blender/arm/material/shader.py
Fixes https://github.com/armory3d/armory/issues/1990.
Previously it could happen that normals or other attributes like `vVec` were accessed in shaders before they were declared. Also, the w coordinate socket was mistakenly used as the scale in the musgrave texture node.
This PR was tested with various example files including normal mapping, bump mapping, displacement, etc., tangent export on/off and in forward and deferred render paths.
@luboslenco I'm interested in implementing normal map blending when I get some more time again, do you recommend one certain method? I wrote a bit about it here: https://github.com/armory3d/armory/issues/1968#issuecomment-718766196.
> Fix usage of normals in shaders + smaller shader improvements

- blender/arm/make.py
Requires https://github.com/armory3d/armsdk/pull/18 and https://github.com/Kode/khamake/pull/235.
This makes it possible to pass the `--debug` flag to krafix as well, in order to compile HLSL shaders with debug information. It is then possible to access the .hlsl source code in RenderDoc for easier step debugging.
> Add option to compile with khamake --debug flag

- blender/arm/make.py
- blender/arm/props.py
- blender/arm/props_ui.py
- blender/arm/utils.py
1. Processing data entry into fields:
- `Name` - the field must not be empty. If the user tries to set an empty value, then this field specifies the name of the blend file (this is how it is implemented during assembly). The default is `untitled`.
- `Package` - the field must not be empty, it must not consist only of numbers and start with a number. The `.` symbol is replaced with `_`. The default is `arm`.
- `Bundle` - the field must be filled in according to the mask `[string].[string]`. Each part must not be empty, contain numbers, or start with a number. The default is `org.armory3d`. Previously, this field was blank, in which case the current default was used.
- `Version`. The default is `1.0.0`.
Input in the `Version` field is processed and only allows input by masks:
- 0.0
- 0.0.0 …
> Exporter Panel - Project Settings

- blender/arm/logicnode/math/LN_quaternion_math.py
- blender/arm/logicnode/math/LN_vector_math.py
The error occurs when updating projects with old nodes. Unfortunately, the node is not completely replaced, but the error with deleting the output parameters has been fixed, the incorrect node will not be in the `Logic Editor`.
The error is written here - https://github.com/armory3d/armory/pull/1994#issuecomment-726988371
> Fixed logical nodes Vector Math and Quaternion Math

- blender/arm/make.py
- blender/arm/props.py
- blender/arm/props_ui.py
- blender/arm/utils.py
Added `Armory Exporter` - `HTML5 Settings` panel:
- `Copy Files To Specified Folder` - copy files to the folder specified in the settings after publish. The name of the folder where the result will be copied is formed based on the name of the project and version. Sample, `test-1.0.5`.
- `Run Browser After Copy` - run browser after copy. The url is formed from the one specified in the settings and the directory with the project where it was copied. Sample, `http://localhost/test-1.0.5`.
Console messages:
```
Copy files to ...
Running a browser with a link ...
```
Added settings in Render: Armory:
- `HTML5 Copy Path` - path to copy project after successfully publish (directory on local web-server).
- `Url To Web Server` - url that runs the local server.
Related to PR: …
> HTML5 Settings

- Sources/armory/logicnode/MapRangeNode.hx
- blender/arm/logicnode/math/LN_map_range.py
I guess it  is the same but without clamp checkbox: https://docs.blender.org/manual/en/latest/compositing/types/vector/map_range.html
Use: you have the vertical rotation of the camera axis object and you need to get it in camera FOV to increase the sense of depth when the player looks up or down.
This nodes takes the vertical rotation value (i.e. from -1.5 to 1.5) and changes it to FOV value (i.e. from 1 to 2).
> Map Range node

- blender/arm/logicnode/logic/LN_is_not_null.py
- blender/arm/logicnode/logic/LN_is_null.py
Fixes a few wiki links for renamed nodes.
I think it's better to change the references to `bl_idname` in the future (node labels were only used to quickly get the doc generation system working) but this might require a bit of rewrite of the category system in order to expose this information to the reference generation script.
> Fix some node docstrings

- blender/arm/api.py
- blender/arm/material/shader.py
- blender/arm/props_ui.py
This adds support for a optional panel `Armory Driver Properties` for drivers in the material properties tab (to be used in https://github.com/armory3d/driver_celshade/pull/9). Maybe it makes more sense in the future to register those UI functions via a different API call than the `add_driver` call if we add even more callbacks.
> Add per-material UI support for driver API

- blender/arm/nodes_logic.py
- blender/arm/props_ui.py
This makes it easier to access `arm_material_property` without navigating in the sidebar.
> Add node context menu entry for material parameters

- blender/arm/make.py
- blender/arm/props.py
- blender/arm/props_ui.py
- blender/arm/utils.py
- blender/arm/write_data.py
1. Added a project version to the project name.
2. Windows Settings
- `Visual Studio Version` - select the studio version for which the project will be exported. Options: _2010, 2012, 2013, 2015, 2017, 2019_. Default: _2019_.
- `Update` - checks the installed versions of _Visual Studio_ on the PC and adds `(installed)` to the version in the list if available (for information). Example:
- `Action After Publishing` - select an action after a successful publication. Options:
- `Nothing` - do nothing. Default value;
- `Open In Visual Studio` - open the project in the corresponding studio version;
- `Compile` - compilation of the project;
- `Compile and Run` - compile and run the project. Then the executable file will be copied to the windows-hl folder (where the resources are located).
- …
> Windows Settings – Publish and action after

- Sources/armory/logicnode/GetMouseMovementNode.hx
- blender/arm/logicnode/input/LN_get_mouse_movement.py
- Rename misleading `Delta` socket to `Wheel Delta` (on the Discord channel there was someone asking about how to get the mouse wheel rotation, this is the main reason for this PR)
- Reordered the sockets to make a bit more sense (movement and delta values are now grouped together)
- Node output defaults to `0` now instead of `null` for unsupported operations. This prevents errors on other places
- Better docstring
I'm not even sure if `Mouse Delta` makes sense in this node or if it should get it's own node (it is not per se a "movement" of the mouse I would say?), but I don't know. We should at least keep it for compatibility reasons.
> Improve `Get Mouse Movement` node

- Shaders/chromatic_aberration_pass/chromatic_aberration_pass.frag.glsl
- Sources/armory/renderpath/RenderPathForward.hx
- blender/arm/make_renderpath.py
- blender/arm/write_data.py
Fixes https://github.com/armory3d/armory/issues/1398
This PR adds support for chromatic aberration in the forward renderpath, before this the setting would only work on deferred rendering. Also the compositor flags weren't reset between builds, so until now disabling the `Realtime postprocess` flag for example wasn't taken into account until restarting Blender.
> Forward renderpath: add support for chromatic aberration

- blender/arm/props.py
- blender/arm/props_ui.py
- blender/arm/write_data.py
- `Disable browser context menu` - disable the browser context menu for the canvas element on the page (_index.html_).
Default value `False`.
> Added option for HTML5 Settings

- blender/arm/logicnode/arm_nodes.py
- blender/arm/logicnode/replacement.py
- blender/arm/nodes_logic.py
- blender/arm/props.py
- blender/arm/props_ui.py
- Fixed a bug where the already added replacement node wasn't deleted when an exception occurred, resulting in two nodes
- Moved the replacement code into its own module because it is quite a lot of code (also we probably should soon think about how to handle those ever-growing files like `props_ui.py`, Armory needs a better package structure)
- Added a button to the error dialog that lets you quickly open the project folder with the generated report file
- The traceback of unknown exceptions is now included in the generated report
- Some general cleanup and small message improvements
@niacdoial Is it ok for you if I credit you in the `replacement.py` module docstring, now that the original git history is rather hidden because the code was moved to a new module?
> Fix and further improve node replacement system

- Sources/armory/logicnode/AddPhysicsConstraintNode.hx
- Sources/armory/logicnode/AddRigidBodyNode.hx
- Sources/armory/logicnode/PhysicsConstraintNode.hx
- Sources/armory/trait/physics/bullet/PhysicsConstraint.hx
- Sources/armory/trait/physics/bullet/PhysicsConstraintExportHelper.hx
- Sources/armory/trait/physics/bullet/PhysicsWorld.hx
- Sources/armory/trait/physics/bullet/RigidBody.hx
- blender/arm/exporter.py
- blender/arm/logicnode/physics/LN_add_physics_constraint.py
- blender/arm/logicnode/physics/LN_physics_constraint.py
- Two new nodes to add physics constraints during runtime.
- Improve the Physics Constraint trait. Now the trait uses `objects` instead of object names, making it more reliable.
- Added support functions to handle the setting of constraint parameters.
- Added a new helper trait to help export constraints from Blender.
- Added some descriptive documentation.
Requires [Haxebullet #39](https://github.com/armory3d/haxebullet/pull/39#issue-532862113).
> New Physics Constraint nodes. Improve Bullet Physics constraint trait

- Sources/armory/logicnode/PlaySoundRawNode.hx
- blender/arm/logicnode/sound/LN_play_sound.py
- blender/arm/make_logic.py
Added a checkbox to Play Sound nodes for selecting whether the sound should be loaded into memory or streamed from disk.
I had to raise the number of allowed node properties to 10 (previously 5) for it to work, but that shouldn't break anything (no other node uses `property5` - `property9`).
> Add 'stream' option to Play Sound nodes

- Sources/armory/logicnode/SetShaderUniformNode.hx
- Sources/armory/object/Uniforms.hx
- blender/arm/logicnode/renderpath/LN_set_shader_uniform.py
This is an addition to the already existing material param nodes with a more generalized way of setting uniforms for all kinds of shaders (the currently existing nodes require a parameter node in the material). This allows for example to also control world shaders (weather, lightning etc.), it works best in combination with Armory's `Shader Data` material node.
I put the node into the renderpath category because it is not related to materials only.
> Add SetShaderUniform node

- blender/arm/logicnode/array/LN_array.py
- blender/arm/logicnode/array/LN_array_boolean.py
- blender/arm/logicnode/array/LN_array_color.py
- blender/arm/logicnode/array/LN_array_float.py
- blender/arm/logicnode/array/LN_array_integer.py
- blender/arm/logicnode/array/LN_array_object.py
- blender/arm/logicnode/array/LN_array_string.py
- blender/arm/logicnode/array/LN_array_vector.py
- blender/arm/logicnode/input/LN_gamepad.py
- blender/arm/logicnode/input/LN_keyboard.py
- blender/arm/logicnode/input/LN_mouse.py
- blender/arm/logicnode/input/LN_touch.py
- blender/arm/logicnode/input/LN_virtual_button.py
- blender/arm/logicnode/logic/LN_loop.py
- blender/arm/logicnode/logic/LN_merge.py
- blender/arm/logicnode/math/LN_math.py
- blender/arm/logicnode/math/LN_vector_math.py
- blender/arm/logicnode/miscellaneous/LN_timer.py
- blender/arm/logicnode/object/LN_object.py
Implements https://github.com/armory3d/armory/issues/2014.
Reposting the screenshots from the linked issue (for more details please refer to that):
- Some nodes will not display a dynamic header if the sockets are connected or only parts of the header are dynamic (for example `x...5` for a loop node where the lower value is a connected socket)
- If a user renames a node, Blender will only display that name (= no dynamic header), which gives the user more freedom.
Also, we should probably think about adding a super class for array nodes, they basically have 90% the same code.
> Add dynamic node labels

- blender/arm/write_data.py
Link to https://github.com/armory3d/armory/issues/1519.
Fixed a bug where enabling the `Generate Relative Paths` setting could lead to exceptions when the SDK and the project directory were on different drives. Now absolute paths are used in this case (however asset paths that are on the same drive are not affected for example).
Only tested on Windows, I would really appreciate it if somebody could test this PR on Linux or MacOS.
> Use relative paths only when path/reference are on the same drive

- blender/arm/exporter.py
Fixes https://github.com/armory3d/armory/issues/2054.
Bone markers didn't work because the `action` object was overridden while handling the autobake setting.
> Fix bone markers export

- Sources/armory/trait/physics/bullet/KinematicCharacterController.hx
Same fix as https://github.com/armory3d/armory/pull/1907
> Fix inverted margin for Kinematic Character

- Shaders/deferred_light/deferred_light.frag.glsl
- Shaders/deferred_light_mobile/deferred_light.frag.glsl
Changed how a spot light is detected when sampling light, which caused false positives and produced
that visual artifact described in this issue https://github.com/armory3d/armory/issues/1289#issuecomment-743190855 when a cluster/pixel was detected incorrectly as being lit with a spot light when there were no spot lights in the scene.
> Solve artifact with clustering of lights

- blender/arm/material/make.py
- blender/arm/material/make_shader.py
Closes https://github.com/armory3d/armory/issues/2072 (please refer to this for more details).
When multiple objects share one material but only some of them are instanced there can be visible flickering in the game because instance attributes like `ipos` are set with garbage values. In those cases there is now a warning printed. Is there a reason why instancing is set per-object and not per-material?
I moved the instancing part in its own method so that we can display the warning for custom shaders too while having to iterate only once over all material users when _not_ using custom shaders. The reason there is only a warning and no workaround behaviour is that users can then decide what to do (for example split materials or enable instancing for all objects with that material).
I also …
> Show warnings for invalid instancing configurations + cleanup

- blender/arm/props_lod.py
- blender/arm/props_traits.py
- blender/arm/props_ui.py
UI updates to the object properties panels for Blender 2.9, most of it is just to get similar results to the old 2.8 look. Some visual changes:
**Reordered the trait types to roughly match the amount of usage:**
**The proxy menu now uses a column heading instead of a label which seems to be a new Blender convention:**
**The logic node operators under the trait menu now have shorter labels to better fit into the layout:**
Unfortunately (as you can see in the last image), there is a small bug in Blender's UI that places the checkbox in template lists a few pixels too much to the left. I hope this gets fixed in the future, I wasn't able to find a workaround.
> [Blender 2.9] Object panel UI

- blender/arm/logicnode/arm_nodes.py
- blender/arm/logicnode/input/LN_on_swipe.py
- blender/arm/nodes_logic.py
- blender/arm/props_exporter.py
- blender/arm/props_ui.py
The [Blender 2.9 release notes](https://wiki.blender.org/wiki/Reference/Release_Notes/2.90/Python_API) state:
> With the new operator search that only searches through menus, add-ons that expose operators only through search need to be updated. In general it is good practice to always expose operators through menus so users can find them.
But it doesn't seem to affect Armory operators as far as I could see. Nonetheless, I updated a few operators so that they no longer show up in the search menu when they are not meant to appear there.
> Blender 2.9: Update operator options

- blender/arm/props_traits.py
When a project was never compiled before and there was no `Sources` directory, editing a bundled trait would fail with an exception.
> Fix editing bundled traits if the project was never compiled

- blender/arm/logicnode/arm_nodes.py
- blender/arm/props_tilesheet.py
Some various, smaller fixes because more operators are now automatically exposed to the search menu. Some `poll()` methods only work in the correct context.
> [Blender 2.9] Search menu fixes

- blender/arm/make_logic.py
Fixes https://github.com/armory3d/armory/issues/2090.
Reroutes were not followed correctly before, the input's `from_socket` was taken from the first node in the reroute line (that is the first reroute, and reroutes have one socket only => the index is always 0).
What looks like much in the diff is actually just a little while loop added. Tested it with a lot of example files, all worked as before.
> Fix Reroute nodes

- blender/arm/make.py
`Finished in 0.29s` instead of
`Finished in 0.2960593223571777`
> Print rounded build time to console

- blender/arm/utils.py
Removes the trailing slash of the sdk path (which gets automatically added by blender).  
Before that combined paths did have 2 slashes in between:
`…/armsdk//Krom/Krom` → `…/armsdk/Krom/Krom`
> Normalize sdk path

- blender/arm/material/cycles.py
- blender/arm/material/cycles_nodes/nodes_input.py
- Added support for the new `Alpha` output socket
- UV maps and vertex colors are now only available in the new `Geometry` mode as in Blender (they depend on the mesh)
- Added support for custom properties and even Blender properties from the object that uses the material (https://developer.blender.org/rB6fdcca8de6). If multiple objects use the material, only the first is used for now because the values would then need be passed as uniforms. This is something to do in a future PR.
> [Blender 2.9] Update attribute node

- Shaders/custom_mat_presets/custom_mat_deferred.frag.glsl
- Shaders/custom_mat_presets/custom_mat_deferred.vert.glsl
- Shaders/custom_mat_presets/custom_mat_forward.frag.glsl
- Shaders/custom_mat_presets/custom_mat_forward.vert.glsl
- blender/arm/material/make.py
- blender/arm/props_ui.py
This adds a button to the material UI that opens a small dialog for creating a custom material. All files and folders will be created automatically without having to setup and lookup everything by yourself. The shaders used are the slightly modified minimal glsl examples from [the wiki](https://github.com/armory3d/armory/wiki/renderpath#forward-path), I hope the path where they are currently saved is ok (I can still change that if it doesn't fit). The glsl files are extensively commented to make it easier to getting started with shader programming, json doesn't allow comments.
If the material definition file and/or the glsl files exist already, separate warnings are displayed (Blender makes a confimation dialog rather complicated):
> Add button to create a new custom material

- Shaders/deferred_light/deferred_light.frag.glsl
- Shaders/deferred_light/deferred_light.json
- Shaders/deferred_light_mobile/deferred_light.frag.glsl
- Shaders/deferred_light_mobile/deferred_light_mobile.json
- Shaders/std/clusters.glsl
- Shaders/std/light.glsl
- Shaders/std/light_mobile.glsl
- Shaders/std/shadows.glsl
- Shaders/volumetric_light/volumetric_light.frag.glsl
- Shaders/volumetric_light/volumetric_light.json
- Sources/armory/renderpath/Inc.hx
- Sources/armory/renderpath/RenderPathCreator.hx
- Sources/armory/renderpath/RenderPathDeferred.hx
- Sources/armory/renderpath/RenderPathForward.hx
- Sources/armory/trait/internal/DebugConsole.hx
- blender/arm/make_renderpath.py
- blender/arm/material/make_cluster.py
- blender/arm/material/make_mesh.py
- blender/arm/material/shader.py
- blender/arm/props_renderpath.py
- blender/arm/props_ui.py
- blender/arm/write_data.py
With this it will now possible to enable atlasing of shadow maps, which solves the existing limitation of 4 lights in a scene: https://github.com/armory3d/armory/issues/1289
This is done by grouping the rendering of shadow maps, that currently are drawn into their own images for each light, into one or several big textures. This was done because the openGL and webGL version Armory targets do not support dynamic indexing of shadowMapSamplers, meaning that the index that access an array of shadow maps has to be know by the compiler before hand so it can be unrolled into if/else branching. By instead simply using a big shadow map texture and moving the dynamic part to other types of array that are allowed dynamic indexing like vec4 and mat4, this limitation was solved.
The premise was simple …
> Add support for shadow map atlasing

- blender/arm/material/shader.py
Attempt to solve this https://github.com/armory3d/armory/pull/2102#issuecomment-778844866
The error was introduced by `add_include_front`, which allowed the `clusters.glsl` include to be written before `compiled.inc`. This produced a compiler error because `clusters.glsl` relies on macros defined in `compiled.inc`.
Tested on Linux Krom with Armory PBR material with opacity < 1.0.
> Make sure compiled.inc is always first when parsing shaders for clusters

- Shaders/deferred_light/deferred_light.frag.glsl
- Sources/armory/renderpath/RenderPathDeferred.hx
- blender/arm/make_renderpath.py
- blender/arm/material/make_mesh.py
- blender/arm/props.py
- blender/arm/props_ui.py
I thought I had made a pull request about this earlier, but turns out I had forgotten to.
In any case, it's a fix for https://github.com/armory3d/armory/issues/1615 which involves issues with blending. On deferred blending causes a setPipeline error, whilst forward displays nothing.
Before on forward:
After:
> Blending fix + ignore irradiance per material

- blender/arm/write_data.py
I might be mistaken, but shouldn't the  `--debug` param not get automatically added for html5, in non-publish mode, to have source-map support ?
> Write debug param by default

- Shaders/std/light.glsl
- Shaders/std/light_mobile.glsl
- Shaders/std/shadows.glsl
- blender/arm/make.py
- blender/arm/write_data.py
This solves https://github.com/armory3d/armory/issues/2110 by applying a workaround discussed in the issue found by @Naxela: 
WebGL supposedly has the same texture coordinate system as openGL, but for whatever reason coordinates require a special treatment in order to make texture reading (and consequently shadows) work on Firefox and Chrome (Windows and Linux), so this should solve it for spot lights, sun and point lights.
Explanation:
Basically what's done is coordinates are flipped after applying the projection (in LightObject and Uniform for spot lights and sun respectively, and sampleCube() in the shaders for point lights). Then after computing the uv for the atlas, the coordinates are flipped again and that makes it work.
The result are coordinates which are "offseted"
Also a …
> Fix shadow artifacts for HTML5 with shadow map atlas

- blender/arm/material/make_cluster.py
- blender/arm/material/make_mesh.py
- blender/arm/material/shader.py
This should fix an issue where the uniform for shadowMapAtlas used with the single atlas option was not added when having just 1 light.
Originally reported here https://forums.armory3d.org/t/krom-windows/4496/8
> Fix forward+single atlas failing to compile with just 1 light

- blender/arm/keymap.py
- blender/arm/lightmapper/keymap/__init__.py
- blender/arm/make_renderpath.py
- blender/arm/props_bake.py
First commit is a fix where unallocated material slots would cause an error with the arm_ignore_irradiance check, as reported by a user on Discord:
Second commit is a fix for the annoying winman error - It's already fixed in the upcoming lightmapper update for the 2.9 branch, but I'm not sure how far out the branch is yet, so I've fixed it for the main branch as well:
> Fix for material NoneType and fix for Blender exit error

- Shaders/std/clusters.glsl
- blender/arm/write_data.py
This fixes a current problem with lights that occurs when getting too close to the camera. The issue is related to the clustering algorithm and the "cluster near solution".
> #### "Cluster near solution" explanation for context:
> Because of the logarithmic nature of how the Z slice is calculated, clusters slices get "burned" too quickly at the start of the frustum, which is not ideal. So to solve this an offset is applied to the start of the cluster frustum, which is clusterNear.
Cluster near solves one problem but creates another one: There is a gap between the near plane and the cluster near offset that gets completely ignored when calculating the Z slice. And this results in the visual artifact of a visual space not being affected by light whatsoever.
The proposed solution is to …
> Fix light visual artifact when close to the camera

- blender/arm/props_traits.py
- blender/arm/props_traits_props.py
- blender/arm/utils.py
This PR introduces a regex-based system for parsing `@prop` definitions from Haxe scripts, an example of the regex can be seen here: https://regex101.com/r/bbrCzN/7.
Changes:
- The code is much easier to understand and it's easier to make changes
- It no longer matters if `@prop` is on the same line or on the line above the actual property definition, both is correct Haxe syntax
- More possibly erroneous situations are recognized and a warning is displayed
- More precise warning messages
> Make `@prop` recognition more robust

- Shaders/deferred_light_mobile/deferred_light.frag.glsl
- Shaders/deferred_light_mobile/deferred_light_mobile.json
- Shaders/std/light_mobile.glsl
Tested with Krom Linux with point lights and spot lights with deferred and forward using the Mobile render path preset, 
Test file: [deferred_mobile.blend.zip](https://github.com/armory3d/armory/files/6138138/deferred_mobile.blend.zip)
> Fix shadow rendering for point and spot lights for deferred and forward mobile

- Shaders/deferred_light/deferred_light.frag.glsl
- Shaders/deferred_light_mobile/deferred_light.frag.glsl
- Shaders/volumetric_light/volumetric_light.frag.glsl
- Sources/armory/renderpath/Inc.hx
- blender/arm/material/make_cluster.py
With this it's possible to combine lights that cast no shadows (cast_shadow=false/"Shadow" toggled off on Blender's UI) with shadow casting lights, otherwise previously broken because of the hardcoded nature of `ReceiveShadows` when invoking `sampleLight()`.
This was done by exposing cast_shadows to the shaders through pointLightData.
Note: 
Because there was not enough space I had to increment the requirement for lights from 2 to 3 vec4 in the lightsArray, so this solution leaves 3 unused spaces per light (for now). I've tried to change lightsArray to be an array of vec3 to avoid wasting space, but after testing I've noticed it doesn't play nice on Windows with Direct3D, so I had to revert it to vec4.
Tested with Krom Linux / Krom Windows, with point lights and spot lights with deferred …
> Fix shadows not working when there are lights present with cast_shadow=false

- blender/arm/props.py
- blender/arm/props_collision_filter_mask.py
* Moved the collision filter mask panel under armory props to keep UI
more tidy.
* Moved the `arm_rb_collision_filter_mask` property out of the
props_collision_filter_mask to be with the rest of the properties.
* Changed name and description of collision filter mask to be more
consistent with the existing rigid body UI.
> Modified UI for collision filter props_collision_filter_mask

- blender/arm/exporter.py
- blender/arm/props_ui.py
Defining the final type of rigid body is not as straight forward in the UI because of the many options that can change it, so I thought it could be exposed in the UI to make it more clear:
> Expose the exported rigid body type to the UI to make rb less confusing

- blender/arm/exporter.py
- blender/arm/log.py
- blender/arm/make.py
- blender/arm/props_ui.py
Log and show and error instead of just letting the error pop up in the blender UI, like this: 
Instead show this
and this:
Ideally an error should probably stop the building, but I'm not sure if there is a system in place to do that... for now showing a better error would do 
Related: https://github.com/armory3d/armory/issues/2136, https://github.com/armory3d/armory/issues/1411
> Show error in the UI for tangent calculation error instead of just crashing to blender UI

- blender/arm/material/mat_utils.py
The extra input node in the principled for 2.9+ is now taken into consideration.
Before:
Now:
> [Blender 2.9] Fix material translucency in Blender 2.9+

- blender/arm/material/make_mesh.py
Previously it could happen that `gl_Position` was set before taking the instancing data into account, resulting in all instances drawn with the same transformations.
> Fix writing to gl_Position before instancing code

- blender/arm/utils.py
Fixes https://github.com/armory3d/armory/issues/2143.
I also think there was a similar issue somewhere that could be fixed by this (I had the changes already stashed in my local repo but forgot about it...) but I can't find it anymore/am not sure if it existed at all. If anyone knows, please let me know.
> Replace ' and " characters in asset names

- Shaders/deferred_light/deferred_light.json
- Shaders/deferred_light_mobile/deferred_light_mobile.json
- Shaders/volumetric_light/volumetric_light.json
- blender/arm/material/make_mesh.py
user `Lytz1` over the Armory discord server found the issue on this test file: [AtlasShadowTest.zip](https://github.com/armory3d/armory/files/6224434/AtlasShadowTest.zip), which upon investigation it seems the problem is that the uniform variables that the deferred light shader relies on for computing the sun shadows (`LWVP` and `casData`) are computed with the incorrect light (the point light in the test file).
Before:
After:
This occurs because when generating those uniforms, `Uniform` expects you to set up the `light` parameter of `renderpath` correctly. So it can occur a case where the wrong light ends up picked instead of the sun when computing the uniform data for the `deferred light` shader.  
Solution: So the solution was to simply remove the need for the user input and instead …
> Fix case where sun shadows are not working if there are other type of lights present 

- Shaders/std/sky.glsl
- Sources/armory/math/Helper.hx
- Sources/armory/object/Uniforms.hx
- Sources/armory/renderpath/Nishita.hx
- blender/arm/exporter.py
- blender/arm/make_world.py
- blender/arm/material/cycles.py
- blender/arm/material/cycles_nodes/nodes_texture.py
- blender/arm/material/shader.py
- blender/arm/props.py
- blender/arm/props_ui.py
- blender/arm/write_probes.py
This PR adds an implementation of the Nishita sky model which was introduced in Blender 2.9. It was ported from https://github.com/wwwtyro/glsl-atmosphere which is licensed under the [Unlicense](https://github.com/wwwtyro/glsl-atmosphere/blob/master/LICENSE).
- To make it work fast, I moved the computation of the inner integral to a precalculated 2D LUT texture that only needs to be recalculated if the density parameters change. In the future we could improve things further by (optionally) rendering the sky to a lower resolution texture first, but that's not part of this PR. The LUT also makes it possible to store presets for different atmospheres.
- Also, I added support for all the node settings such as air, dust and ozone density …
> [Blender 2.9] Nishita sky model & (ir)radiance support for all world shaders

- Sources/armory/renderpath/Inc.hx
This solves an issue where lights waiting to be collected by the GC after being removed (by calling remove() either manually or after loading a scene) could interfere with the algorithm that add lights to atlases.
The solution was to introduce a callback only used for shadow map atlasing whenever a light gets removed. That way the main tile gets properly notified of this event and can free itself accordingly instead of the old method of waiting for the reference of the light to be null. An additional callback was setup to remove the tile from the activeTiles.
Depends on https://github.com/armory3d/iron/pull/122
> Fix detection of removed lights by shadow map atlas

- Sources/armory/logicnode/GetSystemName.hx
Fixed `Unknown identifier : systemName` error as observed by @onelsonic in https://github.com/armory3d/armory/pull/2153.
> Fix GetSystemName node

- Sources/armory/renderpath/Inc.hx
- Sources/armory/trait/internal/DebugConsole.hx
This is a first step to add debug info to help understand what is going on with shadow map atlases by displaying some information like tile size, current size, max size, free tiles, etc. 
When single map is enabled
No single map:
> Add shadow map atlases info to the debug console

- blender/arm/material/make_overlay.py
This PR adds a previously missing call to `make_finalize.make()` after overlay materials are created to ensure that inputs/outputs referenced in the shader are actually included. There were issues when using the texture coordinate node on overlay materials for example.
> Fix creation of overlay materials

- blender/arm/material/cycles_nodes/nodes_input.py
> Fix export of attribute node if no UV map exists

- Sources/armory/renderpath/Inc.hx
- Sources/armory/trait/internal/DebugConsole.hx
This is to help debug atlas rendering and logic performance:
Depends on https://github.com/armory3d/iron/pull/123
> Add profiling of shadow map atlas logic to debug console

- Sources/armory/renderpath/Inc.hx
This solves an oversight that basically made all atlases share the their tileSizesFactor, a variable used to quickly lookup tile tile sizes depending on the shadowMapScale. So if cascade size was higher than cube map size, then point light atlases would use incorrect values and break.
> Make tileSizes and TileSizesFactor non-static

- Shaders/std/shadows.glsl
The extra calculation that wasn't supposed to be there produced some artifacts with point light shadows:
Now:
> Fix artifact with point light soft shadow in shadow map atlas

- blender/arm/props_ui.py
One click less to enable/disable the debug console if the panel is closed.
Previously:
Now:
> [Blender 2.9] Slightly improve debug console panel UI

- blender/arm/exporter.py
Fixes https://github.com/armory3d/armory/issues/2175.
This issue occurred because of a comparison of scene object names with the asset name of a linked object instead of its actual name (asset names aren't comparable with scene object names).
I also tested this PR with the blend file in https://github.com/armory3d/armory/pull/1597, which first introduced the now fixed code. It should work for both cases now.
> Fix double-export of linked objects (#2175)

- blender/arm/props_renderpath.py
- blender/arm/props_ui.py
* Made shadow map atlas sizes enum's values dynamic:
This allows reducing issues related to picking a "wrong" size for the atlases.
* Added a legend below shadow map sizes to have an idea of how much lights can an option fit.
* Separated listing of subdivisions to include point lights.
* Disabled cubemap size if single map is enabled.
* Added a warning when an atlas is higher than 2048 (arbitrary) to inform that the game might crash if the size is not allowed. (might be better to move it in the future to a warning grouped with also checking other texture assets to inform about this).
> Small improvements for the Shadow Map Atlas Blender UI

- Sources/armory/logicnode/MergeNode.hx
- blender/arm/logicnode/logic/LN_merge.py
- blender/arm/logicnode/replacement.py
Closes https://github.com/armory3d/armory/issues/2189 and requires https://github.com/armory3d/armory_tools/pull/8 for the documentation.
There is now a dropdown that lets you choose whether the node should activate its output for each active input individually or only once per frame for the first active input. If the first mode is selected, there is a new output that lets you access the index of the input that activated the node.
> Merge node: add execution mode and output for input index

- Sources/armory/logicnode/BoneFKNode.hx
- Sources/armory/logicnode/BoneIKNode.hx
- Sources/armory/logicnode/GetBoneFkIkOnlyNode.hx
- Sources/armory/logicnode/GetBoneTransformNode.hx
- Sources/armory/logicnode/SetBoneFkIkOnlyNode.hx
- blender/arm/logicnode/animation/LN_bone_ik.py
- blender/arm/logicnode/animation/LN_get_bone_fk_ik_only.py
- blender/arm/logicnode/animation/LN_get_bone_transform.py
- blender/arm/logicnode/animation/LN_set_bone_fk_ik_only.py
Requires https://github.com/armory3d/iron/pull/126
This PR introduces 
1. An upgraded Inverse Kinematics node, that includes pole location, bone roll, chain length and more. For better control IK and FK is now solved only when called. Before, once called FK and IK were solved every frame and could not be stopped.
2. Nodes to set and get if a bone is controlled only by forward/inverse kinematics and should ignore other animations
3. Node to get a bone's transform in world space.
4. This PR also improves usability of the FK and IK nodes so they can now be used in a sequence to get better results.
> Improve bone IK. Add new nodes for better animation control

- blender/arm/material/make_mesh.py
This fixes the rendering part of https://github.com/armory3d/armory/issues/2212.
`gl_Position` was set before the instancing code in the vertex shader, this was the same issue as already fixed for desktop renderpaths in https://github.com/armory3d/armory/pull/2141.
> Fix instancing on mobile and solid renderpaths

- Shaders/std/sky.glsl
- blender/arm/material/cycles.py
- blender/arm/material/make_attrib.py
- blender/arm/material/make_depth.py
- blender/arm/material/make_finalize.py
- blender/arm/material/parser_state.py
This fixes https://github.com/armory3d/armory/issues/2186.
The issue was caused by the Layer Weight node which needs to access normals that were not available in the generated shadowmap shaders. Because the Layer Weight node might change the opacity of objects depending on normals and thus also should affect shadowmap rendering, the normals are now added to the shader if this is not yet the case (e.g. this is already done when displacement is enabled).
@luboslenco do you remember what the following comment (on now removed code) meant?
https://github.com/armory3d/armory/blob/138386f02a031e958daec1d0dca1ab2af1cf7f45/blender/arm/material/make_depth.py#L35-L37
How is something discarded at compile time (particularly by adding `vec3 n`)? Or is this just related to the discarding of fragments …
> Fix Layer Weight node and multiple cycles shaders in one material

- Sources/armory/logicnode/SelectNode.hx
- blender/arm/logicnode/arm_nodes.py
- blender/arm/logicnode/logic/LN_select.py
- blender/arm/nodes_logic.py
Closes #2200, closes #2201.
This PR adds a new `Select` node with two different modes: it can either select an input value based on a given index, or it can forward an input value based on the index of a corresponding action input:
Unfortunately the colors of the Int and Dynamic type sockets are very very similar, maybe this should be adjusted in the future.
> Add Select node

- Sources/armory/trait/internal/MovieTexture.hx
Fixes https://github.com/armory3d/armory/issues/1562.
Previously, the rendertarget used for rendering movies was static. This PR makes the rendertarget non-static and instead adds a cache that makes it possible to reuse rendertargets with the same size to lower memory consumption compared to not using a cache.
> Fix rendering multiple movie textures 

- Sources/armory/logicnode/GetMouseStartedNode.hx
- Sources/armory/logicnode/OnCanvasElementNode.hx
Fixes the remaining error of https://github.com/armory3d/armory/issues/2229 (See https://github.com/armory3d/armory/commit/2f1fe4ef0bdc4bf6bce36418345f0a6f5951ea56 for reference) as well as a typo that caused a redefinition of a node class.
> Fix compilation of some nodes

- blender/arm/handlers.py
- blender/arm/make.py
- blender/arm/props_ui.py
Fixes https://github.com/armory3d/armory/issues/2237. Please refer to that issue for a detailed explanation of this PR.
**Short summary of the changes:**
- If Blender is run in the background, there is no longer threading to wait for subprocesses, instead the main thread waits and blocks execution. There is no UI that can freeze and threading leads to problems because Blender finishes with the executing script before the thread ends, resulting in crashes and error messages.
- If Blender is run with UI, the `done` callback that is executed after a subprocess has finished is no longer called in the thread that waits for the subprocess but instead is called in the main thread to have access to Blender data without crashing. This is solved via a queue between the threads that sends the …
> Fix threading and publishing in background mode

- Sources/armory/trait/physics/bullet/PhysicsConstraintExportHelper.hx
- blender/arm/exporter.py
- blender/arm/props.py
- blender/arm/props_ui.py
This PR adds a new property to the physics constraint tab:
This allows for adding physics constraints relative to its parent object or collection. This way, when a collection with objects having physics constraints is spawned at runtime, the constraint is added between these new objects.
Previously, the constraints were added only between an already existing object and the new object.
> Add option for relative physics constraint

- Sources/armory/logicnode/GetLocationNode.hx
- Sources/armory/logicnode/SetLocationNode.hx
- Sources/armory/logicnode/VectorToObjectOrientationNode.hx
- Sources/armory/logicnode/WorldVectorToLocalSpaceNode.hx
- blender/arm/logicnode/transform/LN_get_object_location.py
- blender/arm/logicnode/transform/LN_set_object_location.py
- blender/arm/logicnode/transform/LN_vector_to_object_orientation.py
- blender/arm/logicnode/transform/LN_world_vector_to_local_space.py
Proposal fix for https://github.com/armory3d/armory/issues/2241
* Improved docs for **World Vector to Local Space** and **Vector to Object Orientation** nodes to be used in cases where don't have parent.
* Added Subtract option for World Vector to Local Space node
> Add "Parent Relative" option to location nodes

- Sources/armory/ui/Canvas.hx
Fixes https://github.com/armory3d/armory2d/issues/62, now custom fonts can be used on all element types.
> UI Canvas: use font from asset for all element types

- Sources/armory/renderpath/Inc.hx
Added 512 option to Inc so it doesn't fails compilation because of
missing option as explained here in the issue.
Solves https://github.com/armory3d/armory/issues/2252#issue-937328497
> Fix compiling error with shadow map atlas shadow size option

- Sources/armory/logicnode/GetInputMapKeyNode.hx
- Sources/armory/logicnode/OnInputMapNode.hx
- Sources/armory/logicnode/RemoveInputMapKeyNode.hx
- Sources/armory/logicnode/SetInputMapKeyNode.hx
- Sources/armory/system/InputMap.hx
- blender/arm/logicnode/input/LN_get_input_map_key.py
- blender/arm/logicnode/input/LN_on_input_map.py
- blender/arm/logicnode/input/LN_remove_input_map_key.py
- blender/arm/logicnode/input/LN_set_input_map_key.py
I don't know if this layout of nodes are good to have full control over the input maps, so if anyone have some suggestion im here!
**Still missing:**
* Create input maps from Blender UI
* A way to create **input map groups** that allow recycle input maps (i.e. for local multiplayer with different indexes on gamepad). I couldn't find a good way to do it without adding considerable complexity to it.
I also ask for someone with gamepad to test if the triggers are working with the deadzone right :)
> Improved Input Map and added nodes to it

- Shaders/deferred_light/deferred_light.frag.glsl
This PR fixes the second example from issue https://github.com/armory3d/armory/issues/2166 and probably also the original issue. @knowledgenude can you please test this if you have the project still around?
The reason for the artifacts was that `gbuffer2` could be accessed even if it was not used, thus it was filled with left-over values from other usages on OpenGL. On DirectX this was not an issue (probably undefined behaviour).
> Fix visual artifacts caused by invalid gbuffer2 on OpenGL

- blender/arm/utils.py
Allows to have (optional) spaces before and after `:` trait prop type annotations. 
So far only:
`@prop var name: T` was allowed.
With this:
`@prop var name : T`
`@prop var name:T`
is valid too.
> Fix fetch trait prop type

- blender/arm/material/make_attrib.py
- blender/arm/material/make_mesh.py
Fixes https://github.com/armory3d/armory/issues/2279. The necessary code for exporting `texCoord1` was simply missing on mobile.
> Fix usage of multiple UV maps on mobile render path

- Sources/armory/trait/ArcBall.hx
Minor ArcBall improvements.
- Removes unnecessary calls to `buildMatrix`
- Adds `axis` trait prop to have control over direction and speed of the rotation
> ArcBall axis trait prop

- blender/arm/utils.py
From the [Python documentation](https://docs.python.org/3/library/os.path.html#os.path.join):
> Note that since there is a current directory for each drive, os.path.join("c:", "foo") represents a path relative to the current directory on drive C: (c:foo), not c:\foo.
This was an issue if a project was stored at the root of a hard drive, thanks to the Discord user "karthiban" for reporting this :)
> Windows: fix arm.utils.get_fp() if the project path is a drive root

- Sources/armory/trait/internal/CanvasScript.hx
- Sources/armory/ui/Canvas.hx
Fixes https://github.com/armory3d/armory/issues/2249, non-default fonts were always loaded as a `kha.Image` and thus had no `height()` function.
> Canvas: fix using non-default fonts

- Shaders/volumetric_light/volumetric_light.frag.glsl
This should solve an issue that prevents volumetric lights from working when shadow map atlasing is enabled. Tested on Krom linux (openGL) with the volumetric example from the examples repo.
> fix volumetric lights not working when shadow map atlas is enabled

- Shaders/std/math.glsl
- Shaders/std/sky.glsl
- Sources/armory/renderpath/Nishita.hx
Fixes https://github.com/armory3d/armory/issues/2295 and requires https://github.com/armory3d/iron/pull/134.
It could happen that values returned by `dot()` were slightly larger than 1 or less than -1 due to precision errors, but the return value of `acos()` is undefined outside of [-1, 1]. This would lead to NaN values on some GPUs, causing visible artifacts.
Also I moved another calculation of the inner scattering integral into the LUT precalculation, with the big advantage that the LUT no longer contains inf values which could potentially lead to other issues. The values are now only slightly larger than 1 (max) and as a positive side effect we need much less dithering because apparently the interpolation of the LUT works much better in this range. Also, it is a tiny bit faster now.
> Fix nishita artifacts and improve LUT value range

- blender/arm/write_data.py
Fixes https://github.com/armory3d/armorcore/issues/32. I'm not sure whether ES6 can be enabled for html5 targets as well without loosing support for some target systems, so it's krom-only for now.
Also the 'armory' define wasn't written to the khafile which is fixed now.
> Switch to ES6 on krom target and fix 'armory' define

- blender/arm/lib/server.py
Allows to:
- Disable logging of http requests to terminal as it is redundant with devtools
- Change the webserver port in case already used
Related PR in armsdk: https://github.com/armory3d/armsdk/pull/30
> HTML5 webserver log, port prefs

- Sources/armory/import.hx
- Sources/armory/system/Assert.hx
- blender/arm/props.py
- blender/arm/props_ui.py
- blender/arm/write_data.py
This PR adds an `assert()` macro to Armory in order to make the handling of some error cases easier and optional for better performance. This is especially helpful for checking correct user input in logic nodes for example, but this PR doesn't introduce any code yet that actually uses the macro. Assertions are _completely_ turned off and omitted from the code when publishing a build.
Please note that assertions don't replace checks that are required during runtime! For example they should not replace important safety checks in some nodes where the input is allowed to be invalid during runtime (e.g. unavoidable `null` values).
For debugging, there are two different assert levels available: `Warning` (only shows a message but doesn't throw an exception) and `Error` (throws an exception). …
> Add assert() macro

- Shaders/bloom_pass/bloom_pass.frag.glsl
- Shaders/bloom_pass/bloom_pass.json
- Shaders/blur_gaus_pass/blur_gaus_pass.frag.glsl
- Shaders/blur_gaus_pass/blur_gaus_pass.json
- Shaders/chromatic_aberration_pass/chromatic_aberration_pass.frag.glsl
- Shaders/chromatic_aberration_pass/chromatic_aberration_pass.json
- Shaders/ssao_pass/ssao_pass.frag.glsl
- Shaders/ssao_pass/ssao_pass.json
- Shaders/ssr_pass/ssr_pass.frag.glsl
- Shaders/ssr_pass/ssr_pass.json
Potential fix for https://github.com/armory3d/armory/issues/2314.
When `Realtime postprocess` was turned off, some unused uniforms were removed by the compiler but were still referenced from Iron. This led to warnings and maybe even to the blackscreen reported in the above issue. @onelsonic can you please check whether the blackscreen is fixed by this PR?
> Fix "Uniform PPCompXX not found" warnings

- Sources/armory/system/Assert.hx
Previously only string literals were allowed as optional messages in the new assert() macro. Now you can use variables and concatenated or interpolated strings in the last parameter (and probably everything that can be converted to string somehow). This is helpful if you want to have a message like `'No trait with the name "$name" found'`.
Thanks to @QuantumCoderQC for reporting this!
> Allow to use more complex string expressions as assert() messages

- blender/arm/lib/make_datas.py
- blender/arm/make.py
Fixes https://github.com/armory3d/armory/issues/2323. This issue happened because `PPCompXX` uniforms were used in shaders which were not part of the compositor pass, however they were only correctly considered in that pass. Because the uniforms don't interfere with any non-compositor uniforms, it is safe to simply allow them for non-compositor shader passes.
I also cleaned up make_datas.py a bit, the changes are mostly semi-automatic IDE stuff, some type hints and comments and two big duplicate code blocks were moved into a function.
> Fix realtime postprocess & cleanup arm.lib.make_datas

- Sources/armory/system/Assert.hx
Fix  using `assert` without proper import.
```
Unknown identifier : throwAssertionError
```
This happens if the Assert methods aren't properly imported, like when:
```haxe
import armory.system.Assert.assert;
```
instead of
```haxe
import armory.system.Assert.*;
```
> Fix assert throw error

- blender/arm/exporter.py
Fixes https://github.com/armory3d/armory/issues/2327. Because `SceneFormat.TTrait` attributes like the trait type or custom properties are only important for traits that start activated, it seems sufficient to simply include their classes in the generated output.
> Fix fake user export for traits

- blender/arm/write_data.py
How about removing this flag per default ?
There isn't that much useful information in there and one could add it manually to the khafile.js if necessary.
> Remove haxe --times param per default

- blender/arm/assets.py
- blender/arm/keymap.py
- blender/arm/props_ui.py
- blender/arm/write_probes.py
Removes the `Armory Warning:` prefix in log messages as `arm.log.warn` already prefixes it with `WARNING:`
> Improve log messages

- Sources/armory/logicnode/GetGlobalCanvasScaleNode.hx
- Sources/armory/logicnode/SetGlobalCanvasScaleNode.hx
- Sources/armory/trait/internal/CanvasScript.hx
- blender/arm/logicnode/canvas/LN_get_global_canvas_scale.py
- blender/arm/logicnode/canvas/LN_set_global_canvas_scale.py
This PR adds two new nodes that allow to get/set the scale of the entire canvas, not just of individual elements.
> Add nodes to get/set global canvas scale

- blender/arm/logicnode/__init__.py
When reloading the add-on via the reload operator, all node modules were reimported even if they were new and not imported before which led to an exception.
> Fix add-on reloading when there are new unimported node files

- Sources/armory/trait/internal/DebugConsole.hx
- blender/arm/exporter.py
- blender/arm/props.py
- blender/arm/props_ui.py
Closes https://github.com/armory3d/armory/issues/2190.
- There is now an option in both the Blender UI and the debug console UI to omit the position infos from trace statements, the actual Haxe console output is not affected by that.
- There is now less space between the individual log lines in the UI:
- Added some tooltips to the debug console
> Debug console: make log output more readable

- blender/arm/utils.py
- blender/arm/write_probes.py
Fixes https://github.com/armory3d/armory/issues/2344.
The CMFT sources state the following about the `--numCpuProcessing` parameter:
> Should not be bigger than the number of physical CPU cores/threads.
Both `multiprocessing.cpu_count()` and `os.cpu_count()` return the number of logical CPU cores, which can be larger than the number of physical ones. Because the Python standard library doesn't provide a function for this, we need our own function that relies on some shell commands. In theory the Linux command can be executed without `shell=True` if you correctly pipe together the individual programs used in the command ([like this](https://docs.python.org/3/library/subprocess.html#replacing-shell-pipeline)), but my Ubuntu VM lags as hell and I didn't get it to work that way.
Tested on …
> Fix CPU count parameter for cmft

- blender/arm/logicnode/arm_nodes.py
- blender/arm/logicnode/deprecated/LN_quaternion.py
- blender/arm/logicnode/deprecated/LN_separate_quaternion.py
- blender/arm/logicnode/deprecated/LN_surface_coords.py
There were some deprecated nodes with incorrect categories that led to an empty "Deprecated" menu entry in the add node menu. Deprecated nodes instead have to keep their original category in order to show up in the right category in the wiki, so I also added an assertion to check for this problem.
> Fix deprecated nodes and improve deprecation handling

- blender/arm/make_world.py
- blender/arm/material/cycles_nodes/nodes_input.py
- blender/arm/material/cycles_nodes/nodes_texture.py
Requires https://github.com/armory3d/iron/pull/140.
The world normals in Armory were the opposite of how Blender works (which is actually the correct way), the zenith had normals (0, 0, 1) which rather is the _position_ of the zenith but _not its normal vector_ (0, 0, -1). This resulted in worlds looking different than in Blender if the Geometry node was used. Now there is a differentiation between normals and position and all usages should be updated accordingly. Tested it with both sky types, clouds, environment maps and all outputs of the Texture Coordinate and Geometry nodes.
Also fixed in the Geometry node:
- `Tangent`, `Incoming` and `Backfacing` outputs in world shaders
- Added fake support for the new `Random Per Island` output (Cycles only, so it just returns 0.0 like in Eevee) …
> Fix Geometry and Texture Coordinate nodes for world shaders

- Sources/armory/trait/internal/UniformsManager.hx
Removes unnecessary block in switch expression.
This caused some strange behaviour when using the method.
> Fix switch expression

- blender/arm/material/cycles.py
- blender/arm/utils.py
Fixes an issue that could happen if a material from a linked library used a texture with a path relative to the library. In this case the relative path would be copied to the khafile and Iron would then try to load a nonexisting texture.
@luboslenco Currently `krom_load_image()` will return `null` when an image doesn't exist which will result in a Kha image object which neither has a `texture_` nor a `renderTarget_` set. Because of that, Amorcore will crash as soon as Iron tries to generate mipmaps for the image. Should there be handling for this in the mipmap generating function? Should `krom_load_image()` instead trigger a failure callback so that those failures can be more easily handled in Iron? I'm not sure what the "design philosophy" of Armorcore or Iron is in this case.
> Fix exporting textures from linked libraries

- blender/arm/utils.py
Fixes https://github.com/armory3d/armory/issues/2344#issuecomment-962416069.
Even though `C:\Windows\System32` should be part of the PATH environment variable by default ([source](https://ss64.com/nt/syntax-variables.html)), there might be cases where this entry is missing and `utils.cpu_count()` could fail because `wmic.exe` could not be found.
This PR also improves the error handling in that function by also using the logical CPU count as a last resort for FileNotFoundErrors and by showing some information about what went wrong.
> Fix cpu_count() for incomplete PATH var on Windows and improve error handling

- blender/arm/node_utils.py
Fixes #2380 
From https://docs.python.org/3.9/library/collections.html:
> Deprecated since version 3.3, will be removed in version 3.10: Moved Collections Abstract Base Classes to the collections.abc module. For backwards compatibility, they continue to be visible in this module through Python 3.9.
> Correct depricated (and now removed) import

- Sources/armory/object/TransformExtension.hx
The right, look and up vectors were not normalized. This PR fixes that by normalizing the orientation vectors before multiplying world vectors
> fix TransformExtension - Normalize vectors

- blender/arm/make_world.py
- blender/arm/material/cycles_nodes/nodes_texture.py
- blender/arm/write_probes.py
- This PR tries to fix the overly strong irradiance brightness that was introduced by using a world render as the input to cmft. The biggest problem was that the environment render wasn't properly gamma corrected/in the wrong color space and thus too bright.
Unfortunately there are still some visible differences to Blender depending on the situation, even though they are much less extreme now. Apparently cmft's calculations differ from Blender's calculations, when comparing the output of cmft for a given (color-correct) render of a plain color in [this SH viewer](https://ed.ilogues.com/2016/02/19/interactive-spherical-harmonic-visualization) with Blender there are still slight differences (without any tonemapping/color grading active).
For more details please see …
> Fix environment gamma and improve handling of envmap file formats

- blender/arm/logicnode/arm_props.py
- blender/arm/node_utils.py
Bool, Int and Float Vector properties were not parsed properly for Haxe. This PR fixes this.
Thanks to @MoritzBrueckner for help.
> Fix Bool, Int and Float vector property export from logic nodes

- blender/arm/material/parser_state.py
Fixes https://github.com/armory3d/armory/issues/2301. The `ParserContext` enum was redefined during reload which is no longer the case, and to make things extra-safe the enum is now an `IntEnum` which makes the values comparable.
> Fix parser context references after reload and make enum values unique

- blender/arm/make.py
- blender/arm/props.py
- blender/arm/props_ui.py
- blender/arm/write_data.py
This PR adds a new option to toggle off `trace()` calls in published builds via the `--no-traces` parameter (https://haxe.org/manual/compiler-usage.html#other-global-arguments).
> Add option to enable Haxe's --no-traces param

- Sources/armory/logicnode/CompareNode.hx
Fixes https://forums.armory3d.org/t/removing-object-causes-game-to-freeze-only-after-exporting/4742.
Because the objects that are compared by the compare node are typed as `Dynamic`, DCE seems to have some problems and accidentally removes some used vector functions. To not clutter Iron code with `@:keep` metadata that makes it difficult to see why it was used in the first place, I decided to use the [type check syntax](https://haxe.org/manual/expression-type-check.html) instead to take away some work from the compiler.
> Compare node: fix accessing vector methods when DCE is on

- Sources/armory/logicnode/CallGroupNode.hx
- Sources/armory/logicnode/GroupInputNode.hx
- Sources/armory/logicnode/GroupInputsNode.hx
- Sources/armory/logicnode/GroupOutputNode.hx
- Sources/armory/logicnode/GroupOutputsNode.hx
- blender/arm/logicnode/arm_sockets.py
- blender/arm/logicnode/deprecated/LN_group_nodes.py
- blender/arm/logicnode/miscellaneous/LN_call_group.py
- blender/arm/logicnode/miscellaneous/LN_group_input.py
- blender/arm/logicnode/miscellaneous/LN_group_output.py
- blender/arm/make_logic.py
This PR introduces `Node Groups` in Armory. `Node Trees` can be used as `Node Groups` to reduce the repetitive usage of logic nodes and make the tree more elegant.
Partially solves https://github.com/armory3d/armory/issues/723.
An example:
Thanks to @knowledgenude and @MoritzBrueckner for their insights on this and @t3du for testing this feature. 
More documentation on this feature:
https://github.com/QuantumCoderQC/armory/wiki#node-groups
> Introducing Node Groups

- blender/arm/logicnode/__init__.py
- blender/arm/logicnode/physics/LN_add_physics_constraint.py
- blender/arm/logicnode/physics/LN_physics_constraint.py
- blender/arm/nodes_logic.py
- External node libraries can now use Armory's `init_nodes()` function that registers all nodes inside of a given package (recursively)
- If node categories had special characters in their name (e.g. spaces), the menu class name and bl_idname would also contain those characters which would lead to warnings (interestingly, there was no _error_ when using spaces before, just a warning...?)
- Also fixed a small typo that is unrelated to this PR, but I didn't want to annoy you with a separate PR for this. @luboslenco it seems that I have write access to this repo, I guess it's ok for you if I would commit such trivial typo fixes directly to master? For everything else I will of course open a PR, but I think stuff like this is just unnecessary work for you.
> Improve node library handling

- Sources/armory/logicnode/OnCanvasElementNode.hx
this node wasnt working as expected if the canvas was scaled with the set canvas global scale factor... the values considered the initial canvas values defined in the json file instead of the actual ones modified by scale.
> OnCanvasElementNode: fix elements values for scaled canvas

- Sources/armory/logicnode/SetRotationNode.hx
Fixes https://github.com/armory3d/armory/issues/2413.
`Quat` is a mutable type and because the SetRotationNode didn't clone the inputted quaternion, all previous usages of that quaternion were also changed and even if only one object would be used for this node, the inputted quaternion might be used in other places where it would also be changed by this node.
In order to prevent an allocation on the heap, the rotation quat of an object is no longer exchanged, only its values are updated instead (`setFrom()`). Then the cloned quaternion can be inlined by Haxe.
> Fix SetRotationNode: don't change rotation of previous objects

- Sources/armory/logicnode/FloatDeltaInterpolateNode.hx
- Sources/armory/logicnode/RetainValueNode.hx
- blender/arm/logicnode/math/LN_float_delta_interpolate.py
- blender/arm/logicnode/variable/LN_retain_value.py
This PR introduces two new nodes. The `Retain Value Node` and `Float Delta Interpolation Node`
The `Retain Value Node` may be used to retain some value and reduce repetitive computations.
`Float Delta Interpolation Node` may be used to interpolate between `from` and `to` values linearly with a certain `rate`. The `Delta Time` input takes the system delta time to account for varying frame rates.
> Retain Value Node, Float Delta Interpolation Node

- Sources/armory/logicnode/GetGamepadStartedNode.hx
this node is not working because gamepad is input 1 not 0, so it gets a null value and fails
> Get Gamepad Started - fix node input

- blender/arm/material/mat_utils.py
This fixes a bug from https://forums.armory3d.org/t/colors-in-blender-and-armory3d-do-sometimes-not-match/4805.
The previous code of `is_transluc_type()` accidentally enabled translucency if the "Emission Strength" input of the principled BSDF node was != 1 (because the compatibility check with `len(node.inputs) > 20` is also true for the current principled bsdf nodes).
Because this function might get overlooked when changing socket indices, I replaced the int indices with string indices. I'm still not sure what is used internally for lookup (see [this comment](https://devtalk.blender.org/t/implement-new-node-parameters-without-breaking-existing-scripts/15433/6) from brecht that leaves room for interpretation), but here it should be safer to do so despite possibly being a little slower.
> Fix is_transluc_type(): do not activate translucency with Principled BSDF emission strength

- Sources/armory/logicnode/GamepadSticksNode.hx
- blender/arm/logicnode/input/LN_gamepad_sticks.py
added functionality for retrieving the states, sticks and axis of a gamepad
i did the states logic the best i could maybe that could be improved
i added both sticks to the logic which is basically the same, i tested all the cases only for the leftstick because kha doesnt seem to be retrieving the right stick from my control even though the control is sending the signal
> add Gamepad Sticks node

- Sources/armory/logicnode/ArraySampleNode.hx
- Sources/armory/logicnode/ArrayShuffleNode.hx
- blender/arm/logicnode/array/LN_array_sample.py
- blender/arm/logicnode/array/LN_array_shuffle.py
Added two new nodes for array handling which i have been using:
-> Shuffle items from an array to create random order of items
-> Sample n items from an array with the option to remove those items from original array to create a new array of n random items
> Array - ArraySampleNode and ArrayShuffleNode

- blender/arm/logicnode/logic/LN_merge.py
- blender/arm/logicnode/logic/LN_select.py
- blender/arm/logicnode/native/LN_read_file.py
- blender/arm/logicnode/native/LN_read_json.py
- blender/arm/logicnode/native/LN_read_storage.py
- blender/arm/logicnode/native/LN_write_file.py
- blender/arm/logicnode/native/LN_write_json.py
- blender/arm/logicnode/native/LN_write_storage.py
Implements the documentation part of https://github.com/armory3d/armory/issues/2070 and requires https://github.com/armory3d/armory_tools/pull/12 for proper layout in the GitHub wiki.
For the Write Storage node I had to look up some of the save file paths in the Kinc sources because I can't test all targets. This however means that some of the paths might not be correct or formatted in a wrong way that isn't used on that particular platform. So if someone sees a mistake, please let me know :) Also, I know that the paths are internal Kha stuff that may change any time, but as Kha's documentation is rather non-existent or extremely well hidden I think it is good to write it down somewhere as it might be of interest for developers.
> Add detailed documentation for read/write json/file/storage nodes

- blender/arm/make_renderpath.py
This prevents the [usual krafix/directx issue](https://github.com/armory3d/armory/issues/1772) in case multiple lights exist in the scene but only one is used for rendering in game (e.g. because the other lights are used for light mapping only).
> Don't count not exported lights when setting shader defines

- Sources/armory/logicnode/BitwiseMathNode.hx
- blender/arm/logicnode/math/LN_bitwise_math.py
This new node allows to perform bitwise math on integers, which can be helpful when working with masks for example.
> Add bitwise math node

- blender/arm/handlers.py
- blender/arm/logicnode/__init__.py
- blender/arm/logicnode/arm_nodes.py
- blender/arm/logicnode/array/LN_array.py
- blender/arm/logicnode/array/LN_array_boolean.py
- blender/arm/logicnode/array/LN_array_color.py
- blender/arm/logicnode/array/LN_array_float.py
- blender/arm/logicnode/array/LN_array_integer.py
- blender/arm/logicnode/array/LN_array_object.py
- blender/arm/logicnode/array/LN_array_string.py
- blender/arm/logicnode/array/LN_array_vector.py
- blender/arm/logicnode/material/LN_material.py
- blender/arm/logicnode/object/LN_object.py
- blender/arm/logicnode/replacement.py
- blender/arm/logicnode/string/LN_string.py
- blender/arm/logicnode/trait/LN_trait.py
- blender/arm/logicnode/tree_variables.py
- blender/arm/logicnode/variable/LN_boolean.py
- blender/arm/logicnode/variable/LN_color.py
- blender/arm/logicnode/variable/LN_dynamic.py
- blender/arm/logicnode/variable/LN_float.py
- blender/arm/logicnode/variable/LN_integer.py
- blender/arm/logicnode/variable/LN_mask.py
- blender/arm/logicnode/variable/LN_rotation.py
- blender/arm/logicnode/variable/LN_transform.py
- blender/arm/logicnode/variable/LN_vector.py
- blender/arm/node_utils.py
- blender/arm/nodes_logic.py
- blender/arm/props.py
- blender/arm/utils.py
Fixes https://github.com/armory3d/armory/issues/2434.
What started as an attempt to fix a simple issue became an almost complete rewrite of the logic ID system. Previously it was easily possible to create a few different situations where the correctness of the exported logic tree was completely violated or at least depending on external things such as iteration orders when exporting nodes:
- if multiple variable nodes shared the same values, only one random node was exported, so the initial value was undefined if the nodes had different values.
- it was possible to use the same logic ID for nodes with different types. Because all linked nodes were replaced with the exported node of another type, this could lead to runtime exceptions/type errors in other places of the tree.
- the above …
> New logic tree variable system

- Shaders/deferred_light/deferred_light.frag.glsl
- Shaders/deferred_light/deferred_light.json
- Shaders/deferred_light_mobile/deferred_light.frag.glsl
- Shaders/deferred_light_mobile/deferred_light_mobile.json
- Shaders/std/light.glsl
- Shaders/std/light_common.glsl
- Shaders/std/light_mobile.glsl
- Shaders/volumetric_light/volumetric_light.frag.glsl
- Shaders/volumetric_light/volumetric_light.json
- blender/arm/material/make_cluster.py
- blender/arm/material/make_mesh.py
Fixes https://github.com/armory3d/armory/issues/2145 and requires https://github.com/armory3d/iron/pull/155.
Previously the code expected spotlights to be scaled to 1,1,1 and if this wasn't the case, it could happen that spot lights weren't rendered (because each fragment was treated as being outside of the light cone).
Now Armory supports arbitrary spotlight scales, so it is now possible for example to create an elliptic spotlight by scaling it on one axis. The output shape is exactly the same as in Eevee. Unfortunately we need slightly more data on the GPU now (up to 4 more floats per spotlight depending on the shader), but I think that's acceptable.
I put the spotlight glsl code in a new module because it is also used in mobile deferred where including light.glsl would lead to a …
> Full support for arbitrary spotlight scales

- blender/arm/utils.py
Armory still had some legacy code to support bundled SDKs (no longer a thing), whose SDK counterpart was removed in https://github.com/armory3d/armsdk/commit/446fb39a43fa75d10817ccc37814511615713dbc. If the SDK was at the same location as the bundled SDK would have been in the past, there would be an exception because of a referenced variable that was removed in the commit linked above.
Thanks to RPaladin for the report :)
> Remove legacy code from utils.py and fix possible installation error

- Shaders/volumetric_light/volumetric_light.frag.glsl
Fixes the first error mentioned in https://github.com/armory3d/armory/issues/1480, the other two errors seem to have been fixed already by https://github.com/armory3d/armory/pull/1945. I'm assuming the shader compiler is clever enough to remove unused variables in case neither `_Sun` nor `_SinglePoint` are defined :)
---
@luboslenco out of interest (because I'm trying to fix another lighting issue), what is the reason for supporting `ifdef` and `ifndef` for links in the accompanying .json files for shaders when the links are only resolved when the uniform is used in the shaders anyway (see [blender/arm/lib/make_datas.py](https://github.com/armory3d/armory/blob/fe19efe56a3831df43a9392d9c301c6ef8dc60ae/blender/arm/lib/make_datas.py#L82))? It looks like the links are checked twice this way, …
> Fix redefinition in volumetric light shader when using both sun and single spot light

- blender/arm/exporter.py
- blender/arm/material/make.py
- blender/arm/node_utils.py
- blender/arm/write_data.py
- The "Auto" option for SSS could lead to a missing `sssWidth` variable in the shader which is one of the issue mentioned here: https://github.com/armory3d/armory/issues/2136
- If multiple SSS nodes were present in a material but the first to be parsed was not used, the shader didn't use SSS. It's still far away from Blender's subsurface scattering, but it's a bit more reliable now.
- When compiling with SSS disabled and then setting it to "Auto" without clearing the cache, it could happen that the generated materials didn't activate SSS because the `_SSS` flag wasn't set. I'm not completely happy with the solution, but I'm not yet confident enough with the material exporter code to be able to refactor the code in a way that prevents the dependency/order issues that can happen. It might …
> Various export fixes for subsurface scattering

- blender/arm/material/cycles.py
Fixes a shader compilation error due to incompatible variable types that could occur when activating box mapping in a texture node.
> Fix compiling texture node with triplanar (box) mapping

- blender/arm/logicnode/arm_nodes.py
- blender/arm/logicnode/arm_sockets.py
- blender/arm/logicnode/miscellaneous/LN_call_group.py
- blender/arm/logicnode/miscellaneous/LN_group_input.py
- blender/arm/logicnode/miscellaneous/LN_group_output.py
- blender/arm/node_utils.py
I guess it's explained best with some gifs:
- ArmAnySocket sockets now follow reroutes and correctly display the name and color of the actually connected socket:
- CallNodeGroup nodes are now updated when a node group changes its inputs or outputs (also following reroutes now):
> Follow reroutes for group nodes and update call group node upon changes

- blender/arm/logicnode/variable/LN_retain_value.py
The output socket order was different for Python and Haxe, so the retain node accidentally activated other nodes with its "Value" output.
> Fix socket order for Retain Value node

- blender/arm/material/cycles.py
There was some leftover code in the texture export that, according to a comment, led to Blender loading the textures into memory even though its no longer used. After removing the code, I got from 2.6s to 0.2s overall spent in `make_texture()` in a file with 15 textures on my machine.
> Remove unused code that substantially slowed down texture export

- blender/arm/logicnode/arm_nodes.py
- blender/arm/logicnode/tree_variables.py
Fixed an exception that could occur when using the operator search (F3) outside the logic node editor.
> Fix polling of tree variable operators outside of logic trees

- Sources/armory/logicnode/ValueChangedNode.hx
- blender/arm/logicnode/logic/LN_value_changed.py
Previously the "Unchanged" output of the Value Changed node was not activated if the value was unchanged _compared to the last value_, but only if it was different to the _initial value_ from the first execution of the node. The "Changed" output however compared the last value.
This led to some confusion, so there is now a new output "Is Initial" for the old functionality, and "Unchanged" now checks against the last value as well. It's also possible now to use `null` as a value without always triggering the initialization of the node.
> Improve output socket handling of the Value Changed node

- Sources/armory/trait/internal/Bridge.hx
- blender/arm/live_patch.py
I'm not quite sure why it worked before in some cases (js...), but setting quaternion values as simple float arrays sometimes led to NaN values which then caused havoc later.
Thanks @rpaladin for the report!
> Fix updating rotation sockets during live patch session

- Sources/armory/logicnode/OnEventNode.hx
- blender/arm/logicnode/event/LN_on_event.py
Upgrade for the `OnEvent` node as suggested in #1134.
* `Init` type
* `Update` type
* `Custom` type
<https://github.com/rpaladin/A3D-LN-Reviews/blob/main/A3D_LN_On_Event.blend>
I would like to especially thank @MoritzBrueckner & @QuantumCoderQC for their time, advice, help & review!
> Upgrade OnEvent node

- Sources/armory/system/Starter.hx
Fixes a "haxe is not defined" error message that could happen if ammo.js tries to print a WASM error message.
Due to its interaction with Haxe the now fixed error had the nice side-effect of printing a stack trace that pointed to the location where the actual WASM error happened, but unfortunately that is gone now (at least in my specific case). If anyone knows how to get WASM to print stack traces please let me know :)
> Fix printing WASM errors when using ammo.js

- blender/arm/lib/server.py
- blender/arm/make.py
Use web server port number specified in preferences, not hard coded.
Also removes dependency of arm.lib.server outside its' package.
> Use port from prefs for html5 player path

- Sources/armory/renderpath/RenderPathCreator.hx
- Sources/armory/renderpath/RenderPathDeferred.hx
- Sources/armory/renderpath/RenderPathForward.hx
- blender/arm/exporter.py
- blender/arm/make_renderpath.py
- blender/arm/material/make.py
- blender/arm/material/make_mesh.py
- blender/arm/props.py
- blender/arm/props_renderpath.py
- blender/arm/props_ui.py
Requries https://github.com/armory3d/iron/pull/160.
This PR implements what was discussed in https://github.com/armory3d/armory/pull/1817. Materials now can specify that they want to read from the depth buffer. In this case, meshes with those materials are drawn last and before they are drawn, the depth buffer is copied to a dedicated depth texture that can then be sampled from a shader uniform called `depthtex`.
It works on deferred and forward (Depth prepass on/off), with shadows and transparency, SSR and mesh batching. The only limitation I know is that on forward RP this doesn't work when the compositor is turned off because then the `rp_render_to_texture` define is undefined and `lbuffer0` does not exist. I'm not sure whether this define should only be set for the compositor (as it …
> Allow materials to read from a depth texture

- Sources/armory/logicnode/KeyInterpolateNode.hx
- blender/arm/logicnode/math/LN_key_interpolate.py
This node allows to linearly interpolate between `0` and `1` based on a condition, For example keyboard/ mouse key down. It can be used to smooth character movement/translations that are activated on key down.
> key Interpolation Node

- blender/arm/write_data.py
Unnecessary, 0px margin is already set inline for body element.
> Remove head style element

- blender/arm/material/cycles.py
- blender/arm/material/cycles_nodes/nodes_texture.py
- blender/arm/material/make.py
- blender/arm/props_ui.py
Custom materials can now sample from textures that have been loaded in Blender ("mesh" context only for now). If the user has selected a custom material, the following panel appears:
The selected images then get an entry in the scene's material data for binding them to a texture unit, but the user still has to add the actual texture unit in the material's .json file. Apart from checking whether the uniform name is not empty and there is an image selected, there are for now no additional checks if the uniform name is actually allowed.
> Support for texture bindings for custom (json) materials

- blender/arm/make_logic.py
Fixes an error mentioned in https://github.com/armory3d/armory/issues/2487#issuecomment-1120386019 that was caused by an oversight in https://github.com/armory3d/armory/pull/2480.
> Fix exporting node sockets when using live patch or unconnected reroutes

- blender/arm/make_world.py
- blender/arm/material/cycles.py
- blender/arm/material/parser_state.py
Closes https://github.com/armory3d/armory/issues/2490.
Now the socket parsing functions are only called if the link's socket types are supported, otherwise a warning is printed and a default value is used. This prevents either "unsupported node" warnings as in the linked issue or in some cases even glsl errors.
> Better shader node tree warnings

- blender/arm/api.py
- blender/arm/handlers.py
Fixes an issue described in https://forums.armory3d.org/t/celshade-option-only-appears-after-opening-forest-example-with-right-click-how-to-set-manually-for-other-blends/4891.
Libraries weren't reloaded when changing files from within the same project, but registered render path drivers are removed each time a file is changed. Now libraries are reloaded each time a file is opened or the addon is reloaded, which also gives libraries the possibility to re-initialize themselves for a new file. Also, libraries can now have an optional `unregister` function that will be called before a new file is loaded or when the addon is unregistered, giving libraries the possibility to properly clean up.
Furthermore libraries are no longer loaded twice when a blend file is opened from the file explorer …
> Fix and improve loading of libraries

- blender/arm/material/cycles.py
Fixes https://github.com/armory3d/armory/issues/2467.
To convert RGB values to grayscale, Armory used different luma coefficients than Blender which could lead to visible differences between Armory and Blender materials. I wasn't exactly sure where the values come from, so I did some research:
- Previously, Armory used approximations of values from Rec. 601 (Rec. ITU-R BT.601-7 Section 2.5.1). Similar values (but not the same) were used in older Blender versions (see [this commit](https://github.com/blender/blender/commit/49247f0fc445ec014478d485883492a04ae5facb#diff-577a4d894f44ce57f77a4988305f510e77a95edee5b044c3802a4a9e953cf559L746)).
- Blender uses the [default coefficients from OpenColorIO](https://opencolorio.readthedocs.io/en/latest/guides/authoring/authoring.html#luma) (see …
> Align RGB to grayscale luminance with Blender

- blender/arm/material/cycles_nodes/nodes_converter.py
Fixes another issue mentioned in https://github.com/armory3d/armory/issues/2467 (see https://forums.armory3d.org/t/textured-terrain-rgb-channel-flipped/4850).
In the color ramp node it could happen that the input factor was left of the left-most stop and thus the relative position between two stops was negative. As a consequence the output of `mix(stopLeft, stopRight, relativePos)` was wrong. Because there is always an implicit stop at position 1.0, the same issue doesn't happen for the opposite case of values right to the right-most stop.
I also made the code a bit more readable to better describe what it does.
> Fix color ramp node for factors left of the left-most stop

- Sources/armory/trait/FirstPersonController.hx
The first controller node allows player to walk faster when using a combination of two keys,
because vectors are added as is without modifications ; I changed the code to get the correct speed. Also sped up the movement overall.
> FirstPersonController.hx anti chess fool cheat.

- Sources/armory/logicnode/RotationNode.hx
Fixes https://github.com/armory3d/armory/issues/2506.
The rotation node counted its input sockets in the constructor, so the count was always 0 because no sockets existed yet.
> Fix RotationNode.set(): get rid of invalid input length check

- Sources/armory/trait/NavAgent.hx
When NavAgent Object was removed, the tweening still continued, resulting in an error. This PR fixes this issue.
> Stop tweening when NavAgent is removed

- blender/arm/exporter.py
- blender/arm/props.py
- blender/arm/props_ui.py
This PR introduces a new option for the armatures called `Relative Bone Constraints`. 
When enabled, the constraints refer to the target objects from within the Armature's parent. 
This solves an issue when multiple Armatures are spawned but all the armatures always follow the initial constraint targets rather than the newly spawned.
Thanks to @1k8 on Discord for bringing up this issue.
Requires https://github.com/armory3d/iron/pull/166
> Add parent relative bone constraint option

- Sources/armory/renderpath/RenderPathDeferred.hx
Fixes an issue described in https://github.com/armory3d/armory/issues/2520 that would draw translucent materials on top of the volumetric light when using the deferred renderpath.
Previously the render order on deferred was `Volumetric Light -> World -> Translucenct Materials`, now it is `World -> Translucent Materials -> Volumetric Light`. As a side effect, the world shader is now also subject to light scattering, but god rays still work exactly as before. We discussed this a little on the Discord server and came to the conclusion that this change is acceptable and more correct.
I wasn't sure whether it is required to unbind depth for the volumetric lighting like it was done before, but it isn't done in the forward render path and it worked without issues on Krom (DirectX), html5 and HL …
> Deferred renderpath: fix volumetric light combined with translucent materials

- blender/arm/logicnode/arm_nodes.py
- blender/arm/logicnode/tree_variables.py
- blender/arm/make_logic.py
- blender/arm/props.py
Fixes https://github.com/armory3d/armory/issues/2504.
Adding getters/setters for tree variables did not synchronize the variable values from the master node to all replica nodes, and because only the first logic node for a given variable is exported in place for all other nodes of the same variable, there was a race condition depending on which node was exported first. Files saved before the next SDK 22.09 will be automatically fixed upon loading.
> Tree variables: fix missing synchronization when adding getters/setters

- blender/arm/handlers.py
- blender/arm/logicnode/arm_nodes.py
- blender/arm/logicnode/math/LN_tween_float.py
- blender/arm/logicnode/math/LN_tween_rotation.py
- blender/arm/logicnode/math/LN_tween_transform.py
- blender/arm/logicnode/math/LN_tween_vector.py
- blender/arm/logicnode/miscellaneous/LN_group_input.py
- blender/arm/logicnode/miscellaneous/LN_group_output.py
- blender/arm/props.py
- blender/arm/props_ui.py
This PR fixes two related issues:
1. The tween and group input/output nodes weren't correctly initialized, so their version number was set to 0 and always caused a node replacement that would fail with an exception because no replacement routine exists for those nodes. Instead of using `arm_init()`, the nodes were using `init()` which would override Blender's initialization callback that we use to initialize the version number.
To make the error less silent, I marked `init` as `@final` although this is just a hint for mypy and not enforced at runtime. A good IDE with mypy support will show this however. It may be even better to make `ArmLogicTreeNode` abstract and require overriding `arm_init`, but this doesn't work because Blender will fail with an error due to the way its Python API …
> Fix initialization of tween and group nodes and ensure correct file version numbers

- Sources/armory/logicnode/SleepNode.hx
When a trait containing sleep node is removed, the seep timer still continued even after the trait removal, causing errors.
Thanks to @ wuaieyo on Discord for pointing it out.
> Fix sleep node

- Sources/armory/logicnode/SetSceneNode.hx
The `Set Scene Active` node wouldn't take lz4 compressed scenes into account and cause a crash in published projects.
Thanks to 1k8 on Discord for reporting this!
> Fix "Set Scene Active" node when using asset compression

- Shaders/deferred_light/deferred_light.frag.glsl
- Shaders/deferred_light_mobile/deferred_light.frag.glsl
- Shaders/probe_cubemap/probe_cubemap.frag.glsl
- Shaders/probe_planar/probe_planar.frag.glsl
- Shaders/std/gbuffer.glsl
- Sources/armory/renderpath/RenderPathDeferred.hx
This PR fixes two related issues mentioned in https://forums.armory3d.org/t/personal-website-made-with-armory/4723/35:
1. The SSS pass tried to read from the depth buffer that was still bound to a different render target. I'm not exactly sure which change caused this issue to appear (according to the forum post it didn't happen last year), but it works now.
2. The implementation of `packFloatInt16` in gbuffer.glsl had some numerical robustness issues: a matid of 2 and a metallic value of 0.0 would result in a packed float value of 0.125, which then got unpacked into matid = 1 and metallic = 1.0 because both packed representations are very close to each other.
My new implementation does not have this issue since the encoded output is basically an integer stored in a float. Unfortunately we …
> Fix depth buffer access in SSS pass & fix numerical robustness of packFloatInt16()

- Sources/armory/logicnode/DrawStringNode.hx
- blender/arm/logicnode/renderpath/LN_draw_string.py
Fixes https://github.com/armory3d/armory/issues/2547.
Zui was disabled in the example file of the linked issue but the Draw String node tried to access it. With live patch enabled, all logic nodes are included in compilation so that they can be added at runtime.
> Fix compilation error in Draw String node when Zui is disabled

- blender/arm/material/cycles.py
When the image texture node had `Armory Parameter` enabled, the material context constants overrides the textures set by the logic. So the texture could never be changed. This PR fixes this issue by not binding texture constants to materials if `is_arm_mat_param` is enabled.
Thanks to @ MoritzBrueckner for their help.
> Fix image texture parameters

- blender/arm/exporter.py
Fixes https://github.com/armory3d/armory/issues/2556.
When particle systems referenced objects from other scenes that weren't part of any collection (apart from the scene collection itself) there would be an exception because those objects would not be exported yet. Now they are lazily exported in this case. 
Objects inside of collections are always exported for all scenes (I suppose it's done so that all collections can be added at rutime), but there is potential for improvement here since currently a lot of exported data is redundant.
> Fix export of particle objects outside of the current scene and other collections

- blender/arm/exporter_opt.py
- blender/arm/material/make_morph_target.py
When `optimize data` was enabled in export settings, shape key data was not parsed. This PR adds shape key parsing in optimized mesh export.
This PR also fixes a minor issue with shader attribute not initialized properly, which lead to flickering of objects when shape keys were enabled. Thanks to @ wuaieyo on discord for bringing up this issue
> Fix shape key export in optimized mesh export

- Sources/armory/logicnode/AddRigidBodyNode.hx
- Sources/armory/trait/physics/bullet/RigidBody.hx
- blender/arm/exporter.py
- blender/arm/logicnode/physics/LN_Add_rigid_body.py
- blender/arm/props.py
- blender/arm/props_ui.py
- blender/arm/utils.py
This PR fixes an issue with rolling friction in Rigid Bodies. Requires https://github.com/armory3d/iron/pull/170
To fix the issue #831, angular damping was used instead of angular friction. But this caused additional issues with rolling objects such as spheres and cylinders. The actual issue was that linear friction setting was also used for angular friction, since there was no option in Blender rigid body settings. This PR adds a field for angular friction setting in the Rigid Body settings and uses it instead.
Additionally, the Rigid Body trait parameters is also changed form `Array<Float>` and `Array<Bool>` to `typedef` as this offers more information about the values.
> Fix rigid body angular/ rolling friction

- Sources/armory/logicnode/SetParentNode.hx
- blender/arm/logicnode/object/LN_set_object_parent.py
Fixes #2580
The set parent node used to treat empty parent socket as an option to un-parent objects. This interfered with the working of the socket. This PR fixes it by treating empty socket as `self-object` (as is by default). To unparent, simply use `get scene root` node at the parent socket.
Also added some documentation for the node.
Some more pertinent references if required:
https://github.com/armory3d/armory/issues/356
https://github.com/armory3d/armory/issues/310
> Fix set parent node

- blender/arm/material/cycles.py
- blender/arm/material/cycles_nodes/nodes_converter.py
This fixes the first issue in https://github.com/armory3d/armory/issues/2578.
- Blender introduced new Separate/Combine Color nodes but it isn't mentioned in the release notes, so unfortunately we missed it in the last SDK release.
Since I couldn't find a GPU-optimized implementation of a RGB->HSL routine (and vice versa) that we can use licence-wise and I haven't had time so far to really understand HSL, I didn't add support for the new HSL mode and instead added a warning. This is something to implement in the future.
I didn't remove support for the replaced Separate/Combine RGB/HSV nodes for now, since they still exist in the Blender API and I'm not sure whether they can still be used in some older files or manually via Python. 
- I also fixed a shader compilation error due to a …
> Fix support for Separate/Combine Color nodes

- blender/arm/handlers.py
- blender/arm/props_traits.py
Newer Blender versions no longer allow changing collection properties in draw() methods, this commit fixes an oversight from https://github.com/armory3d/armory/commit/04bd360cf6d8409926b7777a129ee2ad3c1b4008. When a blend file was opened after Armory was already registered, the now replaced code was called and caused an exception.
Thanks to Hreez on Discord for the report :)
> Fix exception when drawing the UI for bundled traits

- Sources/armory/logicnode/CanvasGetLocationNode.hx
- Sources/armory/logicnode/CanvasGetPBNode.hx
- Sources/armory/logicnode/CanvasGetRotationNode.hx
- Sources/armory/logicnode/CanvasGetScaleNode.hx
- Sources/armory/logicnode/CanvasSetAssetNode.hx
- Sources/armory/logicnode/CanvasSetCheckBoxNode.hx
- Sources/armory/logicnode/CanvasSetInputTextNode.hx
- Sources/armory/logicnode/CanvasSetLocationNode.hx
- Sources/armory/logicnode/CanvasSetPBNode.hx
- Sources/armory/logicnode/CanvasSetProgressBarColorNode.hx
- Sources/armory/logicnode/CanvasSetRotationNode.hx
- Sources/armory/logicnode/CanvasSetScaleNode.hx
- Sources/armory/logicnode/CanvasSetSliderNode.hx
- Sources/armory/logicnode/CanvasSetTextColorNode.hx
- Sources/armory/logicnode/CanvasSetTextNode.hx
- Sources/armory/logicnode/CanvasSetVisibleNode.hx
- Sources/armory/trait/internal/CanvasScript.hx
This PR changes `CanvasScript.notifyOnReady()` to allow registration of multiple callbacks instead of just one. Other trait callbacks (init, update, render, etc.) already allow multiple callbacks, so it only makes sense to make onReady work in the same way.
With that change it is also possible to remove a lot of redundancy from the canvas nodes. Some canvas nodes make use of a try/catch workaround for some issue that's unfortunately not further explained ([here for example](https://github.com/armory3d/armory/blob/fc3bdd8d23b8aa75c6e42424f8e8a7d84a0b012e/Sources/armory/logicnode/CanvasGetCheckboxNode.hx#L20-L21)), so in order to not break anything I left those nodes as they currently are and further tests are required here.
> Support multiple canvas onReady callbacks

- Sources/armory/trait/PhysicsBreak.hx
- Sources/armory/trait/physics/bullet/RigidBody.hx
The signature of the `RigidBody` constructor was changed, but PhysicsBreak.hx wasn't updated.
This also fixes the failed CI in https://github.com/armory3d/armsdk/pull/50.
> Fix compilation of PhysicsBreak.hx

- Sources/armory/ui/Canvas.hx
This PR fixes some theming related issues that would happen if `ui.t == getTheme(canvas.theme)`, which initially is true for canvases created with the CanvasScript trait. If there were elements with custom colors and others that follow theme colors, it would happen that the elements following the theme would inherit the custom color because the theme is never reset after drawing.
I considered many different solutions (macros, reflection, etc.) to have less redundant code, but in the end I think it makes more sense like it is done in this PR to keep the code more readable, it's not changed that often anyways.
Thanks to @Onek8 for the report!
> Canvas: fix theme issues when Zui theme == canvas theme

- Sources/armory/trait/internal/DebugConsole.hx
This PR fixes an issue that would prevent editing attributes like object transforms from the debug console. After pressing enter, the value would always reset to the value before editing because the changed value would not be written to the attribute.
Apparently `ui.changed` is no longer set to true when the value of a text input is changed (git bisect "blamed" https://github.com/armory3d/zui/commit/85eebc77ee8176ed4a7cce92a2f76f6fb43a10b8, I'm not sure if this particular change is intentional), so instead we need to use `handle.changed` which probably is better anyways.
Thanks to @ RPaladin for the report!
> Fix editing values in debug console

- blender/arm/make.py
Use `state.proc_play` instead of `webbrowser.open` to start the html5 player.  
This allows to stop the browser from withing blender (Stop button) and prevents opening multiple browser windows, like on krom.
Not sure why this wasn't the default behavior, but i can't see any drawbacks.
> Start browser using proc_play

- Sources/armory/trait/internal/DebugConsole.hx
The active camera is now highlighted in the outliner, making it easier to find:
Also, the "Set Active Camera" button is no longer visible for already active cameras.
---
@ luboslenco (or @ anyone who knows Zui better than me): is it possible to add scrollbars not only to windows, but to areas inside of windows? The outliner can get pretty long in complex scenes which then pushes the object properties out of view. Also, is there a way to check in Zui whether the mouse currently hovers some UI elements/windows? Currently, you can click "through" the debug console which in some cases is a bit annoying.
I would like to implement both these things, but my Zui knowledge is rusty and I can't seem to find a good solution.
> Debug Console: show active camera in outliner and hide "Set Active Camera" button for active cameras

- blender/arm/exporter.py
- blender/arm/exporter_opt.py
This PR adds a warning for a precision issue that would happen if a UV map has extremely large coordinates. Since exported UV coords are normalized based on the largest coordinate, such cases lead to situations where sufficiently small differences in UV coordinates cannot be represented anymore. In the case of UV coordinates many million units away from the origin, arbitrary coordinates in [0, 1] no longer work as expected.
There may be some cases in which we could attempt some automatic corrections, but since there can be cases where an entire UV island is scaled extremely large we cannot completely solve this issue. Also, the user might use procedural textures where there isn't any tiling.
Instead, there is now a function that checks whether we can represent pixel differences in the [0, …
> Warn about precision issues for very large UV coordinates

- blender/arm/lightmapper/utility/build.py
- blender/arm/lightmapper/utility/cycles/lightmap.py
- blender/arm/lightmapper/utility/cycles/prepare.py
- blender/arm/lightmapper/utility/denoiser/oidn.py
- blender/arm/lightmapper/utility/denoiser/optix.py
- blender/arm/lightmapper/utility/utility.py
The lightmapper was a bit broken with Blender 3.3. I added some fixes to render-tile paths, addon path, nodes fetching hadn't been updated to 3.3, and a fix for whatever [BF did to force filmic 8-bit output on bake results](https://developer.blender.org/rB2b80bfe):
> Update the Lightmapper to support Blender 3.3

- blender/arm/make.py
Adds the possiblity to use a custom player launch command by setting environment variables.
- `ARMORY_PLAY_HTML5`
- `ARMORY_PLAY_KROM`
The given string gets transformed with python templates using platform specific params:
- html5: `host, port, width, height, url, path, dir, browser`
- krom: `pid, audio, location, krom_path, path, resources, width, height`
If not set the default launch commands are used.
Html5 example:
```sh
export ARMORY_PLAY_HTML5='chrome --app=$url --new-window --window-size=$width,$height --auto-open-devtools-for-tabs'
```
The default launch commands:
```sh
export ARMORY_PLAY_HTML5='$BROWSER $url'
export ARMORY_PLAY_HTML5='$BROWSER http://$host:$port/$path'
export ARMORY_PLAY_HTML5='$BROWSER http://$host:$port/$dir/debug/html5'
```
The default launch command on krom: …
> Custom play launch commands

- blender/arm/make.py
This fixes an exception when trying to build for Krom on Windows that was introduced in https://github.com/armory3d/armory/pull/2605/commits/435f155c8a01a606ea72fd93d63921042644da3d. Unfortunately, I didn't notice it in time for the 22.10 release. There were two different problems:
- `str` was used as a variable name, thus overwriting all uses of `str()`
- `pid` is an integer and was causing an exception on Windows because it was used in a `subprocess` command list that only accepts strings or byte objects
@luboslenco I would have pushed this to main directly, but since it's quite a major issue: could you please update the builds on itch\.io after this PR is merged? Thanks a lot, and sorry for the inconvenience :)
> Fix building for Krom on Windows

- Sources/armory/logicnode/CombineColorNode.hx
- Sources/armory/logicnode/SeparateColorNode.hx
- blender/arm/logicnode/math/LN_combine_rgb.py
- blender/arm/logicnode/math/LN_separate_rgb.py
Closes https://github.com/armory3d/armory/issues/1721.
Following https://github.com/armory3d/armory/pull/2608, there still was no way to specifically set individual color values, which is possible now with the new "Combine RGBA" node. The "Separate RGB" node was expanded by an alpha output and is now called "Separate RGBA".
> New "Combine RGBA" node and add alpha output to "Separate RGB" node

- blender/arm/material/cycles_nodes/nodes_shader.py
Apparently, Blender changed the Principled BSDF sockets a second time between 3.0-3.3 without a note in the release notes, at least I can't find it anywhere.
This PR fixes parsing normals and emission values. Emission is still pretty broken since we have no space left in the gbuffers to save any emission color (https://github.com/armory3d/armory/issues/1774), and I don't think that we can fix it without a 3rd render target. However, this would mean that either the 3rd render target would be bound all the time during mesh rendering, or we'd need to sort the meshes each frame to prevent to many context switches and maybe also bandwidth issues (I'm not sure what affects the bandwidth in what way, more specifically where it matters). @ luboslenco do you have an opinion on this? I think the …
> Fix socket indices of Principled BSDF node

- Sources/armory/logicnode/GoToLocationNode.hx
- Sources/armory/trait/NavAgent.hx
- Sources/armory/trait/NavMesh.hx
- blender/arm/logicnode/navmesh/LN_go_to_location.py
This PR adds the following:
1.  Option in the NavAgent trait to set the height offset from the NavMesh.
2.  Option in the Go To Location node to set the height offset. 
3.  Option to set the NavAgent height more precisely using physics ray cast.
4.  Compensates the height introduced by the NavMesh voxel height.
5.  Outputs to some functionality during rotational and transitional tweening.
Thanks to @ Hreez on Discord for this feature request.
> Add option for NavAgent height offset

- blender/arm/material/cycles_nodes/nodes_input.py
- blender/arm/material/make_tess.py
For #2618, without the changes for #2616.
> Disp color mix

- Sources/armory/trait/internal/DebugConsole.hx
This fixes https://github.com/armory3d/armory/issues/2636. I also did some code cleanup and added a tooltip.
> Fix position of trait debug views if the debug console is left-aligned 

- Shaders/custom_mat_presets/custom_mat_deferred.frag.glsl
- Shaders/custom_mat_presets/custom_mat_deferred.vert.glsl
- Shaders/custom_mat_presets/custom_mat_forward.frag.glsl
- Shaders/debug_draw/line_deferred.frag.glsl
- Shaders/deferred_light/deferred_light.frag.glsl
- Sources/armory/renderpath/RenderPathDeferred.hx
- Sources/armory/trait/internal/DebugDraw.hx
- blender/arm/make.py
- blender/arm/make_renderpath.py
- blender/arm/material/cycles.py
- blender/arm/material/cycles_nodes/nodes_shader.py
- blender/arm/material/make.py
- blender/arm/material/make_decal.py
- blender/arm/material/make_mesh.py
- blender/arm/material/make_shader.py
- blender/arm/material/mat_state.py
- blender/arm/material/mat_utils.py
- blender/arm/material/parser_state.py
- blender/arm/node_utils.py
- blender/arm/write_data.py
This PR implements what was discussed in https://github.com/armory3d/armory/pull/2606#issuecomment-1266620114 and fixes https://github.com/armory3d/armory/issues/1774.
It took me a bit longer than expected since I was also working on improving the Armory PBR node but there still are some unresolved issues concerning automatic compatibility updates from the old PBR node so that I decided to remove the Armory PBR changes again and postpone them to hopefully next month. This way I have more time to test everything, I don't want to break anything shortly before a release.
**Major changes**:
- If there is both base color and emission color in a material, it will use a dedicated render target to store the emission color. If the node setup has emission but doesn't require a base color (e.g. …
> Fully support emission colors in all supported shader nodes

- Shaders/compositor_pass/compositor_pass.frag.glsl
- blender/arm/props_renderpath.py
- blender/arm/props_ui.py
- blender/arm/write_data.py
Allows to set a custom letterbox color.  
Also moved the letterbox shader code to the top of the main function to skip other  (invisble) effects from being processed.
> Allow to set custom letterbox color

- Sources/armory/logicnode/GetVelocityNode.hx
- Sources/armory/object/TransformExtension.hx
When `On Local Axis` option in the `Get RB Velocity` node was enabled, the output was incorrect. This PR fixes this issue. 
Thanks to @ Power_Broker on Discord for reporting the issue.
> Fix Get RB Velocity node

- blender/arm/handlers.py
This fixes https://github.com/armory3d/armory/issues/2642. It's not documented when exactly `bpy.context.active_operator` is available, so all we can do is to check whether it actually exists
> Fix exception when marking object as asset

- Sources/armory/logicnode/GetDateTimeNode.hx
- blender/arm/logicnode/native/LN_get_date_time.py
Sorry, "All" Option would return different timestamps in the case of operating with the seconds/millisecond values. In/out action resolved this issue
> Fixed GetDateTimeNode

- blender/arm/logicnode/sound/LN_play_sound.py
Previously it was set to 0, so sounds weren't audible without changing this setting.
> PlaySoundNode: set volume to 1 by default

- Sources/armory/system/Event.hx
In correspondence to the new wiki article: https://github.com/armory3d/armory/wiki/Events. Both the API docs and the wiki article use quite technical language, but I think they should be exact and leave little room for interpretation.
I noticed that `Event.get(name)` may return `[]` or `null` for events without listeners depending on how the API was used before. From an outside perspective this is pretty "random" behaviour, so I guess this should be changed?
> Document the event API

- blender/arm/utils.py
This PR fixes https://github.com/armory3d/armory/issues/2650.
`arm.utils.color_to_int()` is meant to convert a 4-component color into a 32 bit integer value (for direct use as `kha.Color`\*) but it could happen that the resulting value was bigger than that. As a result, the integer would be exported as unsigned 64 bit in the .arm file and because the reader in Iron [currently does not implement this (`0xcf` prefix)](https://github.com/armory3d/iron/blob/9f0d936045214fbc507dfb8442a8b6f1abc82998/Sources/iron/system/ArmPack.hx#L46-L66) the parser returned a wrong result.
Haxe still doesn't seem to have a UInt64 type on all targets, and even the Int64 type is simulated on some platforms IIRC. Armory doesn't seem to use them at the moment, but should we still read two 32 bit integers in case …
> Fix .arm reading issue when world color exceeds [0, 1] range

- blender/arm/make.py
The `build_success` method was never called since `proc_build` cannot be used to check the return code when in blender background mode.
> Fix background mode build

- Sources/armory/system/Event.hx
Following the discussion in https://github.com/armory3d/armory/pull/2649. Previously, `Event.get()` either returned `null` or `[]` if no listeners existed depending on how the API was used prior to that, now only `null` is returned in that case. This is a theoretically a breaking change, but I doubt that it will cause much trouble and all the occurences of `Event.get()` in the SDK sources still seem correct :)
> Event.get(): always return null if no listeners exist

- Sources/armory/logicnode/MapRangeNode.hx
Values in the map range node were incorrectly calculated, sometimes resulting in `infinity` and `NaN`. This PR fixes the calculations.
> Fix map range node

- blender/arm/props_bake.py
The native Armory baker (non-lightmapper) had been throwing some errors lately related to some 3.0+ changes. Now it should work again:
> Fix for Armory baker

- Sources/armory/logicnode/CreateRenderTargetNode.hx
- Sources/armory/logicnode/SetMaterialImageParamNode.hx
- Sources/armory/logicnode/SetMaterialRgbParamNode.hx
- Sources/armory/logicnode/SetMaterialValueParamNode.hx
- Sources/armory/trait/internal/UniformsManager.hx
Currently, if a default float/vector/texture material parameter of an object is changed to "per-object", all other default external links for that object were removed. This caused the default values to be lost and `null` values for uniforms. This PR intends to fix this by removing just the particular float/vector/texture from the external link maps in the `Uniforms Manager`.
Additionally some more comments and a few typos were fixed.
> Fix uniforms manager

- blender/arm/exporter.py
This PR fixes a runtime error that would happen if the world name contained special characters:
```
Sources/iron/data/WorldData.hx:57: World data "World_äöüß" not found!
Sources/iron/data/ShaderData.hx:54: Shader data "World_World_äöüß" not found!
Trace: TypeError: Cannot read property 'getContext' of null
at <anonymous>:3973:21
at <anonymous>:6005:5
at <anonymous>:7278:5
at Function.getSceneRaw (<anonymous>:6016:4)
at Function.parse (<anonymous>:7274:18)
at Function.getShader (<anonymous>:5998:24)
at iron_RenderPath.loadShader (<anonymous>:3972:18)
at <anonymous>:5233:29
at <anonymous>:5208:5
at <anonymous>:4758:7
```
I'm wondering whether it would make sense to maintain a list for all cases where something was renamed during export (cleared at the beginning of each export) that would …
> Fix loading world shader contexts if world name contains special characters

- blender/arm/logicnode/array/LN_array.py
- blender/arm/logicnode/array/LN_array_add.py
- blender/arm/logicnode/array/LN_array_boolean.py
- blender/arm/logicnode/array/LN_array_color.py
- blender/arm/logicnode/array/LN_array_float.py
- blender/arm/logicnode/array/LN_array_integer.py
- blender/arm/logicnode/array/LN_array_object.py
- blender/arm/logicnode/array/LN_array_string.py
- blender/arm/logicnode/array/LN_array_vector.py
In the past with https://github.com/armory3d/armory/commit/cf086d770ee6af9de0fa15c50876bc5f62198b0a.
I foolishly assumed `self.get_id_str()` was the same as `str(id(self))`, which broke some of the array nodes. I revert those certain line changes of mine in this PR. Sorry I didn't catch this before, I swear when I had tested them before, all of them worked, but I must have not looked hard enough: all blame goes to me.
Special thanks to @t3du for reporting these issues on Discord.
> Fix array node indexes

- blender/arm/make.py
Adds more checks to the custom html5 player launch command (#2693).
It does not modify the log output handling, so please keep the issue open.
> Improve player launch command

- Sources/armory/logicnode/DrawCameraNode.hx
- Sources/armory/logicnode/PauseActiveCameraRenderNode.hx
- blender/arm/logicnode/renderpath/LN_pause_active_camera_render.py
Requires https://github.com/armory3d/iron/pull/179
New node to pause only the rendering of the active camera. The logic will continue to run in the background. This could be used for example to render only certain camera projections to the render target using logic nodes and exclude redundant rendering effort.
Thanks to @ TriVoxel on Discord for the idea.
> Implement Pause Active Camera Render Node

- blender/arm/make_world.py
Errors were thrown if dark clouds were enabled and no sky texture was passed to the world node. Those errors are now fixed.
```
ERROR: D:\Blender\Projects\RP\0_Build_Files\Mine\A3D\Code_Testing\build_A3D_Code_Testing\compiled\Shaders\World_World.frag.glsl:71: 'hosekSunDirection' : undeclared identifier
ERROR: D:\Blender\Projects\RP\0_Build_Files\Mine\A3D\Code_Testing\build_A3D_Code_Testing\compiled\Shaders\World_World.frag.glsl:71: 'z' : vector swizzle selection out of range
ERROR: D:\Blender\Projects\RP\0_Build_Files\Mine\A3D\Code_Testing\build_A3D_Code_Testing\compiled\Shaders\World_World.frag.glsl:71: '' : compilation terminated
```
> Check if no sky texture for dark clouds

- blender/arm/props_renderpath.py
If was an already selected RenderPath that is invalid (i.e deleted or renamed), creating new RenderPath presets that didn't have matching settings (i.e. `Forward Clustering` for `Mobile` / `2D/Baked` and `Deffered Clustering` for `Desktop` / `Max`) would break new preset settings because of invalid preset list indexing. According to @ MoritzBrueckner, this issue was introduced in the Blender 3.3 LTS migration.
```python
File "D:\Blender\Projects\RP\B3D_33\armsdk/armory\blender\arm\props_renderpath.py", line 643, in execute
update_preset(wrd, context)
File "D:\Blender\Projects\RP\B3D_33\armsdk/armory\blender\arm\props_renderpath.py", line 120, in update_preset
rpdat.rp_renderer = 'Deferred'
AttributeError: 'NoneType' object has no attribute 'rp_renderer' …
```
> Check if RenderPath preset is none

- blender/arm/make.py
- blender/arm/props_ui.py
Do not hide `arm_project_khamake` exporter option when using preset exporters, but append its values to the khamake call.
> Append khamake options to command on preset exporters

- Sources/armory/logicnode/DrawEllipseNode.hx
- Sources/armory/logicnode/DrawImageNode.hx
- Sources/armory/logicnode/DrawRectNode.hx
- blender/arm/logicnode/renderpath/LN_draw_ellipse.py
- blender/arm/logicnode/renderpath/LN_draw_image.py
- blender/arm/logicnode/renderpath/LN_draw_rect.py
1. Adds anchor point option for `Draw Rect` and `Draw Image` nodes. Option to rotate around the anchor point.
2. New draw ellipse node.
> Anchor and rotation option for draw nodes + New draw ellipse node

- Sources/armory/logicnode/DrawTextAreaStringNode.hx
- blender/arm/logicnode/renderpath/LN_draw_Text_Area_string.py
This node extends the previous functionality of the draw string node that draws text in a line.
thanks @rpaladin @QuantumCoderQC @MoritzBrueckner for your comments.
Regarding the vertical alignment discussion, i  just left the code consistent with the actual aligned function. Robert did not merge the fix but he said  the actual code was deprecated and it was going to be replaced soon. Maybe then we can modify this too.
> add Draw Text Area String node

- blender/arm/props_traits.py
- blender/arm/props_ui.py
1. Added new trait specials UI menu for Blender.
2. Redesigned the print traits operator (outdated since 2.8+ migration; undocumented too).
3. Cleanup unnecessary whitespace.
```
Scene: Scene
Trait: Cube ("Scene_1_Haxe")
Trait: Cube ("Scene_1_Nodes")
Trait: Cube ("Scene_1_Canvas")
Trait: Cube ("ArcBall")
Trait: Cube ("Scene_1_WebAssembly")
Scene: Scene.001
Trait: Torus ("Scene_2_Haxe")
Trait: Torus ("Scene_2_Nodes")
Trait: Torus ("Scene_2_Canvas")
Trait: Torus ("Character")
Trait: Torus ("Scene_2_WebAssembly")
````
Special thanks to @t3du for the feature request suggestion.
> New trait specials menu

- blender/arm/material/cycles.py
- blender/arm/material/make_mesh.py
This PR fixes ghosting artifacts on some platforms caused by undefined behaviour if the emission buffer was used. Materials without emission didn't write to the buffer, in which case some platforms wrote zeroes to it but on others didn't update the buffer at all and in turn caused the emission values from earlier frames to persist.
Thanks to @ TriVoxel on Discord for the [report](https://discord.com/channels/486771218599510021/487613529990365184/1044950433686372353), from which I took the screenshot above.
> Fix emission ghosting effect on some platforms

- blender/arm/make.py
Fixes crash that was first introduced in #2731
**Steps to reproduce:** Attempting to recompile (with cache) with zero export presets available caused crashing on build export.
```
File "D:\Blender\Projects\RP\B3D_33\armsdk/armory\blender\arm\props_ui.py", line 1171, in invoke
return self.execute(context)
File "D:\Blender\Projects\RP\B3D_33\armsdk/armory\blender\arm\props_ui.py", line 1190, in execute
make.play()
File "D:\Blender\Projects\RP\B3D_33\armsdk/armory\blender\arm\make.py", line 572, in play
compile(assets_only=(not wrd.arm_recompile))
File "D:\Blender\Projects\RP\B3D_33\armsdk/armory\blender\arm\make.py", line 387, in compile
item = wrd.arm_exporterlist[wrd.arm_exporterlist_index]
IndexError: bpy_prop_collection[index]: index 0 out of range, …
```
> Fix crash on recompile

- Sources/armory/logicnode/GateNode.hx
Same issue & fix as https://github.com/armory3d/armory/pull/2398, but this time for the Gate node. Thanks to @ TriVoxel for the report on Discord.
> Gate node: fix accessing vector methods when DCE is on

- Sources/armory/logicnode/CaseIndexNode.hx
- blender/arm/logicnode/logic/LN_case_index.py
Same fix as https://github.com/armory3d/armory/pull/2740 again, this time for https://github.com/armory3d/armory/pull/2743. While I was on it I also cleaned up the node's sources a bit (whitespace, unused variables/functions etc.) and took the liberty of changing the documentation as well as some socket names to hopefully make its usage a little clearer.
I didn't implement a replacement function for my changes by purpose (in fact, I even removed it since the node's version is still 1 so it is never called) because the node was only implemented a few days ago and isn't yet part of any SDK release.
> Case Index node: fix accessing Vec4.equals() when DCE is on + cleanup

- blender/arm/props_traits.py
This PR implements a `Edit Script` button for WASM traits. Previously, WASM traits didn't allow the option of opening the local file in a OS (or Armory User Preferences) specified text editor, unlike with `Haxe Scripts` and `Bundled` scripts.
Special thanks to @MoritzBrueckner for code review.
> "Edit Script" button for WASM traits

- blender/arm/exporter.py
Fixes https://github.com/armory3d/armory/issues/2659.
When `bpy.ops.nla.bake()` fails, it doesn't create a new action so the `action` variable still contains the original one. In such situtations, the original action was treated as being baked and would get deleted after being exported.
> Don't delete actions if baking was not successful

- Sources/armory/logicnode/GetObjectGroupNode.hx
- blender/arm/logicnode/scene/LN_get_object_collection.py
> logic node: Get Object Collection

- blender/arm/logicnode/logic/LN_gate.py
- blender/arm/logicnode/logic/LN_merge.py
- blender/arm/logicnode/math/LN_compare.py
- blender/arm/logicnode/math/LN_quaternion_math.py
- blender/arm/logicnode/native/LN_call_haxe_static.py
Reported by @ MoritzBrueckner on Discord. Past commit of mine: https://github.com/armory3d/armory/commit/94902e5a59e01eaee1093c82974327c75551f13e, is the culprit. Apparently, I implemented incorrect replacement checks, which causes errors with outdated nodes, such as those in online demo blends.
For example with the [archery](https://github.com/armory3d/armory_templates/tree/master/archery) demo, the merged node would throw the error:
```
A node of type LNMergeNode in tree "NodeTree" failed to be updated, because there is no (longer?) an update routine for this version of the node. Original exception:
File "[...]\armory\blender\arm\logicnode\replacement.py", line 237, in replace_all
replace(tree, node)
File …
```
> Fix incorrect node replacements

- Shaders/compositor_pass/compositor_pass.frag.glsl
- Shaders/compositor_pass/compositor_pass.json
- Sources/armory/logicnode/CameraGetNode.hx
- Sources/armory/renderpath/Postprocess.hx
- blender/arm/logicnode/postprocess/LN_get_camera_post_process.py
- blender/arm/logicnode/postprocess/LN_set_camera_post_process.py
- blender/arm/make_renderpath.py
- blender/arm/props_renderpath.py
- blender/arm/props_ui.py
- blender/arm/write_data.py
Originally requested [here](https://forums.armory3d.org/t/underwater-effect/5093). Combined with fog and a LUT texture or a colored overlay, a convincing underwater effect can be achieved.
<hr />
https://user-images.githubusercontent.com/69180012/210872628-1601ad40-53ad-46b1-a891-3fd3962e3caf.mp4
`props_renderpath.py` - New distort data.
`props_ui.py` - New distort UI. [Unrelated] Moved lensflare UI closer to one another (team decision).
`make_renderpath.py` - New distort data.
`write_data.py` - New distort data.
`LN_get_camera_post_process.py` - New distort output.
`LN_set_camera_post_process.py` - Fixed incorrect type statement (additionally reported on Discord). Renamed input to distort.
`CameraGetNode.hx` - New distort data. Implemented missing input return.
`Postprocess.hx` - New …
> New compositing distort shader

- blender/arm/props_ui.py
This adds a compact launcher on the top of the blender window. 
Compared to Armory Player, the advantage is not needing to tab to render properties. Compared to key shortcut, it can terminate build, and (personally speaking) gives more obvious immediate signs of something happening than "building..." message in the viewport.
There could be a discussion about things that go in there. Possibly, an icon for build warnings?
* also if blender has a built-in stop icon, please can someone show it using a big red circle because i can't seem to find anything better than plane icon?
> Add player buttons to topbar

- blender/arm/exporter.py
- blender/arm/props_renderpath.py
- blender/arm/props_ui.py
Closes #842
Test blend: https://github.com/rpaladin/armory3d-export-deform-only-test
**NOTE:** Test blend uses code from: https://github.com/armory3d/iron/pull/184
For those curious, if the new `Only Deform Bones` option is enabled, any parent bone that is marked as non-deformed, their children will not be exported along with the parent bone (this is expected behavior and not a bug).
<hr />
Special thanks to @MoritzBrueckner and @QuantumCoderQC for review and suggestions.
> Export deform only option

- Sources/armory/logicnode/RemoveObjectNode.hx
The remove object node, removes the object from its collection only when that collection is assigned in blender. But if the collection is assigned within armory, the object remains in the collection despite being removed. This added code removes the object from the armory collection to keep it consistent with the other collection nodes.
> Remove Object Node: remove object from collection

- Sources/armory/logicnode/GetCameraStartEndNode.hx
- Sources/armory/logicnode/SetCameraStartEndNode.hx
- blender/arm/logicnode/camera/LN_get_camera_start_end.py
- blender/arm/logicnode/camera/LN_set_camera_start_end.py
These nodes allows to modify the initial  start end plane of a given camera. Very useful for effects or camera draws (according to object position)
> Logic Nodes: Get/Set Camera Start End Node

- blender/arm/make_world.py
- blender/arm/props_ui.py
- blender/arm/write_probes.py
This PR closes https://github.com/armory3d/armory/issues/2760 and requires https://github.com/armory3d/armsdk/pull/62.
Using CMFT with OpenCL can lead to driver hangs as described in the linked issue. My changes allow to disable OpenCL in the preferences to work around the problem, and additionally display a warning to the console in case CMFT takes an unusually long amount of time (> 20s). I'm not sure whether 20 seconds are a good value and whether this warning is really needed, so please let me know if I should revert that commit.
> Option to disable OpenCL processing in CMFT to avoid driver freeze

- Shaders/volumetric_light/volumetric_light.frag.glsl
Reference: <https://armory3d.github.io/armory_examples_browser/#examples-light_volumetric>
(Please note, the lamp that is in the scene _is_ of type `Sun`, yet the uniforms are still never used.)
> Cleanup volumetric light

- Shaders/deferred_light_solid/deferred_light.frag.glsl
Not sure why these uniforms were even included originally?
Reference: <https://armory3d.github.io/armory_examples_browser/#examples-material_shadeless>
> Cleanup deferred light solid

- blender/arm/make.py
- blender/arm/make_renderpath.py
- blender/arm/props_renderpath.py
- blender/arm/props_ui.py
In case anyone wonders:
1. I renamed "Color Grading" to "Colorgrading" to match the manual (it's also logically shorter). (`props_renderpath.py`)
<https://github.com/armory3d/armory/wiki/screen-effects#lut-colorgrading>
2. Removed some unnecessary `true` check conditions. (`make.py`)
3. I also moved some misc code lines so that lens code would be closer to LUT code. This caused some extra diff. (`props_renderpath.py` & `make_renderpath.py`)
> Allow custom naming of lens texture

- Shaders/compositor_pass/compositor_pass.frag.glsl
- Sources/armory/logicnode/CameraGetNode.hx
- Sources/armory/logicnode/CameraSetNode.hx
- blender/arm/logicnode/postprocess/LN_get_camera_post_process.py
- blender/arm/logicnode/postprocess/LN_set_camera_post_process.py
Issues caused by me in #2751..
`compositor_pass.frag.glsl` - Special thanks to @ Armory-Community-Channel for reporting this issue on Discord.
`CameraGetNode.hx` - Added comments; fixed outputs order and added missing output.
`CameraSetNode.hx` - Added comments; fixed inputs order and added missing input.
`LN_get_camera_post_process.py` - Added comments; fixed return order and added missing return.
`LN_set_camera_post_process.py` - Added comments; fixed return order and added missing return; match default values with [Postprocess.hx](https://github.com/armory3d/armory/blob/main/Sources/armory/renderpath/Postprocess.hx). (Original defaults weren't implemented by me.)
> Fix realtime postprocessing

- Sources/armory/logicnode/ArrayGetPreviousNextNode.hx
- blender/arm/logicnode/array/LN_array_get_PreviousNext.py
As we have the array get next, I thought to make the array get previous. But then i realized that in order to change the direction between them is needed the index, so i end up only uploading the previous/next that has the boolean condition to establish the direction of the item to be retrieved, as is shown in the video containing a collection arrays of objects as a path to follow. 
https://user-images.githubusercontent.com/32546729/216962298-50502400-7b75-4b11-91b5-bb30215b5472.mp4
> Logic Node: Array get Previous Next

- Sources/armory/logicnode/ArrayInArrayNode.hx
- Sources/armory/logicnode/ArrayIndexNode.hx
Both nodes returned -1 for vector items or array items (the case when the input array is an array of more than one dimension), even though those items did indeed exist in the array. That's because the indexOf function of  the array class does not handle the comparison properly.
With this fix now the comparison is handled and the correct value is returned for both nodes.
> Fix ArrayContains and ArrayIndex Nodes

- Sources/armory/logicnode/ArrayAddNode.hx
Meanwhile an efficient comparison method is defined, the array unique values can be compared as a string representation for values like arrays or vector, which at the moment are not working.
In that case I added a condition to only do that for cases that are not: Bool, Float, Int or String (if there is a better way to check the value types please update this code or leave a comment so i can modify it)
When the time comes this code can be discarded for the definitive solution.
> ArrayAdd Node: comparison for other type of values

- Shaders/deferred_light/deferred_light.frag.glsl
- Shaders/std/light.glsl
- blender/arm/material/make_cluster.py
- blender/arm/material/make_mesh.py
- blender/arm/material/shader.py
- blender/arm/props_renderpath.py
- blender/arm/props_ui.py
- Fixed shader generation and compilation when using micro shadowing (`sampleLight()` did not receive the correct amount of arguments)
- Fixed the value range of the micro shadow factor (following the [original paper](https://advances.realtimerendering.com/other/2016/naughty_dog/index.html)). Previousl,y values could be both negative or greater than 1. The original implementation does not use a `dotNL` value clamped to [0, 1] but instead uses its absolute value, but since the mesh will be in shadow for negative values I think we can keep it as is.
- Added a more precise UI tooltip to the micro shadowing property
- Disable the micro shadowing property if the selected material model doesn't support it (mobile, solid/baked)
- Enable micro shadowing by default for the "Max" render path preset
> Various micro shadowing fixes and improvements

- Shaders/deferred_light/deferred_light.frag.glsl
- Shaders/deferred_light_mobile/deferred_light.frag.glsl
- Shaders/std/brdf.glsl
- Shaders/std/light.glsl
- Shaders/std/light_mobile.glsl
Fixes https://github.com/armory3d/armory/issues/2792 (see the issue for an example).
Some dot products weren't clamped correctly and caused some mathematical mayhem when calculating the microfacet BRDF in `specularBRDF()`. Thanks @ LVutner for the help!
> Fix roughness artifacts in specularBRDF()

- blender/arm/props.py
- blender/arm/props_ui.py
Special thanks to @ QuantumCoderQC for review.
For those who wonder, I wrapped the code into a function, so that it's easier to implement code for copy/repath sound data-blocks in the future as well. Currently, to my knowledge, imported sounds can only be exported from Blender IF embedded in videos. So the exporting will need to be done using raw Python, but that's for another day. 🙂
Copy Override - False (First Log - mage Does Not Exist / Second Log - Image Exists)
Copy Override - True (First Log - mage Does Not Exist / Second Log - Image Exists)
> New copy to bundled operator/button

- Sources/armory/logicnode/VectorMoveTowardsNode.hx
- Sources/armory/math/Helper.hx
- blender/arm/logicnode/math/LN_vector_move_towards.py
To be more easy to use, the node automatically changes the current vector under the hood when it is changed.
I can't see a problem with this behavior yet, except some performance loss because of the comparison. If anyone test other use cases for this and see something that shouldn't happen, please let me know.
Its update is limited by one time per frame, so connecting its output multiple times will not change the speed of the movement.
In the gif, I input the current vector [0, 0, 0] and the target vector [5, 0, 0]. The green cube is positioned at the target position.
> Add Vec4 moveTowards function and a new logic node for it

- blender/arm/make_logic.py
A small fix for when the call node group don't have a reference node tree
> Fix empty call group nodes

- blender/arm/logicnode/arm_node_group.py
- blender/arm/logicnode/arm_nodes.py
- blender/arm/logicnode/tree_variables.py
Some cases were missed when polling for node groups. This PR fixes it.
> Fix node group polling

- Sources/armory/logicnode/PlayActionFromNode.hx
- blender/arm/logicnode/animation/LN_play_action_from.py
Requires: [iron:187](https://github.com/armory3d/iron/pull/187)
This modification allows the node to play the action backwards for both Object and Bone Animations. The functionality clones the action as actionReverse and reverses the frames. In that way the animation class works as usual.
> PlayActionFrom: add boolean for Reverse Action

- Sources/armory/logicnode/ApplyForceAtLocationNode.hx
- Sources/armory/logicnode/ApplyImpulseAtLocationNode.hx
- blender/arm/logicnode/physics/LN_apply_force_at_location.py
- blender/arm/logicnode/physics/LN_apply_impulse_at_location.py
Currently, in these logic nodes, the position at which the force is applied is incorrect. By default, Bullet applies force or impulse relative to Rigid Body position. The rotation of the Rigid Body is not accounted for in Bullet physics. But the logic nodes did not follow this convention, resulting in incorrect application location. 
This PR fixes the above issues. 
References:
1. [Clarifications form creator of Bullet Physics](https://pybullet.org/Bullet/phpBB3/viewtopic.php?p=10849&sid=02a0494883aa9e90879dd0a22603dca3#p10849)
2. [Implementation of apply force at location](https://pybullet.org/Bullet/BulletFull/btRigidBody_8h_source.html#l00318)
> Fix apply force and apply impulse at location

- blender/arm/exporter.py
Errors would be raised if a particle system's instance object wasn't found because it wasn't exported.
```python
Error: Python: Traceback (most recent call last):
File "D:\Blender\Projects\RP\B3D_334\armsdk/armory\blender\arm\props_ui.py", line 1178, in invoke
return self.execute(context)
File "D:\Blender\Projects\RP\B3D_334\armsdk/armory\blender\arm\props_ui.py", line 1197, in execute
make.play()
File "D:\Blender\Projects\RP\B3D_334\armsdk/armory\blender\arm\make.py", line 555, in play
build(target=runtime_to_target(), is_play=True)
File "D:\Blender\Projects\RP\B3D_334\armsdk/armory\blender\arm\make.py", line 473, in build
export_data(fp, sdk_path)
File "D:\Blender\Projects\RP\B3D_334\armsdk/armory\blender\arm\make.py", line 182, in export_data
ArmoryExporter.export_scene(bpy.context, …
```
> Don't export particle if instance isn't exported

- blender/arm/material/make.py
- blender/arm/material/mat_batch.py
The material batch option did not properly separate materials since it missed a few properties. This PR fixes by including those properties in the material signature.
Also, when material batch was enabled, the input textures were not treated as uniforms for shadowmap context. This caused incorrect shadows for meshes. Fixed it by adding these uniforms from the mesh context
> Fix material batch

- blender/arm/nodes_logic.py
For some nodes like _Array Loop_, the previous code would generate a wrong HTML anchor to link to the node reference (e.g. `#array-loop-node` instead of `#array-loop`) because the code didn't match with the script that generates the documentation.
The new code still isn't 100% fail-safe since we depend on GitHub behaviour and we currently don't check for special characters. But to my my knowledge no node's `bl_label` has such characters so we should be safe :)
Thanks to @ BrahRah on Discord for the report.
> Fix html anchor in the "Open Node Documentation" operator for some nodes

- Sources/armory/trait/internal/DebugConsole.hx
The values displayed by the watch nodes were not in full due to the name and the value displayed in the same line. Additionally, all the outputs were displayed at the same time, making it difficult to decipher. This PR uses collapsible panels to display the values of the watch nodes. Another advantage is that the value of the node is retrieved only when panel is expanded, reducing some overhead.
before:
now:
**Edit:** Also thanks to @ BrahRah for bringing up this issue on Discord.
> Use panels for watch nodes in Debug Console

- blender/arm/exporter.py
Iron expects `TAnimation.has_delta` for delta transform animations in order to initialize some transform attributes ([source](https://github.com/armory3d/iron/blob/0f28228090ebc452da3c21bab8bea64f7414ec88/Sources/iron/object/ObjectAnimation.hx#L85-L95)), but Armory did not set `has_delta`  during export, leading to the following runtime exception:
```
Trace: TypeError: Cannot set properties of null (setting 'x')
at iron_object_ObjectAnimation.updateTransformAnim (<anonymous>:17492:22)
at iron_object_ObjectAnimation.updateObjectAnim (<anonymous>:17388:8)
at iron_object_ObjectAnimation.update (<anonymous>:17384:9)
at iron_Scene.updateFrame (<anonymous>:4550:9)
at update (<anonymous>:3418:21)
at kha_TimeTask.task (<anonymous>:25557:4)
at kha_Scheduler.executeTimeTasks (<anonymous>:25440:76) …
```
> Fix export of delta transform animations

- blender/arm/props_traits.py
Fixed issue 1: The <kbd>Edit Script</kbd> button was still enabled even when the active trait property was empty, which caused errors if the button was clicked because no trait property was selected.
Fixed issue 2: Trait properties panel was still visible even when the active trait property was empty, which shouldn't happen.
> Add missing checks for bundled traits

- blender/arm/keymap.py
- blender/arm/logicnode/arm_node_group.py
- blender/arm/logicnode/arm_nodes.py
- blender/arm/logicnode/arm_sockets.py
- blender/arm/logicnode/miscellaneous/LN_call_group.py
- blender/arm/logicnode/miscellaneous/LN_group_input.py
- blender/arm/logicnode/miscellaneous/LN_group_output.py
This PR adds many QOL improvements to the node groups.
1. Better UI for group nodes, indicating the number of users, fake user and a button to create a copy of current group:
Also removed the `New Group` button when there is an existing node group in use. It was sometimes accidentally clicked making it annoying.
2. Add shortcuts to the node group operations:
3. `Add call group node` operator now follows cursor location and adds the node there:
4. More improvements with the overall behavior of sockets when connecting/ disconnecting.
> Node group improvements

- Sources/armory/logicnode/CastPhysicsRayOnNode.hx
- Sources/armory/logicnode/PhysicsConvexCastOnNode.hx
- blender/arm/logicnode/physics/LN_convex_cast_on.py
- blender/arm/logicnode/physics/LN_ray_cast_on.py
The `Ray Cast` and `Convex Cast` nodes have multiple outputs. Each time an output is accessed, the physics collision operation is performed causing unnecessary overhead. To reduce this overhead and only perform the physics operations when needed, the new nodes will have an `In` and `Out` socket.
The current Ray Cast and Convex Cast may be deprecated once the new nodes become a norm.
Preview of new nodes:
> Ray Cast On and Convex Cast On nodes

- blender/arm/material/cycles.py
- blender/arm/material/make_depth.py
- blender/arm/material/make_mesh.py
- blender/arm/material/parser_state.py
This PR fixes a bunch of shader compilation errors due to missing declarations, caused by two different problems:
- Vertex shaders for mesh or depth contexts didn't include `compiled.inc`, but the wave texture node assumes that this file is included.
- `state.procedurals_written` was set to true when any shader of a material wrote the procedural functions, even if other shader types of the same material were still missing them (and in turn could not find some function declarations). I changed this variable to store per-shader state instead.
Thanks to @ Shakespeare on Discord for the report :)
> Fix shader generation for vertex displacement with procedural textures

- Sources/armory/logicnode/VectorClampToSizeNode.hx
- blender/arm/logicnode/math/LN_vector_clamp.py
Previously, the Vector Clamp node only clamped the length of the vector, this PR makes it possible to alternatively clamp the elements of the vector instead.
> Add component-wise mode to Vector Clamp node

- Sources/armory/logicnode/SpawnCollectionNode.hx
- blender/arm/exporter.py
- blender/arm/logicnode/scene/LN_spawn_collection.py
This PR requires: https://github.com/armory3d/iron/pull/190
This PR intends to solve the following issue with collection spawning:
1. Collections, when spawned from other scenes into the current scene had multiple instances of traits, which ideally should not be. This was because each collection was exported for each scene creating redundancies. Now, there still is a some redundancy, but each collection is exported only if used by the scene that is being exported.
2. The collections when spawned, added an instance of it also to the raw scene data. This meant that when the scene is reset, the collection instance is again spawned. This is fixed by not adding the collection to the raw data.
3. The spawn collection node now has a scene reference to spawn the collection from the given scene …
> Fix collection spawning

- blender/arm/utils.py
Fixes #2846
The colorspace setting of the image was used when exported to disk. This PR disables use of colorspace at export and use only data.
> Do not use colorspace when exporting images

- blender/arm/material/make_depth.py
- blender/arm/material/make_inst.py
The normals were computed incorrectly when instanced objects  had rotations. This PR fixes it.
Thanks to @ Shakespeare and @ projectBP  on Discord for reporting the issue and testing the changes.
> Fix normal vectors for instanced objects

- Shaders/compositor_pass/compositor_pass.frag.glsl
- Sources/armory/logicnode/CameraGetNode.hx
- Sources/armory/logicnode/CameraSetNode.hx
- Sources/armory/renderpath/Postprocess.hx
- blender/arm/logicnode/postprocess/LN_get_camera_post_process.py
- blender/arm/logicnode/postprocess/LN_set_camera_post_process.py
- blender/arm/props_ui.py
For some reason, Shapren and Vignette attributes were never exposed/implemented with the get/set postprocessing logic nodes. This PR implements them.
`props_ui.py` | Matched alphabetical order.
`LN_get_camera_post_process.py` | Added new ***Sharpen*** and ***Vignette*** attributes.
`LN_set_camera_post_process.py` | Added new ***Sharpen*** and ***Vignette*** attributes.
`Postprocess.hx` | Added new ***Sharpen*** and ***Vignette*** attributes.
`CameraGetNode.hx` | Added new ***Sharpen*** and ***Vignette*** get returns.
`CameraSetNode.hx` | Added new ***Sharpen*** and ***Vignette*** set returns.
`compositor_pass.glsl` | Added realtime postprocessing features to ***Sharpen*** and ***Vignette*** code + removed unused/commented code.
Special thanks to @ MoritzBrueckner for review and insightful …
> Implement missing renderpath attributes for postprocessing logic nodes

- blender/arm/make.py
This PR fixes a performance issue that would happen in projects with scenes that have thousands of objects. Armory adds all mesh and empty objects to a temporary collection to make them visible to the depsgraph in order to apply modifiers (see https://github.com/armory3d/armory/pull/1498), but the code had at least quadratic complexity due to—for each object—calling `export_coll.all_objects.keys()` and iterating through the result (list). By using a _set_ of object names that we manually update, the complexity should be linear now.
The following profiler screenshot shows the impact of the fixed issue in a file with ~3800 objects (I had to force a single-threaded build to show everything in the profiler results):
I guess the current approach of using a Zoo collection is still somewhat slow …
> Fix performance issue when creating zoo collection for correct modifier export

- blender/arm/logicnode/arm_node_group.py
- blender/arm/logicnode/arm_nodes.py
- blender/arm/logicnode/tree_variables.py
- blender/arm/props_ui.py
- blender/arm/utils.py
This PR fixes/improves two issues reported by @ QuantumCoderQC on Discord:
- There was an error after duplicating a node tree with tree variables: When duplicating a node tree, Blender copies the original tree variable for which no master node exists in the copy and then calls `ArmLogicVariableNodeMixin.copy()` for each node. Because there is no master node in the copied tree, the previous implementation of `copy()` then assumed that the variable doesn't exist and in turn created a new variable without any node assigned to it (the copied nodes were still correctly assigned to the original variable copied by Blender).
Now, there is a check in place whether the variable already exists. If so, we simply add the copied node to the existing variable, just like before if a node was copied …
> Improve and fix handling of tree variables

- Sources/armory/logicnode/LetterboxGetNode.hx
- blender/arm/logicnode/postprocess/LN_set_letterbox_settings.py
My mistake that I did not catch this earlier.
<hr />
`Get Letterbox Settings` (Haxe)
Special thanks to @ Armory-Community-Channel for reporting the problem and to @ QuantumCoderQC for pointing out the incorrect return value (currently returns an array float when it should return a float)
<hr />
`Set Letterbox Settings` (Python)
While not important because the alpha value is never used, I set the default alpha value to `1.0` for the visual side of the set letterbox settings node, otherwise it looks a bit weird in Blender e.g.
> Fix get letterbox size return value

- blender/arm/exporter.py
In some rare cases it can happen that the scene camera isn't actually a camera object, previously causing exceptions at runtime such as
```
Trace: TypeError: Cannot read property 'V' of null
at Function.setObjectConstant (<anonymous>:24561:21)
at Function.setObjectConstants (<anonymous>:22348:26)
at iron_object_MeshObject.render (<anonymous>:20167:25)
at iron_RenderPath.submitDraw (<anonymous>:8570:6)
at iron_RenderPath.drawMeshes (<anonymous>:8530:9)
at Function.drawMeshes (<anonymous>:1668:45)
at Function.commands (<anonymous>:1755:39)
at iron_RenderPath.armory_renderpath_RenderPathCreator.path.commands (<anonymous>:1838:41)
at iron_RenderPath.renderFrame (<anonymous>:8317:8)
at iron_Scene.renderFrame (<anonymous>:9234:27)
```
(trying to access `camera.V` with `camera == null` here) …
> Fix runtime exception when non-camera object is used as scene camera

- blender/arm/props_renderpath.py
Initially, I had attempted to fix the bug here: #2716. And while it _does_ fix new RP items if the Armory Player RenderPath data-block was _invalid_ or _empty_, it apparently is still broken for _valid_ RenderPath items.
The bug happened when the Armory Player RenderPath data-block was invalid.
https://github.com/armory3d/armory/assets/69180012/01f448e0-c18e-463c-b5bb-754e6dad6e6f
The bug still happens when the Armory Player RenderPath data-block is valid.
https://github.com/armory3d/armory/assets/69180012/1c09e2cd-3d6a-44bf-9b9e-d6627bc873bc
Special thanks to @ MoritzBrueckner for code review.
> Fix new RP items

- Shaders/std/brdf.glsl
This PR fixes a long-standing issue with NaN fragments that would happen with roughness values of 0 (or values close to that due to float precision) at some viewing angles relative to the light direction. While this wasn't really problematic in most cases, the bloom effect made the NaN values visible as white screen flickering like mentioned in https://github.com/armory3d/armory/pull/2725 (check the [render_bloom](https://github.com/armory3d/armory_examples/tree/master/render_bloom) example).
Some technical details, to whom it may interest:
From a mathematical point of view the division by zero is a consequence of narrowing the distribution function representing the specular dot until it is infinitesimally small and infinitely large (dirac delta). If the roughness approaches zero, the …
> Fix potential division by zero in GGX normal distribution function

- Sources/armory/logicnode/DrawArcNode.hx
- Sources/armory/logicnode/DrawCircleNode.hx
- Sources/armory/logicnode/DrawCurveNode.hx
- Sources/armory/logicnode/DrawEllipseNode.hx
- Sources/armory/logicnode/DrawPolygonNode.hx
- Sources/armory/logicnode/DrawTextAreaStringNode.hx
- blender/arm/make.py
This PR fixes compilation of the draw nodes that use the GraphicsExtension class if Zui export is set to "Auto". It is more of a last-minute workaround for SDK 23.06 than a proper fix, so we should revisit this in the future and either remove the "Auto" setting (simple solution but this would always export the default font, code-wise DCE will take care of not increasing the output size too much) or maybe implement an export callback for each node such that a node could register its need for Zui classes.
@ luboslenco do you have any preference regarding a proper solution?
> Fix compilation of draw nodes if "Zui" setting is set to "Auto"

- Sources/armory/trait/physics/bullet/PhysicsHook.hx
- Sources/armory/trait/physics/bullet/SoftBody.hx
- blender/arm/exporter.py
- blender/arm/exporter_opt.py
This PR is an overhaul of the SoftBody physics on both HL and JS targets.
Fixes #2654 and #1920 
Requires https://github.com/armory3d/iron/pull/194 and https://github.com/armory3d/haxebullet/pull/41
1. For #1920, I export an extra index buffer called `vertex_map`. This maps Blender's [`vertex_index`](https://docs.blender.org/api/current/bpy.types.MeshLoop.html#bpy.types.MeshLoop.vertex_index) attribute to Armory's index buffer. This information was lost at export. This is then used to connect vertices and faces properly at SoftBody initialization.
2. For #2654, I changed the data type passed to the SoftBody initialization function.
* **Added support to HL targets**: This was done by creating a custom array type to overcome HL to WebIDL constraints on array data types such as …
> SoftBody physics overhaul

- Sources/armory/trait/physics/bullet/DebugDrawHelper.hx
- Sources/armory/trait/physics/bullet/PhysicsWorld.hx
- blender/arm/exporter.py
- blender/arm/props.py
- blender/arm/props_ui.py
This PR adds debug drawing support for Bullet physics. It requires https://github.com/armory3d/haxebullet/pull/42 where I explained some more technical details.
The debug drawing settings can be found in the `Rigid Body World` panel of the scene properties:
On the Haxe side there are more debug flags available, however, these do not take effect in Armory since Bullet does not use them in the library core, instead they seem to be used in individual (and sometimes obsolete) Bullet examples only (urgh...). Some flags have dependencies between each other, the wireframe flag even leads to drawing the suspension of raycast vehicles for whatever reason (Bullet's codebase truly is something else... :D). In some cases I have put some explanations for the unused flags as comments to the code. …
> Add support for Bullet physics debug drawing

- blender/arm/handlers.py
As already mentioned in https://github.com/armory3d/armory/pull/2898, Blender now initializes the name of new custom node trees to their `bl_label` attribute which is identical to the editor name, which in our case causes warnings because logic nodes named `Logic Node Editor` have to be renamed in order to be valid Haxe class names.
Now, Armory listens to the creation of new logic node trees and renames them to `LogicTree` afterwards. This is potentially prone to timing-related errors in case the operator is called as part of some larger routine that reads/writes the name, but I don't know of any of such routines at the moment so it should be safe. It's definitely much better than greeting new users with a warning they might not understand...
---
Before choosing the current solution I …
> [3.6 LTS] Avoid warnings for default logic tree names

- Sources/armory/ui/Canvas.hx
- blender/arm/props.py
- blender/arm/props_ui.py
- blender/arm/write_data.py
This PR "fixes" https://forums.armory3d.org/t/solved-canvas-asset-distortion-when-scaling/5274, which was caused by always using low quality image scaling for canvases. Now the canvas image scaling quality is exposed to the Blender UI as a global setting and doesn't have to be set via Haxe:
> Allow to configure canvas image scaling quality from Blender UI

- blender/arm/exporter.py
In some cases it can happen that objects reference collections in Blender that do not exist at scene root. This happens for example if you copy a group instance into a new blend file without copying the actual group. In that case, the group is implicitly copied as well, but it isn't "used" by the scene (thus `self.scene.user_of_id(collection)` returns 0).
> Ensure referenced collections are always exported

- Sources/armory/logicnode/RotationMathNode.hx
Cannot check for Null on hashlink base types so I changed it to Null<Float> whereas the Lerp/Slerp wanted an f32 so those were set to Null<Single>. Other solutions are to use a Dynamic type to then check if null, or use another inputs.get(i) in the null check.
> Hashlink Null Float Fix 

- .vscode/settings.json
Allows to read the vscode settings json file for tools not supporting jsonc.
> Fix vscode settings.json

- blender/arm/material/cycles.py
- blender/arm/utils.py
This PR fixes shader compilation for nodes or sockets with `§` or `$` in their names and also fixes more cases where the shader compiler would output a warning because of consecutive underscores.
```
ERROR: [...]\compiled\Shaders\awning01_red__props_blend_mesh.frag.glsl:9: '$' : unexpected token
WARNING: [...]\compiled\Shaders\chimney005__props_blend_mesh.frag.glsl:38: 'VertexLitGeneric_GroupInput__bumpmap_texture__res' : identifiers containing consecutive underscores ("__") are reserved
WARNING: [...]\compiled\Shaders\chimney005__props_blend_mesh.frag.glsl:67: 'VertexLitGeneric_GroupInput__selfillummask_texturealpha__res' : identifiers containing consecutive underscores ("__") are reserved
```
There are more situations where Armory generates shader code with double underscores, but for …
> Fix shader compilation for some node names with special characters

- Shaders/deferred_light/deferred_light.frag.glsl
When irradiance was turned off (either globally or per material), the environment light that's added to the output fragment color was initialized with 1.0 which resulted in a fully-lit scene. This PR sets it to zero as it seems more natural. The default case with irradiance turned on is not touched by this PR.
Before:
After:
@e2002e I noticed that you also work with `envl` in your current voxel AO/GI work, please let me know in case this breaks anything for you :)
> Fix too bright environment and barely visible shadows if irradiance is off

- Sources/armory/logicnode/MathExpressionNode.hx
- blender/arm/logicnode/math/LN_math_expression.py
The formula-parsing runs now into its property-setter only ones (not each time like before while fetching result from socket).
Also some additional optimizations is there to not have to create allways new params (it directly changes its single values now).
Into python part it's working now for all kind of math-functions.
I am also removed the old error-parsing inside of code!
Sorry that i am not good enough to make syntax-parsing into python, anyway ...
if there is something wrong into math-expr.,
it still traces error-msg by haxe on console.
( Tryed also to extract out the parsing-part of formula-lib [300 lines .hx]
and the haxe->python transpiled code was really huge [1400 lines]...
it works ~^ but maybe not good to maintain ~^ )
Here some testfiles: …
> optimized MathExpression

- Sources/armory/logicnode/MathTermNode.hx
- blender/arm/logicnode/math/LN_math_term.py
Ahoi, another LN for formula-lib (^_^):
This node can be used to change mathematical term expressions also at runtime, so its not as fast as MathExpression but can also bind output-terms to other termparam-inputsockets now.
Also useful to calculate the symbolic derivation to the first param or to let transform the math-expr. into a more simple form.
Wrote also a little functionplotter for testing: 
http://www.maitag.de/semmi/armory3d/mathTerm/html5
(nodes and blend files here: http://www.maitag.de/semmi/armory3d/mathTerm/
or here to: https://github.com/maitag/armory-3d-land/tree/main/mathTerm)
> adding a new "MathTerm"-node

- Sources/armory/logicnode/MathExpressionNode.hx
This fixes an error inside of formula-lib if build with the "no-inline" compiler define.
(<https://github.com/maitag/formula/commit/1a380a4a280d0525dbd8dca706979877252f7719>)
> upgrading to formulalib 0.43

- blender/arm/write_data.py
The following lines were added even when there is no scene canvas, debugging disabled, and ZUI disabled --
armory.ui.Canvas.imageScaleQuality = kha.graphics2.ImageScaleQuality.Low;  
causing Type not found : zui.Zui
> Allow building with ZUI disabled

- blender/arm/logicnode/array/LN_array_float.py
- blender/arm/logicnode/logic/LN_gate.py
Both nodes had wrong out-of-range checks for version numbers, the Gate node did update to an old version, and the Array Float node did not copy any input sockets.
> Fix node update routines for Gate and Array Float nodes

- Sources/armory/trait/internal/CanvasScript.hx
- Sources/armory/ui/Canvas.hx
Previously, hiding a canvas with `CanvasScript.setCanvasVisibility()` would hide all canvas elements individually which would overwrite all configured element "visibilities". So if parts of the UI were hidden and then the entire canvas was hidden, the custom visibility configuration would have to be done again after the canvas was made visible again. Now, there is a dedicated attribute for canvases that doesn't touch element state.
Also, I guess the new approach can make a performance difference if you have tens of thousands of UI elements, for whatever reason ¯\_(ツ)_/¯
> Add TCanvas.visible attribute to hide entire canvas

- Sources/armory/logicnode/CrowdGoToLocationNode.hx
- Sources/armory/system/Starter.hx
- Sources/armory/trait/NavCrowd.hx
- Sources/armory/trait/NavMesh.hx
- Sources/armory/trait/NavObstacle.hx
- Sources/armory/trait/navigation/DebugDrawHelper.hx
- Sources/armory/trait/navigation/Navigation.hx
- blender/arm/logicnode/navmesh/LN_crowd_go_to_location.py
- blender/arm/props_traits.py
- blender/arm/write_data.py
This PR is a complete overhaul of the recast navigation system that solves a few issues and introduces many new features.
The navigation mesh is generated at runtime unlike before, where it had to be exported as an `.obj` file and then created from from file. The new version creates the navigation mesh with object geometry info from iron. This also comes with an option to include immediate child meshes into the navmesh build.
Previously, the `NavAgents` would not have any awareness of the other agents. This caused agents to not collide with each other and intersect. The newly implemented crowds system solves this issue. Now the `NavCrowd` agents will be aware of the neighbors and try to remain separated while navigating to the goal. This does not remove the `NavAgent` trait. It is still …
> Recast Navigation System Overhaul

- blender/arm/material/make_finalize.py
- blender/arm/material/make_mesh.py
The proper normal matrix was not used when billboarding was enabled. This caused lighting to be fixed even when the objects rotated and was not visually correct. This PR fixes this issue by using the corrected normal matrix.
Requires https://github.com/armory3d/iron/pull/200
> Use billboard corrected normal matrix

- Sources/armory/logicnode/HideActiveCanvas.hx
- blender/arm/logicnode/canvas/LN_HideActiveCanvas.py
This node hides and unhides the whole active canvas not just certain elements of the canvas. Thus users can easily enable and disable menus for example. I also highly suggest that the LN_set_canvas_visible and LN_get_canvas_visible node are renamed into something like canvas_element_visible. As the node does not actually set the whole canvas visible just parts of it.
> added a new logic node called HideActiveCanvas

- Sources/armory/logicnode/RegularExpressionNode.hx
- blender/arm/logicnode/miscellaneous/LN_regular_expression.py
This node allows regular expression: match (if true it also returns matched patterns),  split and replace. By using regular expressions instead of strings it brings a flexible way of dealing with cases when this kind of operations require some level of flexibility.  
I added some usage documentation in the logic node description.
> Logic node for regular expression

- Sources/armory/renderpath/Inc.hx
The Armory UI allows for shadow map sizes up to 32768, but the corresponding Haxe code didn't. Thanks to @ TriVoxel on Discord for reporting this :)
> Fix compilation when using shadow map atlas of size 32768

- Sources/armory/logicnode/WorldToScreenSpaceNode.hx
- blender/arm/logicnode/math/LN_world_to_screen_space.py
I usually use this node with Raycast and Draw nodes, but not always with the active camera. The actual node by default only uses the active camera always. I propose to add a property to choose between the **Active Camera** and a **Selected Camera**. This property is set to **Active Camera** by default, so unless its value is changed it will continue to produce the same result as the actual node, but it will allow to use a different camera if needed.
> World to Screen Space: Camera option

- blender/arm/make.py
So far there was no way to see the reason why launching the player command failed. The command mentioned in the warning message is already printed in `run_proc()`, so there is no extra print statement in the added code.
> Print exception if player cannot be started

- Sources/armory/network/WebSocket.hx
Recent changes to PCRE need to be investigated to find out the cause of matched index outside bounds caused by the regex matches.
> Update WebSocket and replace Regex

- blender/arm/props_traits.py
- blender/arm/props_ui.py
This is my first attempt to modify armory ui. I appreciate comments if you notice something is missing or it could be improved. I did my best with what I know.
I added an operator that removes all traits from active objects: 
Additionally I added to the operator **Print All Scenes Traits** the information of the Scene traits (@ rpaladin, I hope you find this ok). Before it only printed the object traits.
> Armory Traits UI: Remove Traits and Print Scene Traits

- blender/arm/props_traits.py
Originally mentioned in my code review for #2971
Not quite sure why the PR was merged before the proposed change was implemented.
> Fix context for remove traits operator

- Sources/armory/logicnode/SetNameNode.hx
Currently the set name for armature objects loses the animation armature actions references when the armature name is changed. So for example play action node from stops working because the new armature name does not have any reference although is all the same with a different name. I added that part to the script in order to keep consistency.
The other alternative is not to allow the setName for armature objects, because there isn't a node that updates the animations armature actions reference.
> SetNameNode: update animation armature action references for armature name changes

- blender/arm/write_probes.py
The now replaced code was written when Cycles only supported CUDA or no GPU rendering at all, but now there are more options available (CUDA, OptiX, HIP, oneAPI)
> Enable GPU for environment rendering also for non-CUDA compute devices

- Sources/armory/logicnode/PlaySoundRawNode.hx
- blender/arm/logicnode/sound/LN_play_sound.py
By default the node will continue to be used as usual, but the option added will allow to specify a sound by a string name. This allows to parametrice the sounds with logic instead of having several sound nodes defined, very useful when having a lot of sounds. Additionally, sounds doesn't need to be imported to blender in order to be used by the sound node, as similar as the draw image node or the draw image sequence node, they just need to be in the Bundled folder.
> Play Sound Node: add option for sound/sound name

- Sources/armory/logicnode/GetDebugConsoleSettings.hx
- Sources/armory/logicnode/GetMouseStartedNode.hx
- Sources/armory/logicnode/MergedMouseNode.hx
- Sources/armory/trait/internal/DebugConsole.hx
- blender/arm/logicnode/input/LN_get_mouse_started.py
- blender/arm/logicnode/input/LN_mouse.py
- blender/arm/logicnode/miscellaneous/LN_get_debug_console_settings.py
This PR adds the debug console attribute `DebugConsole.isDebugConsoleHovered` that can be read to check whether the mouse was hovered over any debug console window in the last frame, e.g. to avoid interacting with the game when clicking on the debug console. The same attribute is available via the `Hovered` output of the `Get Debug Console Settings` node.
In addition to that, the mouse nodes now have a "shortcut" property that, if disabled (default), disables the nodes when the mouse is hovered over the console. Please let me know if you want the default to be the other way around. Nodes updated from older versions automatically enable this option to preserve the exact behaviour from before.
> Add DebugConsole.isDebugConsoleHovered (+ node integration)

- Sources/armory/logicnode/PlaySoundRawNode.hx
I missed these lines of code when sound is loaded again and retriggered.
Otherwise the node always plays the same initial sound even though the sound name is changed.
Sorry.
> Play sound node: fix sound load and retrigger

- blender/arm/material/make_mesh.py
Forward render paths (the "regular" one and mobile) didn't correctly handle two-sided materials. This also caused problems in projects using the deferred RP because translucent materials use forward rendering.
Thanks to @ BrahRah on Discord for the [report](https://discord.com/channels/486771218599510021/487613529990365184/1174777894631911535)!
Before (screenshot by @ BrahRah):
After:
> Fix rendering of two sided materials in some render paths

- blender/arm/make_world.py
This PR fixes a potential division by zero in the clouds shader code, which would result in INF/NaN values that in turn would cause white screen flickers when bloom was enabled.
I don't really like this solution because it is just a symptomatic fix (that probably causes branching) to make things work again. The actual problem is the code responsible for weather "dilation" which, if the cloud coverage goes to zero, approaches a dirac delta. Unfortunately, the papers and other sources I can find on this topic all skip over this little detail as if this wasn't a problem for them.
I experimented with other ways of simulating cloud coverage, and while the results looked at least acceptable, they were pretty different so I didn't think they were a good replacement for the current look. I also …
> Fix INF values in cloud shader (causing bloom flickering)

- Shaders/std/light.glsl
- blender/arm/material/make_cluster.py
- blender/arm/material/shader.py
There was some multiplication vector that you forgot to add to forward make_clusters.py
This breaks the clusters in forward, this pull request fixes it.
I also made the spotclusters array a mat4 since that's what it it. Just adding a clause in shaders.py allows it.
> Fix forward clusters

- Sources/armory/logicnode/NetworkHttpRequestNode.hx
- blender/arm/logicnode/network/LN_network_http_request.py
This PR refactors HTTP Request node. Fixes some incorrect indices used and exposes more options. Also introduced a `Callback Type` output indicating the type of callback at the `Out` output.
```
Callback Type: Type of output.
0 = Node Executed
1 = Status Callback
2 = Bytes Data Response Callback
3 = String Data Response Callback
4 = Error String Callback
```
Node now looks like:
**Usage**: May be used with `Select Output` Node to perform actions depending on callback type.
> Refactor HTTP Request Node

- blender/arm/write_data.py
Move assets for published html5 games to /data folder instead of keeping them in the project's root folder.
> Move assets for published html5 games to /data folder

- blender/arm/write_data.py
Following Kha's [wiki](https://github.com/Kode/Kha/wiki/HTML5#full-page-canvas), adds a define in `khafile.js` and customizes `Main.hx` if target is 'html5' and set to full-screen.
Fixes #2515
> Fix html5 canvas auto resize

- Sources/armory/system/Signal.hx
This adds a `Signal` class that works similarly to Godot's signals. This can be an alternative to the `Event` class for handling events that need arguments. Also helpful to maintain the code modular.
This is a first iteration but I plan to add new features if they are needed, for now I think it can be merged if you all think this is a good idea.
@luboslenco @QuantumCoderQC @MoritzBrueckner @Onek8
> Add Signals

- Sources/armory/logicnode/ScreenToWorldSpaceNode.hx
- blender/arm/logicnode/math/LN_screen_to_world_space.py
Previous version of the node retrieved origin (label as world) and direction and they needed to be combined in order to get the desired coordinated. Which until now I didn't know how to use it to get the right world position. Since ray class has a function name "At" that does that, i think is better to output this result for a simple way of using this node.
I also added basic description which explains vector "At" considers the "Origin" point where the ray is emitted from the camera and uses "Distance at" to multiply its "Direction". 
Here is a sample of the same cube spawn at different screen positions with different distance at values using the node:
> Screen Space Node: add result vector position At

- Sources/armory/logicnode/ColorMixNode.hx
- blender/arm/logicnode/math/LN_color_mix.py
Color mix node using spectral mix allows to combine colors in a more natural way.
Mix factor ranges from 0 to 1.
Here are some color examples gradients drawed from armory using the node:
> Color Mix Node

- Sources/armory/logicnode/DrawPolygonFromArrayNode.hx
- blender/arm/logicnode/draw/LN_draw_polygon_from_array.py
This draw node draws a polygon from an array containing all vertices positions. The array input allows to dynamically change the vertices counts which was not possible with the existing version (Draw Polygon Node).
> Draw Polygon From Array Node

- Sources/armory/logicnode/PlayActionFromNode.hx
- blender/arm/logicnode/animation/LN_play_action_from.py
This one was a long due. I finally managed to fix the problem with the Reverse option for the boneAnimation Actions. Previous logic only worked for bones without parents. Now all the armature is reverse as expected.
Besides that, I also fixed another problem regarding the start and end frames for an action, that according to discord, i wasn't working either for all the cases. 
Considering Actions and keyframes from blender, all animation track frames range from 0 to length-1. So when using the PlayActionFromNode, those are the ranges to use. Previous version of start-end frames was been executed because the condition from frame end was never met using the wrong end frame index. Besides, if the action was changed triggered by another PlayActionFromNode, the previous update function that …
> Fixes for Play Action From Node

- Sources/armory/logicnode/GetObjectGeomNode.hx
- blender/arm/exporter.py
- blender/arm/logicnode/object/LN_get_object_geom.py
This node allows to retrieve the object geometry information and the vertex groups (positions and names).
For example using vertex groups (for instancing geometry or drawing geometry) in vertex positions and edges of an object (mesh curve):
Here are some examples in 3D geometry with vertices and normals:
Face Normals and other vectors can be calculated using the previous outputs.
#3017 
requires iron [#218](https://github.com/armory3d/iron/pull/218)
> Get Object Geometry Node

- blender/arm/nodes_logic.py
When adding a node group an error pops up and the node group is not added even though it exists because an array index setting is missing.
Error: Python: Traceback (most recent call last):
File "D:\Armory3D\armsdk/armory\blender\arm\nodes_logic.py", line 112, in invoke
bpy.ops.node.add_node('INVOKE_DEFAULT', type=self.type, use_transform=self.use_transform, settings=setting_dicts)
File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\bpy\ops.py", line 111, in __call__
ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
TypeError: Converting py args to operator properties:  NODE_OT_add_node.settings error converting a member of a collection from a dicts into an RNA collection, failed with: TypeError: Converting a Python list to an RNA collection: keyword …
> Fixes add node group error

- blender/arm/material/make_decal.py
Decal material example does not work anymore or any decal material because this declaration is missing
> DecalMaterials: fix ior declaration missing

- Sources/armory/trait/physics/bullet/PhysicsHook.hx
Hooks are not working for Softbody and Cloth. This PR solves the issue in order for the hooks to work as expected. For example in the physics constraints file, for Cloth vertex group pinned now Cloth does not fall.
> Fix: Softbody and Cloth Hooks

- armory/Sources/armory/trait/internal/DebugConsole.hx
> DebugConsole: add uid and collections

- armory/blender/arm/nodes_logic.py
This links don't work since the update in the repository:
> fix open node links

- armory/Sources/armory/logicnode/SubStringNode.hx
This causes an error when compiling to windows c:
`armsdk\armory\Sources/armory/logicnode/SubStringNode.hx:13: characters 16-20 : On static platforms, null can’t be used as basic type Int`
Start and end can never be null since they are by default 0 in the node.
> fix SubStringNode

- armory/Sources/armory/ui/Canvas.hx
This fixes historial error of canvas text area element.
Now it can be used.
I added a note because handle is not implemented in the text area function.
> fix text area element from canvas

- armory/Sources/armory/logicnode/DrawCameraNode.hx
Fix for html5: the image of the camera is inverted.
Added support for moving camera: now (x, y) are updated.
For example, the camera draw can move along a character position on screen.
> DrawCameraNode updates

- armory/Sources/armory/logicnode/OnTimerNode.hx
On Timer Node:
-- if repeat is set to false it just does one iteration
-- if repeat is set to true it repeats iterations
-- if repeat is changed from true to false during runtime it stops from doing new iterations
-- but if repeat is changed from false to true during runtime it does not continue to do new iterations
I modified the node with a reactivation function so in that case it can continue to do new iterations.
I think that way is more consistent.
> OnTimerNode: add false to true case

- armory/Shaders/deferred_light/deferred_light.frag.glsl
Variable `LWVPSpot0` does not exist so it causes error. The correct sintaxis is `LWVPSpot[0]`
> fix error deferred_light.frag.glsl: variable LWVPSpot0

- armory/Sources/armory/logicnode/RotationFromTransformNode.hx
- armory/blender/arm/logicnode/transform/LN_transform_to_rotation.py
this node allows to get the rotation matrix of an object transform.
This is useful when retrieving the vertex positions of a geometry to get the actual rotation of the vertices.
> Rotation matrix node

- armory/Sources/armory/logicnode/SensorCoordsNode.hx
- armory/blender/arm/logicnode/input/LN_sensor_coords.py
I added a simple description (previous was TODO) an labeled the sensor output to accelerometer.
I also added gyroscope and device orientation outputs and html5 targets in order for the node to not cause errors.
> SensorCoords node upgrade

- armory/Sources/armory/logicnode/ReadFileNode.hx
- armory/Sources/armory/logicnode/ReadJsonNode.hx
- armory/Sources/armory/logicnode/WriteFileNode.hx
- armory/Sources/armory/logicnode/WriteJsonNode.hx
- armory/blender/arm/logicnode/native/LN_read_file.py
- armory/blender/arm/logicnode/native/LN_read_json.py
- armory/blender/arm/logicnode/native/LN_write_file.py
- armory/blender/arm/logicnode/native/LN_write_json.py
I added `Output` workflow for `write nodes`.
I added` Not Loaded` output for the case the file doesn't exist so the workflow can continue.
> ReadWriteNodes: add outputs

- armory/Sources/armory/logicnode/AlertNode.hx
- armory/Sources/armory/logicnode/ConfirmNode.hx
- armory/Sources/armory/logicnode/PromptNode.hx
- armory/blender/arm/logicnode/native/LN_alert.py
- armory/blender/arm/logicnode/native/LN_confirm.py
- armory/blender/arm/logicnode/native/LN_prompt.py
Basic nodes for html5 messages and interaction:
I thought these 3 elements could help in a basic way for based game behavior or debugging because: 
- `Alert` shows a message as an ui does (for people who don't know how to get to the console).
- `Prompt` helps to retrieve an user input by keyboard (which is useful in devices that don't have any).
- `Confirm` has a yes or no decision worflow  (interaction with user).
> Html5 Alert, Prompt and Confirm nodes

- armory/Sources/armory/logicnode/GetBoneTransformNode.hx
Get Bone Transform works well if only 1 instance of an armature is spawned in the scene. But with 2 or more instances of the armature the Transform returned is not consistent with the action played by that instance at that point.
This PR fixes that so the correct Transform is returned for every instance of an armature.
I finally could solve this problem I got long time ago with this node.
> Fix GetBoneTransformNode: incorrect transform returned

- armory/blender/arm/exporter.py
This approach selects all the cameras when the project is exported, so the proper matrix is built for each one. Closes #3131.
> Fix camera spawn position in Blender 4.2.x

- armory/blender/arm/material/cycles_functions.py
- armory/blender/arm/material/cycles_nodes/nodes_texture.py
`Fac Output` failed for `FBM` because `tex_musgrave` function was missing for 4.
I added commented params of detail and distortion to the musgrave function so now the node looks like in blender:
Now Brick texture looks exactly like in blender:
> Update Texture nodes: Musgrave, Noise and Bricks

- armory/blender/arm/nodes_logic.py
These node were not registering in later versions of blender.
Thanks @Onek8 for the modification
> Custom Nodes missing in blender 4.

- armory/Sources/armory/logicnode/DrawSubImageNode.hx
- armory/Sources/armory/logicnode/WriteImageNode.hx
- armory/Sources/iron/format/bmp/Data.hx
- armory/Sources/iron/format/bmp/Reader.hx
- armory/Sources/iron/format/bmp/Tools.hx
- armory/Sources/iron/format/bmp/Writer.hx
- armory/blender/arm/logicnode/draw/LN_draw_sub_image.py
- armory/blender/arm/logicnode/native/LN_write_image.py
`Write Image Node` : allows to take a snapshot of a camera and export it as an image file (supports sub image). Uses format/bmp for image formatting. Works for krom and html5. This was a hard one to get done.
`Draw Sub Image Node`: draws a sub image which is a section of the image. So for example the same image can be used showing different sections of the image or you by making some animation like zooming in or moving along the image.
> New Image nodes: Draw Sub Image and Write Image

- armory/Sources/armory/trait/physics/bullet/PhysicsWorld.hx
- armory/Sources/iron/App.hx
- armory/Sources/iron/Trait.hx
- armory/Sources/iron/system/Time.hx
This adds fixedUpdate to call physics logic from traits with fixed time steps. This keeps the physics running at the same speed regardless of the game's framerate. This doesn't have interpolation yet.
> Add fixedUpdate for Physics

- armory/blender/arm/make_renderpath.py
- armory/blender/arm/props.py
- armory/blender/arm/props_ui.py
Both texture use was confusing because it was a world property under a light menu section. And only 1 texture can be used in a world, which can have different lights and all of them uses the same texture. 
Besides, the name of the texture which can not be changed was not visible for reference.
The property was defined as a string but was used as a boolean.
I also modified the world reference: is always using worlds['Arm'] instead of get_active_scene().world (context world or play/export scene config world).
> Ies Texture and Cloud Texture: improvements

- armory/blender/arm/make_renderpath.py
- armory/blender/arm/write_data.py
Exposure setting was `bpy.data.scenes[0]` pointing always to scene 0 disregarding context scene or play or export scene options so I changed to `arm.utils.get_active_scene()`
The same happens a lot for `bpy.data.worlds['Arm']` is hardcoded world instead of using `arm.utils.get_active_scene().world`. 
@luboslenco is that ok?
> fix scene exposure setting

- armory/Sources/armory/logicnode/GetFPSNode.hx
- armory/Sources/iron/object/Animation.hx
- armory/Sources/iron/object/ParticleSystem.hx
- armory/Sources/iron/object/Tilesheet.hx
Depends on #3165 where `iron.system.Time.delta` is properly calculated.
- fix to call animation markers from skipped frames
- use `delta` instead of `realDelta`
> Framerate and delta fixes

- armory/blender/arm/write_data.py
there were still a missing error in bloom regarding using blender settings field.
> Fix Bloom error for 4.3 

- armory/Sources/armory/logicnode/SetMaterialTextureFilterNode.hx
- armory/blender/arm/logicnode/material/LN_set_object_material_filter_texture.py
- armory/blender/arm/props_renderpath.py
I added a node for changing image texture interpolation:
I also modified the texture filtering names and order to match according the image texture (anisotropic to smart)
A possible addition later could be a property in the node for changing all the image texture at once or just the selected one (simil to the texture filtering in the renderer. And a get texture filter node.
> add material texture filter node

- armory/Sources/armory/logicnode/GetWorldNode.hx
- armory/Sources/armory/logicnode/GetWorldOrientationNode.hx
- armory/Sources/armory/logicnode/SetWorldNode.hx
- armory/blender/arm/logicnode/transform/LN_get_world_orientation.py
- armory/blender/arm/logicnode/world/LN_get_world.py
- armory/blender/arm/logicnode/world/LN_set_world.py
- armory/blender/arm/make_world.py
These nodes allow to change the world scene at runtime.
I had to modify the name of the get world orientation node because it was called "get world" but only in the haxe file.
I also modified the world export: so now worlds that have a fake user or are associated to scenes are exported (excluding 'Arm'). So there is no need to have an empty scene just to export the world.
This was a hard one to get. Finally I can add this to the rest of the world nodes that I've made.
> Set/get World Node

- armory/blender/arm/exporter.py
Thanks @moisesjpelaez for spotting the error.
> fix export particle options: children object particle data not found

- armory/Sources/armory/logicnode/SetLightShadowNode.hx
- armory/blender/arm/logicnode/light/LN_set_light_shadow.py
Introduces SetLightShadowNode in both Haxe and Python to allow toggling the shadow property of a light object via logic nodes. This enables users to programmatically enable or disable shadows on lights within the logic node system.
> Add SetLightShadowNode for controlling light shadows

- armory/Sources/iron/RenderPath.hx
- armory/Sources/iron/object/CameraObject.hx
- armory/Sources/iron/object/LightObject.hx
- armory/Sources/iron/system/VR.hx
Actual code of VR fails:
I think it is best to restore the old code which at least works:
If not then let's disable the VR option.
> Restore VR code

- armory/blender/arm/props.py
Fix attribute error for blender 4. above.
```
    if rp.rp_gi != 'Off':
       ^^^^^^^^
AttributeError: 'ArmRPListItem' object has no attribute 'rp_gi'. Did you mean: 'rp_pp'?
```
> fix attribute error rp_gi

- armory/Sources/iron/RenderPath.hx
- armory/Sources/iron/data/SceneFormat.hx
- armory/Sources/iron/data/ShaderData.hx
- armory/Sources/iron/object/MeshObject.hx
- armory/blender/arm/exporter.py
- armory/blender/arm/material/make_mesh.py
- armory/blender/arm/material/shader.py
- armory/blender/arm/props.py
- armory/blender/arm/props_ui.py
Changes:
- exposed `Compare Mode`
- exposed `Write Depth`
- added `Sorting Order` so when `Render - Renderer - Draw Order` is set to `Shader`, they get sorted by index instead of by name
- added `Next Pass`, this draws before the main pass
With these changes, effects making objects to be seen behind walls can be achieved easily, without having to write custom shaders. Also `Render - Renderer - Ovelays` and `Material - Armory Props - Overlay` may not be needed, since the overlay can be achieved with `Material - Armory Props - Compare Mode - Always`.
> General Material updates

- armory/Sources/armory/system/Starter.hx
- armory/Sources/iron/RenderPath.hx
- armory/Sources/iron/data/MeshData.hx
- armory/Sources/iron/data/SceneFormat.hx
- armory/Sources/iron/data/ShaderData.hx
- armory/blender/arm/exporter.py
- armory/blender/arm/exporter_opt.py
- armory/blender/arm/material/shader.py
- armory/blender/arm/props.py
- armory/blender/arm/props_renderpath.py
- armory/blender/arm/props_ui.py
- armory/blender/arm/write_data.py
- workaround to fix UV coordinates for linked materials when `Render - Armory Exporter - Optimize Data` is enabled
- move `sorting_order` from materials/shaders to `sorting_index` to mesh objects, since RenderPath sort meshes and not materials
- sort mesh objects by name if they have the same index
- changed `Render - Armory Render Path - DrawOrder - Shader` to `Render - Armory Render Path - DrawOrder - Index`
Thanks to @t3du for the insight.
> General fixes

- armory/Sources/armory/logicnode/SetWorldNode.hx
- armory/blender/arm/logicnode/world/LN_set_world.py
- armory/blender/arm/make_renderpath.py
- I removed the validation in the setWorld node because it did not work on html5 even though the world did exist. So I moved the assert message to the node description.
- I added a condition so scenes without worlds can compile if there is only one scene or is the scene set in the launch properties.
> fix world errors

- armory/Sources/armory/logicnode/ShutdownNode.hx
ShutdownNode has the output in the node definition but not in the haxe code.
Turns out it really triggers the nodes after it when in windows.
> shutdown node

- armory/blender/arm/make.py
Fixes:
- reload all linked libraries on build to get their most recent changes without needing to restart Blender
- fully clean up external blends from the `Libraries` outliner
> More linked assets fixes

- armory/Sources/armory/logicnode/SetFirstPersonControllerNode.hx
- armory/Sources/armory/logicnode/SetOverheadPersonControllerNode.hx
- armory/Sources/armory/trait/FirstPersonController.hx
- armory/Sources/armory/trait/OverheadPersonController.hx
- armory/blender/arm/logicnode/object/LN_set_overhead_person_controller_settings.py
This PR includes the bundle OverheadPersonController plus the LN which is similar to FPController, but "overheadCamera" to control the rotation of the "character" with the position of the mouse. 
example 
https://obinowankenobi.github.io/OverheadPersonController01.github.io
Press (v) to desable walk, jump, run and smoothTrack. (b) to reset
> OverheadPersonController and minors changes

- armory/blender/arm/props_ui.py
Linked scenes are added during build process. With this fix all of these scenes get deleted if the user for some reason hits "stop" during this process.
> Clear linked scenes from blend file when build process gets interrupted
