blender/arm/props_ui.py
Solves this: https://github.com/armory3d/armory/issues/273
=> added patch project button

blender/arm/make.py, blender/arm/props_ui.py
Still need to copy assets though without regenerating project files.
=> Fixed project patching.

blender/arm/exporter.py, blender/arm/utils.py
Added type of props displayed in Blender as: prop(Type). If type is String, auto add quotes in exporter.
=> Upgrade props

Sources/armory/trait/physics/bullet/RigidBody.hx, Sources/armory/trait/physics/oimo/RigidBody.hx
Bullet physics implemented and working fine.
Oimo TODO..
=> RigidBody.setFriction(f), change friction during runtime

.travis.yml, blender/arm/exporter_gp.py, blender/arm/exporter_sdf.py, blender/arm/node_utils.py
I have taken this one as far as I can but would need help to complete it.
The four issues that remain should be looked at:
* https://travis-ci.org/armory3d/armory/jobs/310544629#L561-L573
=> Add flake8 tests in Python 2.7 and 3.6

Sources/armory/trait/SimpleRotateObject.hx
Simple script to rotate an object around using the keyboard with RT(x), FG(y), VB(z).
Can be used for testing and debuging.
=> Bundled trait: simple rotate object

Sources/armory/trait/physics/bullet/RigidBody.hx
Only merge once https://github.com/kripken/ammo.js/pull/180 has been merged, and ammo.js has been rebuilt.
=> Enable Bullet.updateSingleAabb (needs updated ammo.js)

Sources/armory/trait/physics/bullet/RigidBody.hx
=> RigidBody enableGravity(), disableGravity(), setGravity(v:Vec4)

Sources/armory/trait/physics/bullet/PhysicsWorld.hx
Needs https://github.com/armory3d/haxebullet/pull/15
=> Enable removeKinematicCharacterController()

Sources/armory/trait/internal/DebugConsole.hx
Dependency: https://github.com/armory3d/iron/pull/28
=> Debug console use custom math class, round object positions with two decimals

blender/arm/exporter.py, blender/arm/props.py, blender/arm/props_ui.py
Fixes issue: http://forums.armory3d.org/t/sound-playing-when-program-launches/621
=> Speaker "play on start" property

Sources/armory/renderpath/RenderPathDeferred.hx, Sources/armory/renderpath/RenderPathForward.hx
Fix for [https://github.com/armory3d/armory/issues/497
](https://github.com/armory3d/armory/issues/497
)Opacity should work now with the fix
=> Fix for #497

Sources/armory/logicnode/TranslateOnLocalAxisNode.hx, blender/arm/logicnode/action_translate_on_local_axis.py
I hope I did everything right, would be a first if I managed it on first try 🙂 
Trying to add this node to main armory, since it is really necessary and annoying to live without. Tell me if I should try to add some other nodes from logic_pack, thinking about "Inverse" and "To Bool", since they are general purpose and really handy to have.
=> Move on local axis node

blender/arm/logicnode/logic_gate.py
Found the solution easily after a good night's sleep
=> Gate Node: Remove extra inputs when no longer on "Or" or "And"

Sources/armory/trait/NavAgent.hx
=> NavAgent: faster is faster

.gitignore, Sources/armory/logicnode/ApplyImpulseNodeAtLocation.hx, Sources/armory/logicnode/GetVelocityNode.hx, Sources/armory/logicnode/VectorClampToSizeNode.hx, Sources/armory/logicnode/VectorMathNode.hx, Sources/armory/trait/physics/bullet/RigidBody.hx, blender/arm/logicnode/physics_apply_impulse_at_location.py, blender/arm/logicnode/physics_get_velocity.py, blender/arm/logicnode/value_vector_clamp_to_size.py, blender/arm/logicnode/value_vector_math.py
@luboslenco theres a few bits in here which may not be ideal? maybe I need to split this into multiple PR's
I added Length to the VectorMath node (straight forward)
I needed a GetVelocity node which led me a little deeper into rigidbody.hx I saw a comment that it was not compiling, for me on macOS it is fine. On this node I think I should out in a extra check to make sure the rb is valid..
Also a new ApplyImpulseAtLocation node as I saw people asking for it.
Finally a VectorClampToSize node (using it to limit velocity on a rigidbody) BUT it requires updated Vec2,3 and 4 in Iron (will submit seperate PR for that)
Anyway, hope this is OK this way let me know
=> Adding some new nodes and length() to VectorMath node

Sources/armory/logicnode/GateNode.hx, blender/arm/logicnode/logic_gate.py
Really handy, makes needed node count in tree smaller -> easier to use.
=> "Gate" node with else output

blender/arm/make_logic.py
Fix for #595  
Support for orphaned REROUTE nodes.
=> Orphaned REROUTE now behaves appropriately

Sources/armory/logicnode/ApplyForceAtLocationNode.hx, Sources/armory/logicnode/ApplyForceNode.hx, Sources/armory/trait/physics/bullet/RigidBody.hx, blender/arm/logicnode/physics_apply_force.py, blender/arm/logicnode/physics_apply_force_at_location.py
Think it would be good to add a global/local bool?
Also needs haxebullet PR
https://github.com/armory3d/haxebullet/pull/21
=> Add ApplyForceNodes

Sources/armory/logicnode/GetGravityNode.hx, Sources/armory/logicnode/MaterialNode.hx, Sources/armory/logicnode/SetGravityNode.hx, Sources/armory/logicnode/TraitNode.hx, blender/arm/logicnode/physics_get_gravity.py, blender/arm/logicnode/physics_set_gravity.py
The Trait node is still not actually returning a trait but with this you can still build/play with the node in the logic tree.
Also added Get and Set Gravity Nodes
=> Stop Trait Node stopping compilation & Get/Set Gravity Nodes

Sources/armory/logicnode/MixNode.hx, Sources/armory/logicnode/VectorMixNode.hx
They were using wrong property for clamp, also changed to use Math.clamp()
=> Little fix for Mix Nodes

Sources/armory/logicnode/ConcatenateStringNode.hx, blender/arm/logicnode/concatenate_string.py
Helps a bit for UI/logging etc.
=> Add Concatenate String Node

Sources/armory/logicnode/SwitchNode.hx, blender/arm/logicnode/arm_nodes.py, blender/arm/logicnode/logic_switch.py
Addresses the Switch Node feature request from issue #771
Some arm_nodes.py bits could be consolidated. Will address later.
=> SwitchNode

blender/arm/logicnode/arm_nodes.py
Change the node colour of array to orange
=> Array node colour change

blender/arm/material/cycles.py
This little change makes the CombineHSV work.
=> Make Combine HSV work

Sources/armory/logicnode/OnTimerNode.hx, blender/arm/logicnode/event_on_timer.py
Hello,
this is my version of onTimer node I worked on according requests here:
[https://github.com/armory3d/armory/issues/612](https://github.com/armory3d/armory/issues/612)
The node require a new approach different from the actual one, you need to attach a onInit or onUpdate event to it or something else.
In this image you can find three way I used it to test it: a normal one, one node activating another one, pausing the node with left click.
C&C are welcome.
Thank you for your time.
M
=> new onTimer node as requested on #612

Sources/armory/logicnode/SetGravityEnabledNode.hx, blender/arm/logicnode/physics_set_gravity_enabled.py
Add a node that lets you enable or disable gravity for a specific object.
=> Add a "Set Gravity Enabled" Logic Node

blender/arm/nodes_logic.py
Small update for extra readability of node list. I meant to add this to my last PR, but it got merged 27 minutes before I pushed this change. :slightly_smiling_face:
=> Sort Logic Node List Alphabetically

blender/arm/exporter.py
=> [Python] Export a separated object for viewport camera

blender/arm/props_traits.py
The arrow buttons will move a item up or down #997
=> Change traits order #997

Sources/armory/logicnode/CastPhysicsRayNode.hx, Sources/armory/trait/physics/bullet/PhysicsWorld.hx, blender/arm/logicnode/physics_cast_physics_ray.py
Added hit normal to both Haxe and Logic Nodes.
=> Add Hit Normal to Physics Ray Cast Result

Sources/armory/logicnode/CastPhysicsRayNode.hx, Sources/armory/trait/PhysicsDrag.hx, Sources/armory/trait/VehicleBody.hx, Sources/armory/trait/physics/bullet/KinematicCharacterController.hx, Sources/armory/trait/physics/bullet/PhysicsConstraint.hx, Sources/armory/trait/physics/bullet/PhysicsHook.hx, Sources/armory/trait/physics/bullet/SoftBody.hx
Update the physics traits with the latest bullet bindings. The [Super Replace](https://marketplace.visualstudio.com/items?itemName=jebbs.super-replace#review-details) VSCode plugin was invaluable for this. :slightly_smiling_face:
=> Update Bullet Bindings for Physics Traits

blender/arm/exporter.py, blender/arm/props_traits.py, blender/arm/props_ui.py
=> Fix Node Trait Selection Issue

Sources/armory/logicnode/CanvasGetSliderNode.hx, Sources/armory/logicnode/CanvasSetSliderNode.hx, blender/arm/logicnode/canvas_get_slider.py, blender/arm/logicnode/canvas_set_slider.py
There are a couple of hackish Try/Catch blocks in here that I put in because it would crash and say that the handles didn't exist if they were accessed too early. I'm not sure if I'm doing something wrong or if that is just how it is at the moment.
=> Add Nodes for Getting and Setting Canvas Sliders

Sources/armory/logicnode/ArrayInArrayNode.hx, blender/arm/logicnode/array_in_array.py
http://forums.armory3d.org/t/remove-object-exept-if-its-in-the-list/2774/11?u=zicklag
=> Add an In Array Node

Sources/armory/logicnode/VectorMathNode.hx, blender/arm/logicnode/value_vector_math.py
=> Add a Distance Measurement to the Vector Math Node

Sources/armory/logicnode/ApplyForceNode.hx, Sources/armory/logicnode/ApplyImpulseNode.hx, Sources/armory/logicnode/TranslateObjectNode.hx, Sources/armory/logicnode/TranslateOnLocalAxisNode.hx, blender/arm/logicnode/action_translate_object.py, blender/arm/logicnode/physics_apply_force.py, blender/arm/logicnode/physics_apply_impulse.py
The title says it. The old Translate on Local axis node is now redundant I think, but maybe leave it in if so old project don't need to be changed. I touched it by mistake in this pull request, only added some lines tho so nothing happened.
=> "On Local Axis" option for Translate-, Impulse- and Force- nodes

blender/arm/nodes_logic.py, blender/arm/props_bake.py, blender/arm/props_exporter.py, blender/arm/props_lod.py, blender/arm/props_properties.py, blender/arm/props_renderpath.py, blender/arm/props_tilesheet.py, blender/arm/props_traits.py, blender/arm/props_traits_props.py, blender/arm/props_ui.py
https://github.com/armory3d/armory/issues/1228
=> update addon to latest blender api changes

blender/arm/props_ui.py
Forgot few fixes in last update 😅 , here it is
=> updating addon fixes

blender/arm/logicnode/input_gamepad_deprecated.py, blender/arm/logicnode/input_keyboard_deprecated.py, blender/arm/logicnode/input_mouse_deprecated.py, blender/arm/logicnode/input_surface_deprecated.py, blender/arm/logicnode/input_virtual_button_deprecated.py, blender/arm/nodes_logic.py, blender/arm/props.py
I added the replacement method to the init method so it is always run on startup.
I also added the required replacement rules.
Finally I readded the old nodes since they cannot be replaced if they are undefined...
This file contains one of each node (open it with an older version.
Upon opening it with this PR they should be replaced.
[test.zip](https://github.com/armory3d/armory/files/3131939/test.zip)
=> Autorun autoreplacer

issue_template.md
Help devs out by getting all the relevant information for a well formed issue.
Added request for description, expected result, actual result, steps to reproduce and tech specs in addition to the pre-existing request for a sample file.
=> Update issue template for better issue reports

Sources/armory/logicnode/RotateObjectAroundAxisNode.hx, blender/arm/logicnode/action_rotate_object_around_axis.py
Pretty much what the title says.
The transform class contains a method to rotate around an axis.
Now this can be used through logic nodes.
=> expose rotation around axis in nodes

blender/arm/write_data.py
=> gpu_dof.fstop  > dof.aperture_fstop

Sources/armory/logicnode/GetPropertyNode.hx, blender/arm/logicnode/value_get_property.py
Implement request from https://github.com/armory3d/armory/issues/1155
=> Return property name in Get Property node

blender/arm/exporter.py
Linked to https://github.com/armory3d/iron/pull/64
=> Add support for fcurves with constant interpolation

Shaders/chromatic_aberration_pass/chromatic_aberration_pass.frag.glsl, Shaders/chromatic_aberration_pass/chromatic_aberration_pass.json, Shaders/compositor_pass/compositor_pass.frag.glsl, Sources/armory/renderpath/RenderPathDeferred.hx, blender/arm/make_renderpath.py, blender/arm/props_renderpath.py, blender/arm/props_ui.py, blender/arm/write_data.py
I've been attempting at making the lens texture a bit more useful by making it usable as a lens dirt filter/mask:
Not entirely sure about the UI (text-input reveal), but I tried to make it minimally cluttering, also it might technically fit better together with the bloom shader, but at least it works for now, if you think it fits :)
=> Lens dirt masking + Chromatic Aberration

blender/arm/props_traits.py, blender/arm/utils.py
-Fixes errors with permissions when running over a new file that has not been saved, or missing SDK.
-Fixes Bundled traits props not working or showing up on a new file.
=> Navmesh update 2

blender/arm/logicnode/native_loadUrl.py
I am sorry for making many mistakes.
=> Correcting category mistakes

Sources/armory/logicnode/CanvasSetVisibleNode.hx, blender/arm/logicnode/canvas_set_visible.py
Python : canvas_set_visible.py
Haxe : CanvasSetVisibleNode.hx
Example : logic_canvas.blend
=> Canvas Set Visible

Sources/armory/logicnode/TimerNode.hx
http://forums.armory3d.org/t/timer-node-does-not-work-as-expected/3543
=> Output error correction

Sources/armory/logicnode/CanvasGetLocationNode.hx, Sources/armory/logicnode/CanvasGetPBNode.hx, Sources/armory/logicnode/CanvasGetRotationNode.hx, Sources/armory/logicnode/CanvasGetScaleNode.hx, Sources/armory/logicnode/CanvasSetPBNode.hx, Sources/armory/logicnode/CanvasSetRotationNode.hx, Sources/armory/logicnode/CanvasSetScaleNode.hx, blender/arm/logicnode/canvas_get_location.py, blender/arm/logicnode/canvas_get_pb.py, blender/arm/logicnode/canvas_get_rotation.py, blender/arm/logicnode/canvas_get_scale.py, blender/arm/logicnode/canvas_set_pb.py, blender/arm/logicnode/canvas_set_rotation.py, blender/arm/logicnode/canvas_set_scale.py
(Canvas set location node already existed)
=> Adds canvas element get/set location, rotation, scale and progress bar nodes

blender/arm/exporter.py
Previously, the exporter exported triangles directly (l. 1086) and triangulated polygons (l. 1091). To triangulate polygons, it used the last loop of the polygon and "connected" it to all the other loops in the polygon (first + j, first + j +1). This is probably not what blender does internally.
However blender provides access to the triangles it creates through the loop triangles. By mapping the polygon indices to these triangles, it is possible to just export all loop triangles belonging to a polygon.
As for performance, I guess the biggest impact will come from `exportMesh.calc_loop_triangles()` or the iteration over the loop_triangles.
Testing with a landscape of 256*256 vertices (ant landscape addon), calc loop_triangles uses 0.9 ms of a total of 0.85 s export time for this mesh. …
=> change the exporter to use blenders triangle loops

blender/arm/utils.py
- Project folder was opened twice on windows and mac
- On windows, the parent folder was opened instead with the project folder selected
=> Fix open_folder() method

Sources/armory/logicnode/ReadFileNode.hx, Sources/armory/logicnode/ReadJsonNode.hx, blender/arm/logicnode/native_read_file.py, blender/arm/logicnode/native_read_json.py
Added a checkbox for setting whether to use cache for "Read JSON" and "Read File" logic nodes.
=> fix https://github.com/armory3d/armory/issues/1438

Sources/armory/logicnode/GetRotationNode.hx
fixes http://forums.armory3d.org/t/bug-in-get-rotation-method/3691
=> corrected indices in getRotation node

Sources/armory/trait/physics/bullet/RigidBody.hx, blender/arm/exporter.py
Mass of Animated(Kinematic) and Static objects will be set to zero. Implemented btMotionState for kinematic rigid bodies. And btSetWorldTransform for Dynamic and static rigid bodies. Kinematic rigid bodies can now be fully controlled through the animation timeline inside Blender.
=> Implemented Kinematic and Static flags for better control.

Sources/armory/logicnode/TransformMathNode.hx, blender/arm/logicnode/value_transform_math.py
When changing the location information alone, Get (Set) Location is simple. For other calculations, direct calculation of transform information is simpler.
=> Calculate transform data directly

Sources/armory/trait/physics/bullet/RigidBody.hx, blender/arm/exporter.py
PR 1 of  2
Should solve the broken Bullet in issues #1504   and #1461 
PR 2 at Haxebullet.
=> Moved kinematic and static flags from Bt.hx to RigidBody.hx

Sources/armory/trait/internal/CanvasScript.hx, blender/arm/exporter.py, blender/arm/utils.py
This PR is linked to https://github.com/armory3d/armory2d/pull/38 and requires https://github.com/armory3d/zui/pull/98 to be merged.
Old projects with no custom canvas are still compatible, the default theme is used if no theme was found :)
=> Load themes from canvas

blender/arm/material/cycles.py
this is a fix for an issue found in the https://github.com/armory3d/armory/issues/1413 issue report. 
See the comments on the issue for details.
=> Attempt to fix noise in opacity map

Sources/armory/trait/internal/DebugConsole.hx
Requires https://github.com/armory3d/iron/pull/77
- Improved outliner, alternating row colors and more visible parent relationships
- Added world transform information and reworked the transform view
- Slightly better traits display
- Some fixes
=> Debug console rework

blender/arm/exporter.py
Linked to https://github.com/armory3d/iron/pull/78
A happy new year to everyone :)
=> Export collection instance offsets

Sources/armory/trait/internal/CanvasScript.hx
and some dox string.
https://github.com/armory3d/armory/issues/1531
=> Add setCanvasFontSize

Sources/armory/trait/internal/DebugConsole.hx
This PR adds the ability to monitor trait attributes in the debug console. This makes it easier to debug traits as some potential debug print statements are not required anymore :)
Video: https://www.youtube.com/watch?v=XhJDXJ8M-so
=> DebugConsole: add trait detail view

Shaders/debug_draw/line.vert.glsl, Sources/armory/trait/internal/DebugDraw.hx
- Now lines should always face the camera.
- Changed some variable names to improve readability.
Fixes this https://github.com/armory3d/armory/issues/350
=> Fixed DebugDraw line drawing method 

Sources/armory/logicnode/GetWorldNode.hx, blender/arm/logicnode/value_get_world.py
https://forums.armory3d.org/t/3rd-person-camera-camera-orbit-problem/3915/
=> Handling issues posted on the Armory forum

blender/arm/make_logic.py
Solution for https://github.com/armory3d/armory/issues/1567. For detailed information see https://github.com/armory3d/armory/issues/1567#issuecomment-584287939.
=> Print warning if logic node tree and generated trait names differ

blender/arm/make.py
Fixes [#1564](https://github.com/armory3d/armory/issues/1564)
=> Fixed adding objects to collection 'export_coll' more than once

blender/arm/props_traits.py
The navmesh generation operator was still using the old trait property system.
Thanks to nubleet on Discord for reporting :)
=> Fix Navmesh generation + few code style improvements (pep8)

Sources/armory/trait/NavAgent.hx
=> Expose NavAgent turn speed to the UI

blender/arm/exporter.py
https://github.com/armory3d/iron/pull/82
=> Update exporter to fit expected new vertex array data

Sources/armory/trait/physics/bullet/RigidBody.hx
This fix should solve the following bug: #1574
=> Fixed Bullet RigidBody memory leak

Sources/armory/logicnode/DistanceNode.hx, Sources/armory/logicnode/TranslateObjectNode.hx, Sources/armory/logicnode/TranslateOnLocalAxisNode.hx, blender/arm/logicnode/value_distance.py
https://forums.armory3d.org/t/something-wrong-with-translate-on-local-axis/2772
https://forums.armory3d.org/t/how-to-avoid-camera-going-through-rigid-bodies/3945
=> Addressing issues reported in the Armory forum

Sources/armory/logicnode/PlayActionFromNode.hx, blender/arm/logicnode/animation_play_action_from.py
New node to start the animation from a set frame in the animation.
Works best with parameter `Blend` not zero.
=> Added node to start animation from a particular frame index

blender/arm/material/cycles.py, blender/arm/material/cycles_functions.py
I separated the basic procedural functions so each material only contains one of them, and added "const" at every parameter of a function.
=> Fix Procedural nodes not working on Forward path

blender/arm/material/cycles.py, blender/arm/material/cycles_functions.py
Fixed+Upgraded Voronoi texture. From the first two tabs only 3D and F1 are used, but all options from the third tab do work. Also takes all Inputs from Blender into account. Fixes #1568
=> Upgrade Voronoi Texture

blender/arm/material/cycles_functions.py
Realized that using a full noise function is unnecessary, a quick hash does the trick. Now at max FPS (~700) on a cube in an empty scene, before at 520. So the noise texture did hurt quite badly before...
=> Optimise Voronoi texture

Sources/armory/trait/physics/bullet/RigidBody.hx
=> Fixed Bullet Rigid Body C target issue

blender/arm/assets.py
Fix for warning 3 in https://github.com/armory3d/armory/issues/1636.
Thanks again to @knowledgenude for reporting this
=> Better asset name conflict detection + use log.warn() for warnings

Sources/armory/logicnode/HasContactArrayNode.hx, blender/arm/logicnode/physics_has_contact_array.py
This node was requested on issue #1256.
=> Add "Has contact (Array)" node

Sources/armory/logicnode/CanvasSetCheckBoxNode.hx, Sources/armory/logicnode/OnCanvasElementNode.hx, blender/arm/logicnode/canvas_set_checkbox.py, blender/arm/logicnode/input_on_canvas_element.py
Two new canvas nodes as requested at #1641 
1. Canvas node to set CheckBox value
2. OnCanvasElement Started, Released, and Down node.
Best Regards,
QC
=> Added set checkbox and OnCanvasElement Node

blender/arm/material/cycles.py
- The mapping node now supports input values from connected nodes, fixes https://github.com/armory3d/armory/issues/1515
- Rotations are now supported for all three axes
- Now `Point`, `Texture` and `Vector` mapping types are supported (only `Normal` is missing, I don't know exactly what it does)
The only issue that's still left is that the z location seems to be a tiny bit off sometimes (cannot reproduce it reliably) and for planes the rotation can be off too but that's probably because of the location issue. Anyway, the mapping node is now much more supported than before.
=> Refactor and fix mapping node

Sources/armory/logicnode/OnCanvasElementNode.hx
OnCanvasElement node now takes into account anchoring points. Now made the code more 'readable' thanks to @MoritzBrueckner.
=> OnCanvasElement node now takes into account anchoring points.

Sources/armory/logicnode/CanvasSetVisibleNode.hx
Related to https://github.com/armory3d/armory/issues/1659
=> CanvasSetVisibleNode: Fix exception when the element doesn't exist

blender/arm/write_data.py
Generate `Main.projectVersion` class field.
=> Generate Main.projectVersion

blender/arm/exporter.py
Requires https://github.com/armory3d/iron/pull/90
=> Particles: implement render emitter option & fix linked instance objects

Sources/armory/logicnode/OnCanvasElementNode.hx
=> Fixed issue where element is not visible

blender/arm/keymap.py
Fixes https://github.com/armory3d/armory/issues/1710. Thanks to @tong for reporting this.
=> Fix for running blender in background mode

blender/arm/exporter.py
Fixes https://github.com/armory3d/armory/issues/1720
=> Fix multi-usage of particle systems

Sources/armory/logicnode/VectorMathNode.hx, blender/arm/logicnode/value_vector_math.py
Was discussed in https://github.com/armory3d/armory/issues/1670.
=> Implement "reflect" operation for VectorMathNode

blender/arm/make_logic.py
I accidentally introduced a bug in https://github.com/armory3d/armory/pull/1728, this PR fixes it. Sorry about that, hopefully nobody found out in the meantime :D
=> Fix boolean node sockets

blender/arm/utils.py
Ignore invalid haxe module names.
=> Improve fetch script names

blender/arm/write_data.py
Add haxe `--times` param on `arm_verbose_output` not `arm_debug_console`
=> Add haxe --times flag on verbose not debug_console

Sources/armory/renderpath/Postprocess.hx
Using a switch statement here speeds up the call by ~ x5 on krom/html5.
=> Replace if conditions with switch

Sources/armory/logicnode/OnContactNode.hx
Fixed a nullpointer error that occured when the first given object has no rigid body trait.
=> Fix OnContactNode

blender/arm/utils.py
Thanks to greyherondev on Discord for reporting this
=> Fix fetching scripts from sub-packages

Sources/armory/trait/VehicleBody.hx, Sources/armory/trait/physics/bullet/RigidBody.hx
=> Use `bullet.Bt.CollisionObjectActivationState`

blender/arm/utils.py
=> Fixes wrong `rsplit` usages trying to discard file extensions

Sources/armory/logicnode/GetGravityNode.hx, Sources/armory/trait/physics/bullet/PhysicsWorld.hx, blender/arm/logicnode/physics_get_gravity.py
=> Add getGravity method. Fix getGravity logic node.

Sources/armory/logicnode/GetChildNode.hx
This solves issue #1845 . This PR can be merged if the changes mentioned are acceptable.
=> Re-Configure getChild node to search for immediate children only

blender/arm/material/make_mesh.py
=> Support for displacement in instanced objects

Sources/armory/logicnode/CanvasGetVisibleNode.hx, Sources/armory/logicnode/GetMouseLockNode.hx, Sources/armory/logicnode/GetMouseVisibleNode.hx, blender/arm/logicnode/action_set_visible.py, blender/arm/logicnode/canvas_get_visible.py, blender/arm/logicnode/value_get_mouse_lock.py, blender/arm/logicnode/value_get_mouse_visible.py
`Canvas Get Visible` -> is based in `Canvas Get Checkbox` and `On Canvas Element`. Needs review.
Test file: [canvas_get_visible.zip](https://github.com/armory3d/armory/files/5191484/canvas_get_visible.zip)
=> Canvas Get Visible , Get Mouse Lock and Get Mouse Visible

blender/arm/props_traits.py
Add buttons:
- New Node Tree – creates and sets a new Node Tree in the list;
- Edit Node Tree – loads the Node Tree selected from the list into all Logic Node Editor;
- From Node Tree – loops through all the working Logic Node Editor and from the last in the list sets the value to the list.
=> Blender UI – Armory Trait – Logic Node

blender/arm/make_logic.py
Fixes https://github.com/armory3d/armory/issues/1862.
This was introduced in https://github.com/armory3d/armory/pull/1860/commits/3a2952ced82b0dd343e39607ae5218f7e0350289.
=> Fix export of String and Object sockets

Sources/armory/logicnode/GetObjectOffscreenNode.hx, Sources/armory/logicnode/GetRigidBodyDataNode.hx, Sources/armory/logicnode/SetVisibleNode.hx, blender/arm/logicnode/object/LN_get_object_offscreen.py, blender/arm/logicnode/object/LN_get_visible.py, blender/arm/logicnode/object/LN_set_visible.py, blender/arm/logicnode/physics/LN_get_rigid_body_data.py
Original pull request: https://github.com/armory3d/armory/pull/1861
@knowledgenude asked to resolve the merge conflict and to create a new pull request, all credit belongs to them.
=> Some new nodes and improvements (by @knowledgenude )

blender/arm/nodes_logic.py
This prevents an error when trying to add a node without a logic tree.
=> Add poll() function to AddNodeOverride operator

Sources/armory/logicnode/OnSwipeNode.hx, blender/arm/logicnode/input/LN_on_swipe.py
The node for the swipe event (section "_Input_").
Input parameters:
- _Time_ - duration of the swipe (default value 0.15 s);
- _Min Length (px)_ - the minimum length that the swipe must “pass” (default value 100 px).
Output parameters:
- _Direction_ - normalized vector of the swipe direction;
- _Length (px)_ - the length of the swipe (to assess the “strength”);
The Length output parameter is calculated by the vector value (without normalization) to relate to the input value.
- _Angle (0-360_) - swipe angle in the range from 0 to 360 degrees (0 is on the right, i.e. Vector (1, 0) = 0 degrees).
- _States_ are states with direction output (Up, Down …). By default, they are not displayed, but if you press “Add 4 States”, then 4 states will appear (Up, Down, Left, Right) and if again, then 8 …
=> Logic Node - On Swipe

blender/arm/make_logic.py
Fixes https://github.com/armory3d/armory/issues/1870.
=> Fix export for sockets with no default value

Sources/armory/logicnode/OnTapScreen.hx, blender/arm/logicnode/input/LN_on_tap_screen.py
Input parameters:
- _Duration_ - time during which the number of touches is counted (default value is 0.3 seconds);
- _Interval_ - the time that must elapse between touches (default value is 0);
- _Repeat_ - the number of touches that need to be done to execute the event (default value is 2).
Output parameters:
- _Done_ - event for a successful completed action;
- _Fail_ - an event for a failed action;
- _Tap_ - event on each touch;
- _Tap Number_ - how many times the user has already touched the screen;
- _Coords_ - coordinates of the touch.
=> On Tap Screen - node for handling touches (double, triple…)

blender/arm/utils.py
This adds a simple Python context manager for handling calls to `os.chdir()`. This ensures that after the operation is done (or an exception happened) the current working directory is reset to where it was before.
So instead of
```python
os.chdir(new_cwd)
do_something()
os.chdir(prev_cwd)
```
we can now use 
```python
with WorkingDir(new_cwd):
do_something()
```
This PR also fixes a bug which made it impossible to execute a script in background mode from the console when the Armory addon was activated because the cwd was wrong.
There are still a lot of places where this context manager isn't used yet but utils.py is safe now and running Blender from background works again :)
=> Implement context manager for safer cwd changing

Sources/armory/logicnode/GetSystemName.hx, blender/arm/logicnode/native/LN_get_system_name.py
Section "_Native_".
Output parameters:
- _System Name_ - displays the system name as a string;
- _List systems_ for quick comparison.
=> Get System Name - to get the name of the system while the application is running

blender/arm/handlers.py
See https://github.com/armory3d/armory/issues/1820#issuecomment-699528410 for details. This change makes creating node libraries a bit more easy.
=> Automatically register new nodes and categories from libraries

Sources/armory/logicnode/OnSwipeNode.hx
Change the data type for the Direction output parameter from Vec3 to Vec4.
Otherwise, on the Android (C) platform, the application crashes.
=> Update logic node On Swipe

Sources/armory/logicnode/ArrayGetNode.hx, Sources/armory/logicnode/BloomGetNode.hx, Sources/armory/logicnode/CameraGetNode.hx, Sources/armory/logicnode/CanvasGetVisibleNode.hx, Sources/armory/logicnode/ChromaticAberrationGetNode.hx, Sources/armory/logicnode/ColorgradingGetGlobalNode.hx, Sources/armory/logicnode/ColorgradingGetHighlightNode.hx, Sources/armory/logicnode/ColorgradingGetMidtoneNode.hx, Sources/armory/logicnode/ColorgradingGetShadowNode.hx, Sources/armory/logicnode/GetCameraFovNode.hx, Sources/armory/logicnode/GetContactsNode.hx, Sources/armory/logicnode/GetCursorLocationNode.hx, Sources/armory/logicnode/GetCursorStateNode.hx, Sources/armory/logicnode/GetFirstContactNode.hx, Sources/armory/logicnode/GetGravityNode.hx, Sources/armory/logicnode/GetMouseMovementNode.hx, Sources/armory/logicnode/GetMouseVisibleNode.hx, Sources/armory/logicnode/GetObjectOffscreenNode.hx, Sources/armory/logicnode/GetRigidBodyDataNode.hx, Sources/armory/logicnode/GetRotationNode.hx, Sources/armory/logicnode/GetSystemName.hx, Sources/armory/logicnode/GetTouchLocationNode.hx, Sources/armory/logicnode/GetTouchMovementNode.hx, Sources/armory/logicnode/GetTraitNode.hx, Sources/armory/logicnode/GetVelocityNode.hx, Sources/armory/logicnode/GetVisibleNode.hx, Sources/armory/logicnode/GetWorldNode.hx, Sources/armory/logicnode/LenstextureGetNode.hx, Sources/armory/logicnode/SSAOGetNode.hx, Sources/armory/logicnode/SSRGetNode.hx
* Optimize some nodes
* Increase readability a bit
=> Logic nodes cleanups

blender/arm/logicnode/input/LN_on_tap_screen.py
=> Fix LN_on_tap_screen.py

blender/arm/logicnode/deprecated/LN_pause_trait.py, blender/arm/logicnode/deprecated/LN_play_action.py, blender/arm/logicnode/deprecated/LN_resume_action.py, blender/arm/logicnode/deprecated/LN_resume_trait.py, blender/arm/logicnode/deprecated/LN_set_object_material.py
Sorry to bother again, now everything was fixed (i hope)
=> Add accidentally removed labels

blender/arm/make.py, blender/arm/props_ui.py, blender/arm/utils.py
Requires https://github.com/armory3d/armsdk/pull/14
=> Add option to open build directory after sucessfully publishing

blender/arm/make_logic.py, blender/arm/props_traits.py, blender/arm/utils.py, blender/arm/write_data.py
This fixes the Armory part of https://github.com/armory3d/armory/issues/1937, however Zui still needs to set the correct values for `kha.graphics2.Graphics.fontGlyphs` depending on the language used.
=> Set file encoding to utf-8

blender/arm/make.py
Fixes https://github.com/armory3d/armory/issues/1939
=> Open correct folder after successful Android build

Sources/armory/logicnode/RandomChoiceNode.hx, Sources/armory/logicnode/RandomOutputNode.hx, blender/arm/logicnode/random/LN_random_choice.py, blender/arm/logicnode/random/LN_random_output.py
- **Random Choice**:
Choose a random value from a given array.
- **Random Output**:
Activate a random output when the input is activated.
=> Two new logic nodes for the "Random" category

Sources/armory/logicnode/BlendActionNode.hx
Fixes https://github.com/armory3d/armory/issues/1119 (see [comment](https://github.com/armory3d/armory/issues/1119#issuecomment-713737481)).
=> Fix BlendActionNode for empty action sockets

Sources/armory/logicnode/VectorFromBooleanNode.hx, blender/arm/logicnode/miscellaneous/LN_vector_from_boolean.py
This can be used as a kind of input map.
Example: [vectorfromboolean.zip](https://github.com/armory3d/armory/files/5425055/vectorfromboolean.zip)
With this node, this logic setup is sufficient to make a character walk in any direction:
=> New node Vector From Boolean

blender/arm/material/cycles.py, blender/arm/material/cycles_nodes/nodes_converter.py
Implements https://github.com/armory3d/armory/issues/1806
=> Implement cycles clamp node

Sources/armory/logicnode/GetFPSNode.hx, blender/arm/logicnode/miscellaneous/LN_get_fps.py
Category: _Miscellaneous_
This is sometimes more convenient than enable the entire debug console.
=> Add LN Get Frames Per Second

Sources/armory/logicnode/MixNode.hx, Sources/armory/logicnode/VectorMixNode.hx, blender/arm/logicnode/math/LN_mix.py, blender/arm/logicnode/math/LN_mix_vector.py
I don't know if there is some reason for this not available, seems to work fine.
=> Add Bounce and Elastic to Mix nodes

Sources/armory/trait/internal/DebugConsole.hx
=> Debug console: add "Set Active Camera" button for camera objects

Sources/armory/logicnode/DetectMobileBrowserNode.hx, blender/arm/logicnode/native/LN_detect_mobile_browser.py
Detect Mobile Browser
Category: _Native_
Demo: [web](https://e1e5en.github.io/armory3d-blog.github.io/detect_mobile_browser/)
=> LN Detect Mobile Browser

blender/arm/make.py
Forces a build before compilation server to generate first krom.js.
Fixes bug where compilation server will delete krom.js if it exists during first launch.
Initial Issue:
When attempting to use the Armory Player play button with Krom the below error would occur.  To fix it you would need to disable the compilation server in the addons menu to build the Krom.js file the first time, and then you could re-enable the compilation server.    
```
__________  [Armory] Compiling  __________
Exporting Scene
Scene exported in 0.011999368667602539
Exception in thread Thread-2:
File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\python\lib\threading.py", line 926, in _bootstrap_inner
self.run()
File "C:\Program Files\Blender Foundation\Blender …
```
=> Fix for play button not working with Krom.

Sources/armory/logicnode/ApplyForceAtLocationNode.hx, Sources/armory/logicnode/ApplyForceNode.hx, Sources/armory/logicnode/ApplyImpulseAtLocationNode.hx, Sources/armory/logicnode/ApplyImpulseNode.hx, Sources/armory/logicnode/ApplyTorqueImpulseNode.hx, Sources/armory/logicnode/ApplyTorqueNode.hx, Sources/armory/logicnode/GetVelocityNode.hx, Sources/armory/logicnode/TranslateObjectNode.hx, blender/arm/logicnode/physics/LN_apply_torque.py, blender/arm/logicnode/physics/LN_apply_torque_impulse.py, blender/arm/logicnode/physics/LN_get_rb_velocity.py
* Added `On Local Axis` checkbox to `Apply Torque`, `Apply Torque Impulse` and `Get RB Velocity`
* Replaced the method in the other nodes for `worldVecToOrientation()`
This line does not makes sense for me:
`inputs.length > 3 ? inputs[3].get() : false`
If the inputs length > 3, isn't to get the input 4?
And is this verification necessary? Because i will verify it in other nodes later.
=> Update nodes that own 'On Local Axis'

Sources/armory/logicnode/MathNode.hx, blender/arm/logicnode/math/LN_math.py
- Dynamically change the number of arguments for the selected operation;
- `Exp()` operation added.
=> Upgrading the Math Node

Sources/armory/logicnode/VectorMathNode.hx, blender/arm/logicnode/math/LN_vector_math.py
Dynamically change the number of input and output parameters for the selected operation.
=> Upgrading the Vector Math Node

blender/arm/logicnode/math/LN_math.py
=> Update the Math Node

blender/arm/props.py, blender/arm/props_ui.py
- Fixed a bug with updating the list of emulators if they are not there.
- Fixed a bug with enabling/disabling options when changing links to Android SDK.
- Fixed display of settings in the form of open panels. When collapsing panels appear incorrect display.
=> Fix Android and HTML5 Settings

blender/arm/exporter_opt.py
=> exporter_opt: fix `NameError: name 'log' is not defined`

Sources/armory/logicnode/MathExpressionNode.hx, blender/arm/logicnode/math/LN_math_expression.py
- Dynamically checking the correctness of an expression in the IDE (Blender).
- The task is divided into 2 parts: checking the correctness through _python_ in the _Blender_ interface and when performing calculations when the application is running in _haxe_.
The following decisions are taken as a basis:
- _python_ - http://repl.it/3xv/1
- _haxe_ - https://github.com/maitag/formula (added all the necessary classes to the node code)
There is a lot of code for this node. It works, but it can be optimized and refactored.
You can call it a _beta_ version. If someone wants to modernize it, I will be glad. I don’t have the option yet, unless later.
_P.S._ If this version of the node is not acceptable, then reject the PR. =)
=> LN Math Expression

Sources/armory/logicnode/AddRigidBodyNode.hx, Sources/armory/trait/physics/bullet/RigidBody.hx, blender/arm/exporter.py, blender/arm/logicnode/physics/LN_Add_rigid_body.py, blender/arm/props.py, blender/arm/props_ui.py
- Node to add rigid body at run-time. 
-Removed the "Force Deactivation" option in the Rigid body panel as it was redundant for the "Use Deactivation" option.
=> New Add rigid body node

Sources/armory/trait/physics/bullet/RigidBody.hx
Useful to remove the collision from gates.
The code was taken from here: https://pybullet.org/Bullet/phpBB3/viewtopic.php?t=11690
=> Added functions to disable/enable collision

Sources/armory/logicnode/OnSwipeNode.hx
Correction of determining the direction of UP-LEFT.
Wrong 9 degrees =)
=> Fix OnSwipe

Sources/armory/logicnode/OnVolumeTriggerNode.hx, Sources/armory/logicnode/VolumeTriggerNode.hx, blender/arm/logicnode/physics/LN_on_volume_trigger.py, blender/arm/logicnode/physics/LN_volume_trigger.py
Fix: https://github.com/armory3d/armory/issues/2044
=> Fix volume trigger

Sources/armory/logicnode/WorldVectorToLocalSpaceNode.hx, blender/arm/logicnode/transform/LN_vector_to_object_orientation.py, blender/arm/logicnode/transform/LN_world_vector_to_local_space.py
It can be used to get the local velocity of a RB, relative location (if an object is on left or right of another for example), etc.
=> Added World Vector to Local Space node

Sources/armory/trait/physics/bullet/PhysicsConstraint.hx, Sources/armory/trait/physics/bullet/PhysicsConstraintExportHelper.hx
=> Fix adding physics constraint at game start

blender/arm/nodes_logic.py, blender/arm/props_traits.py, blender/arm/props_ui.py
=> Improve node side panel + context menu (more operators, icons)

Sources/armory/trait/physics/bullet/PhysicsConstraint.hx
Improves physics constraint behavior.
=> Improve physics constraint handling

blender/arm/exporter.py
Fixes https://github.com/armory3d/armory/issues/2048.
=> Show warning when scene is missing a world and rp background is set to world

Sources/armory/system/InputMap.hx
Test here: https://github.com/knowledgenude/inputmap
=> Added input mapper

Sources/armory/trait/physics/bullet/PhysicsWorld.hx, blender/arm/exporter.py
This should solve the export errors in Blender 2.9.X
To be merged with #2082
=> Blender 2.9 Fix Exporter and conversions for Physics World

Sources/armory/system/InputMap.hx
* Cleanups and optimizations;
* Improved the user API (breaks compatibility);
* Added a WIP way to give "names" for each command of the active config. This is intended to display commands in UIs, so i am looking for a way to add images/translation. Open for suggestions!
Test changes: https://github.com/knowledgenude/inputmap
=> Update input mapper

Sources/armory/system/FSM.hx, Sources/armory/system/InputMap.hx
Sorry to send two different things at the same PR, I am too lazy now :p
**Changes to input map**
* Now the action maps and the axis maps is not grouped at a same class and the later does not return a vector anymore, just a single axis. Looks like It is how the Unreal Engine does.
* The scale parameter is now perfect for me. Is possible to control mouse sensitivity, character speed, etc. without have any conflict with the normalization. The scale is not dependent on which is the current config. It will return the biggest scale of the pressed input, no matter if gamepad, mouse or keyboard.
* Mouse and keyboard is now handled together. This allows to mix mouse modifiers and keyboard modifiers for the same input map.
It is confuse to describe how to setup the inputs, so i will send a PR for …
=> Update inputmap and added finite state machine

blender/arm/props_lod.py
=> Fix lod operator polling and add some bl_options

blender/arm/material/make_attrib.py, blender/arm/material/make_skin.py
Fixes https://github.com/armory3d/armory/issues/2100, there was a wrong order of statements in the exported glsl code.
=> Fix normals export of skinned materials

Sources/armory/trait/physics/bullet/PhysicsWorld.hx
Remove unused import from PhysicsWorld
=> Reuse contacts array instead of creating new

Sources/armory/system/FSM.hx
I found  a good way ~i guess~ to specify the FSM `owner` with type safety inspired by [Haxe Flixel FSM](https://github.com/HaxeFlixel/flixel-addons/blob/dev/flixel/addons/util/FlxFSM.hx) and by following Haxe manual, then no need to implement the state interface anymore...
Also removed the method to bind multiple transitions to avoid confusion. The [example file](https://github.com/knowledgenude/statemachine) will be send to Armory examples after the API reaches a stable version. 
I would create a way to simplify even more the way to setup the states (without the need to construct every single state with the same param) but i still can't realize how... i will search more when i got free time :)
=> Improved FSM

Sources/armory/logicnode/SendEventNode.hx, Sources/armory/logicnode/SendGlobalEventNode.hx
Remove entries member variable from SendEventNode and SendGlobalEventNode
=> Remove array allocation from SendEventNode

blender/arm/exporter.py, blender/arm/log.py, blender/arm/make.py
Minor improvements to terminal output:
- Shows scene name in missing camera warning
- Format scene export time to human readable string
- Format build flags to be copy/paste able
=> Console improvements

blender/arm/props_properties.py
=> Fix drawing of bool properties in UI (#1689)

Sources/armory/logicnode/ClampNode.hx
https://forums.armory3d.org/t/clamp-node-causes-failed-build/4523
=> Fix clamp node

blender/arm/logicnode/physics/LN_on_volume_trigger.py
The OnVolumeTrigger node does not required a RigidBody.
=> Make description of logic node more precise

blender/arm/material/cycles.py, blender/arm/material/cycles_functions.py, blender/arm/material/cycles_nodes/nodes_converter.py, blender/arm/material/cycles_nodes/nodes_vector.py
- The map range node should now be fully supported
- The vector rotate node should now be fully supported
- The blackbody node has been reimplemented in GLSL (rather than being a constant), so animating the value is possible now
- The math node should now be fully supported (the remaining missing operations was added)
=> Add map range node, vector rotate node, missing math operations and blackbody node

blender/arm/props_collision_filter_mask.py
=> Expose collision filter mask as integer to the UI

blender/arm/exporter.py
This PR improves the handling of problems described in https://github.com/armory3d/armory/issues/2104. Instead of hundreds of warnings for a single action there is now only one centralized warning which better describes the possible reasons for it:
Thanks to the user Pewsplosions on Discord for their feedback on this issue :)
=> Improve warning message for unsupported/unknown fcurve data paths

Sources/armory/trait/internal/DebugConsole.hx
This was done to make it easier to understand what is going on with atlases to help users and also the maintenance of the feature.
=> Add visual representation of shadow map atlases to the debug console

blender/arm/props_ui.py, blender/arm/utils.py
=> Update Blender version information to 2.93 LTS

Sources/armory/logicnode/GetObjectNode.hx, Sources/armory/logicnode/SpawnObjectByNameNode.hx, blender/arm/logicnode/object/LN_get_object_by_name.py, blender/arm/logicnode/object/LN_spawn_object.py, blender/arm/logicnode/object/LN_spawn_object_by_name.py
Should solve #2171 
Added a new Logic Node that enables spawning of objects not present in active scene
=> Get object by name node fix

Sources/armory/logicnode/OncePerFrameNode.hx, blender/arm/logicnode/logic/LN_once_per_frame.py
Introduces a new node "Once Per Frame". Fixes #2202
=> Extra logic nodes

Sources/armory/logicnode/GetBoneFkIkOnlyNode.hx, Sources/armory/logicnode/GetGamepadStartedNode.hx, Sources/armory/logicnode/GetKeyboardStartedNode.hx, Sources/armory/logicnode/GetMouseStartedNode.hx, blender/arm/logicnode/input/LN_get_gamepad_started.py, blender/arm/logicnode/input/LN_get_keyboard_started.py, blender/arm/logicnode/input/LN_get_mouse_started.py
Partially fixes https://github.com/armory3d/armory/issues/2229
Added new nodes related to https://github.com/armory3d/armory/issues/2215
I will look into add input for the Keyboard, Gamepad and Mouse nodes later
* Requires https://github.com/armory3d/iron/pull/127
=> Fix GetBoneFkIkOnly node & add new input nodes

Sources/armory/logicnode/LogicNode.hx
Add a check to see if input socket is linked to correct output socket.
Fixes #2246
=> Add check to LogicNode run

Sources/armory/logicnode/CompareNode.hx, Sources/armory/logicnode/GateNode.hx, Sources/armory/logicnode/GetTraitNameNode.hx, Sources/armory/logicnode/PauseTraitNode.hx, Sources/armory/logicnode/ResumeTraitNode.hx, Sources/armory/logicnode/SetParentNode.hx, Sources/armory/logicnode/SetTraitPausedNode.hx, Sources/armory/trait/FollowCamera.hx, Sources/armory/trait/physics/bullet/RigidBody.hx
To get rid of compiler warnings.
=> Replace deprecated Std.is with Std.isOfType

Sources/armory/trait/internal/DebugConsole.hx
Fix https://github.com/armory3d/armory/issues/2253
Thanks to @ sh-dave [here](https://github.com/armory3d/armory/issues/2253#issuecomment-874721108)
=> Fix nullability

Sources/armory/logicnode/SetMaterialImageParamNode.hx, Sources/armory/logicnode/SetMaterialRgbParamNode.hx, Sources/armory/logicnode/SetMaterialValueParamNode.hx, Sources/armory/trait/internal/UniformsManager.hx
=> Static target fix

Sources/armory/trait/internal/UniformsManager.hx, blender/arm/material/cycles_nodes/nodes_texture.py, blender/arm/props_ui.py
Partially fixes #1943 , when exporting terrain to Krom.
=> Fix terrain export for Krom

blender/arm/handlers.py
Thanks to @QuantumCoderQC for reporting this on Discord.
=> Continue thread polling after an exception in the done callback

Sources/armory/trait/PhysicsDrag.hx
Adds properties to the PhysicsDrag trait to have control over linear/angular limits.
=> PhysicsDrag trait limit props

Sources/armory/system/Logic.hx
Updated Logic.hx with changes made in make_logic.py to fix the [failed CI](https://github.com/armory3d/armsdk/pull/26/checks?check_run_id=3265542080) on the armsdk repo. Is this file still used somewhere?
=> Fix armsdk CI

blender/arm/props_ui.py
Adds _shift_ option to the _Play_ button to just run last build (without compiling).
=> Shift click play just run

blender/arm/logicnode/animation/LN_set_parent_bone.py, blender/arm/logicnode/arm_nodes.py, blender/arm/logicnode/arm_sockets.py, blender/arm/logicnode/input/LN_gamepad.py, blender/arm/logicnode/input/LN_on_swipe.py, blender/arm/logicnode/input/LN_on_tap_screen.py, blender/arm/logicnode/logic/LN_loop.py, blender/arm/logicnode/miscellaneous/LN_set_debug_console_settings.py, blender/arm/logicnode/miscellaneous/LN_timer.py, blender/arm/logicnode/native/LN_set_vibrate.py, blender/arm/logicnode/object/LN_set_object_parent.py, blender/arm/logicnode/physics/LN_Add_rigid_body.py, blender/arm/nodes_logic.py
- Fixed some smaller issues with default values (partly fixed in https://github.com/armory3d/armory/pull/2305, the other part is in this PR). We should probably make `ArmCustomSocket` abstract and add getters and setters for default values to prevent such errors in the future.
- While generating the new node screenshots for SDK 21.08, I noticed that the new custom node socket's weren't 100% similar to the Blender sockets, this PR fixes that.
- Updated the node's context menu to point to the new wiki pages (see https://github.com/armory3d/armory_tools/pull/9)
=> Various node fixes

Sources/armory/logicnode/GetAgentDataNode.hx, Sources/armory/logicnode/GoToLocationNode.hx, Sources/armory/trait/NavAgent.hx, blender/arm/logicnode/navmesh/LN_get_agent_data.py, blender/arm/logicnode/navmesh/LN_go_to_location.py
1. Adds Speed and Turn Duration inputs to the go to location node
2. Adds a new node to get NavAgent data
Thanks to @ mokauno for pointing this requirement on the Forums.
=> Small improvement to Navigation nodes

Sources/armory/logicnode/AddTraitNode.hx, blender/arm/logicnode/trait/LN_add_trait_to_object.py
Fixes #2289 by replacing the `Trait` input to `String`. Thanks to @MoritzBrueckner for the discussions and insight.
=> Add trait fix

blender/arm/logicnode/arm_nodes.py
Fixes https://github.com/armory3d/armory/issues/2328, it was caused by a little typo.
=> Fix ArmNodeAddInputOutputButton

Sources/armory/logicnode/TweenFloatNode.hx, Sources/armory/logicnode/TweenRotationNode.hx, Sources/armory/logicnode/TweenVectorNode.hx, blender/arm/logicnode/math/LN_tween_float.py, blender/arm/logicnode/math/LN_tween_rotation.py, blender/arm/logicnode/math/LN_tween_vector.py
This PR adds 3 new nodes for tweening `Float`, `Vector` and `Rotation` values
Tween Float Node:
=> Introducing Tween nodes

blender/arm/utils.py
Fix for https://github.com/armory3d/armsdk/issues/31
=> Fix invalid fp when using local sdk

blender/arm/props.py, blender/arm/props_renderpath.py, blender/arm/props_ui.py, blender/arm/utils.py
See https://github.com/armory3d/armory_tutorials/pull/11#issuecomment-932722484.
=> Allow to set default renderpath for debugging

Sources/armory/logicnode/PickObjectNode.hx, blender/arm/logicnode/physics/LN_pick_rb.py
This PR add a "Normal" output for the pick RB node
=> add normal output for pick rb node

blender/arm/exporter.py
The new morph-target exporting had explicit backwards-slash directory separators, and while that works fine on Windows, we need to use forward-slash separators for the Unix-based systems (Linux, MacOS). I also received an issue due to some parameters not being ints in the NLA code, not sure if this is platform dependent or not. 
To fix this, this PR uses `os.path.join` to automatically join the two with the correct separators as well as casts the problem paramaters to int. This also cleans up some extra spaces lying around in the file since my editor automatically removes them.
(Also, a million thanks to @QuantumCoderQC for this feature!!)
=> Fix morph target exporting on Unix-based systems

Sources/armory/trait/physics/bullet/PhysicsWorld.hx, Sources/armory/trait/physics/bullet/RigidBody.hx
This PR tries to fix memory leaks when targeting HL.
Thanks to @sh-dave for bringing up this issue on Discord.
=> Fix bullet physics memory leak on HL targets

Sources/armory/trait/physics/bullet/SoftBody.hx
See https://github.com/armory3d/iron/pull/146.
=> Fix vertex buffer locking on html5 for soft bodies

Sources/armory/logicnode/DetectMobileBrowserNode.hx
fix return type in detect mobile browser node.
=> Detect mobile browser node fix

Sources/armory/logicnode/IsRigidBodyActiveNode.hx, Sources/armory/trait/physics/bullet/RigidBody.hx, blender/arm/logicnode/physics/LN_is_rb_active.py
I'm using this for debugging, thought i'd share it here as well. Could possibly be improved to use `RB.getActivationState()` instead, so you can switch over the values (ISLAND_SLEEPING, DISABLE_DEACTIVATION, ...) for more control.
=> add IsRigidBodyActive node

Sources/armory/logicnode/ClearParentNode.hx, Sources/armory/logicnode/SetParentBoneNode.hx, Sources/armory/logicnode/SetParentNode.hx
Requires https://github.com/armory3d/iron/pull/148.
=> Replace deprecated addChild()/removeChild() functions with setParent()

Sources/armory/logicnode/RemoveParentBoneNode.hx, blender/arm/logicnode/animation/LN_remove_parent_bone.py
requires: https://github.com/armory3d/iron/pull/149
This node complements for:
=> add Remove Parent Bone Node

Sources/armory/logicnode/AddGroupNode.hx, Sources/armory/logicnode/AddObjectToGroupNode.hx, Sources/armory/logicnode/RemoveObjectFromGroupNode.hx, blender/arm/logicnode/scene/LN_add_object_to_collection.py, blender/arm/logicnode/scene/LN_create_collection.py, blender/arm/logicnode/scene/LN_remove_object_from_collection.py
improve the create collection node by adding object arrays when creating a collection
add and remove object from a collection
requires: https://github.com/armory3d/iron/pull/151
=> add and remove objects from collections

Sources/armory/logicnode/MathNode.hx, blender/arm/logicnode/math/LN_math.py
=> Math node - add precision for round

Sources/armory/logicnode/NavigableLocationNode.hx
fix node error not finding the navmesh
delete the notifying function causing the error not finding the navmesh at init, add assert error to verify navmesh exists
=> fix NavigableLocationNode error

Sources/armory/logicnode/AlternateNode.hx, blender/arm/logicnode/logic/LN_alternate_output.py
update the node from 0-1 to several
=> Alternate Output - alternate outputs with several outputs

blender/arm/logicnode/arm_nodes.py, blender/arm/nodes_logic.py
This PR adds a little sidebar panel in the node editor to allow to quickly see a node's metadata. Also the Replace Nodes operator now has a button in the UI, which should fix https://github.com/armory3d/armory/issues/2209.
=> New sidebar panel to ease logic node development

Sources/armory/logicnode/SetAreaLightSizeNode.hx, Sources/armory/logicnode/SetSpotLightBlendNode.hx, Sources/armory/logicnode/SetSpotLightSizeNode.hx, blender/arm/logicnode/light/LN_set_area_light_size.py, blender/arm/logicnode/light/LN_set_spot_light_blend.py, blender/arm/logicnode/light/LN_set_spot_light_size.py
=> Lights - Add nodes to control spot and area size, and spot blend

blender/arm/logicnode/arm_sockets.py
Thanks to softyoda on Discord for the report :)
ArmAnySocket sockets still don't follow reroutes when it comes to displaying the correct name, I will try to implement this in the next days.
=> Fix exception in ArmAnySocket.draw_color() when connecting reroute node

blender/arm/make.py, blender/arm/props.py, blender/arm/props_ui.py, blender/arm/utils.py
Should VS2022 also be the new default since it is default in Kha, or is it to early for that?
=> Add support for VS2022

Sources/armory/logicnode/ArrayResizeNode.hx, Sources/armory/logicnode/ArraySpliceNode.hx, blender/arm/logicnode/array/LN_array_resize.py
Simply a wrapper around `Array.resize()`.
=> New Array Resize node

blender/arm/exporter.py
Exporter code for https://github.com/armory3d/iron/pull/159.
=> Add support for particle emission from faces

blender/arm/make.py, blender/arm/utils.py
=> Search ffmpeg if not set

Sources/armory/logicnode/PulseNode.hx, blender/arm/logicnode/logic/LN_pulse.py
@ **TriVoxel** in DC was needing help for creating an automatic weapon logic, so I propose a node to further facilitate this
The node allows to **limit the rate** of the signal
Most common uses:
- Prevent spam
- Control weapon fire rate
*Refactored. Thanks to @ QuantumCoderQC by the new layout idea
=> Introduce Pulse Node

Sources/armory/logicnode/DrawArcNode.hx, Sources/armory/logicnode/DrawCameraNode.hx, Sources/armory/logicnode/DrawCameraTextureNode.hx, Sources/armory/logicnode/DrawCircleNode.hx, Sources/armory/logicnode/DrawCurveNode.hx, Sources/armory/logicnode/DrawImageNode.hx, Sources/armory/logicnode/DrawImageSequenceNode.hx, Sources/armory/logicnode/DrawLineNode.hx, Sources/armory/logicnode/DrawPolygonNode.hx, Sources/armory/logicnode/DrawRectNode.hx, Sources/armory/logicnode/DrawStringNode.hx, Sources/armory/logicnode/DrawTriangleNode.hx, Sources/armory/logicnode/OnRender2DNode.hx, Sources/armory/trait/internal/CanvasScript.hx, Sources/armory/trait/internal/DebugConsole.hx, Sources/armory/ui/Canvas.hx, blender/arm/logicnode/event/LN_on_render2d.py, blender/arm/logicnode/renderpath/LN_draw_arc.py, blender/arm/logicnode/renderpath/LN_draw_camera.py, blender/arm/logicnode/renderpath/LN_draw_camera_texture.py, blender/arm/logicnode/renderpath/LN_draw_circle.py, blender/arm/logicnode/renderpath/LN_draw_curve.py, blender/arm/logicnode/renderpath/LN_draw_image.py, blender/arm/logicnode/renderpath/LN_draw_image_sequence.py, blender/arm/logicnode/renderpath/LN_draw_line.py, blender/arm/logicnode/renderpath/LN_draw_polygon.py, blender/arm/logicnode/renderpath/LN_draw_rect.py, blender/arm/logicnode/renderpath/LN_draw_string.py, blender/arm/logicnode/renderpath/LN_draw_triangle.py
sorry ive been away, i did these nodes in February, this upload was long due:
both camera nodes draw camera in the scene considering position size and windows size. Nodes can be activated and deactivated (sorry for the misspelling in the codes, im gonna fix it later)
=> Several Draw nodes: cameras, images, string, geometric figures, etc

Sources/armory/renderpath/Nishita.hx
This PR fixes an integer overflow that could happen in `Nishita.raySphereIntersection()` when squaring the current default atmosphere radius with 32 bit ints. This would result in a wrong LUT and nan/inf values in the sky shader.
It is fixed by combining two approaches:
- The atmosphere's and earth's radii are no longer specified in meters but in kilometers
- We use 64 bit floats instead of ints to encode the radii. This way there is more precision for small values (= where it is needed), and less precision for larger values. So it is still possible to use meters where it could make a visible difference.
I originally tried to use haxe.Int64, but that didn't work out since there is no easy way in the Haxe API to convert such values to float.
Thanks to @ QuantumCoderQC for the report and …
=> [HL] Fix int overflow in Nishita LUT calculations

blender/arm/material/cycles_nodes/nodes_input.py, blender/arm/material/shader.py
Minor fix for export of material parameters.
=> Fix arm material parameter export

blender/arm/handlers.py
A minor fix for copying rigid body parameters from the active object.
=> Fix rigid body copy parameters

Sources/armory/logicnode/CreateRenderTargetNode.hx, Sources/armory/logicnode/DrawArcNode.hx, Sources/armory/logicnode/DrawCircleNode.hx, Sources/armory/logicnode/DrawCurveNode.hx, Sources/armory/logicnode/DrawImageNode.hx, Sources/armory/logicnode/DrawLineNode.hx, Sources/armory/logicnode/DrawPolygonNode.hx, Sources/armory/logicnode/DrawRectNode.hx, Sources/armory/logicnode/DrawStringNode.hx, Sources/armory/logicnode/DrawToMaterialImageNode.hx, Sources/armory/logicnode/DrawTriangleNode.hx, Sources/armory/logicnode/OnRender2DNode.hx, Sources/armory/renderpath/RenderToTexture.hx, Sources/armory/trait/internal/UniformsManager.hx, blender/arm/logicnode/renderpath/LN_create_render_target.py, blender/arm/logicnode/renderpath/LN_draw_to_material_image.py
This PR extends the draw 2D nodes to be able to draw to material image textures. This would be useful to create speech bubbles and the like.
A small demo:
Shader and Logic setup:
=> Draw to material image texture

Sources/armory/logicnode/CanvasSetInputTextFocusNode.hx, Sources/armory/trait/internal/CanvasScript.hx, blender/arm/logicnode/canvas/LN_set_canvas_input_text_focus.py
Added the nodes function to internal/canvasscript
=> New node for setting canvas input text focus

Sources/armory/logicnode/RemoveObjectNode.hx, blender/arm/logicnode/object/LN_remove_object.py
Implements #2570
[A3D_Remove_Object_Upgrade.zip](https://github.com/armory3d/armory/files/9602553/A3D_Remove_Object_Upgrade.zip)
Special thanks to @MoritzBrueckner & @QuantumCoderQC for help, suggestions and code reviews!
=> Upgrade for remove object node

blender/arm/props_traits.py
=> Edit scripts button: use Haxe icon instead of Python icon

README.md
Hello. While Armory3D is understandably buggy in some areas: what kind of open-source software isn't, Armory has come a long ways. First the Blender 2.8x port to Armory. Then the Blender 2.9x port. And now finally the Blender 3.x port.
I think it's time we updated this repository's readme from, "in development," to something more accurate to the current times.
**Note:** If this PR is merged, please update the description a the [Itch.io](https://armory.itch.io/armory3d) as well for matching software statuses.
**Edit:** Sorry for the PR closing! origin and upstream sync issues..
=> Update outdated readme

blender/arm/make.py, blender/arm/utils.py
See https://github.com/armory3d/armsdk/pull/51.
=> Add option to automatically decide amount of Khamake processes

Sources/armory/logicnode/PlaySoundRawNode.hx, blender/arm/logicnode/sound/LN_play_sound.py
Adds an option to set volume of the playback sound. Thanks for the feature request by @ RichBern on Discord.
=> Add option to set playback volume

blender/arm/make.py
As discussed: https://github.com/armory3d/armory/pull/2605
=> Fix webbrowser get name

blender/arm/material/make_tess.py
I've closed #2625 because I needed to recreate a branch.
=> Tesselation missing consts

Sources/armory/logicnode/GetDebugConsoleSettings.hx, Sources/armory/logicnode/SetDebugConsoleSettings.hx
This PR fixes the broken compilation of the debug console nodes introduced in https://github.com/armory3d/armory/pull/2637 and some whitespace issues.
=> Fix [Get/Set]DebugConsoleSettings nodes

blender/arm/api.py, blender/arm/assets.py, blender/arm/exporter.py, blender/arm/exporter_opt.py, blender/arm/handlers.py, blender/arm/keymap.py, blender/arm/live_patch.py, blender/arm/log.py, blender/arm/make.py, blender/arm/profiler.py, blender/arm/ui_icons.py
=> Fix pylint warnings

Shaders/deferred_light/deferred_light.frag.glsl, Shaders/deferred_light_mobile/deferred_light.frag.glsl, blender/arm/material/make_mesh.py
A small fixes for BRDF LUT issues.
- Better texture sampling (Temp. fix for #2668)
- Correct texture coordinates (Fix for overbrightened edges of the meshes)
=> * FIX: Temporary fix(es) for BRDF LUT issues

blender/arm/make.py
=> Fix custom exporter khamake arguments

blender/arm/log.py
=> Log no ansi in blender console

Sources/armory/logicnode/PhysicsConvexCastNode.hx, Sources/armory/trait/physics/bullet/PhysicsWorld.hx, blender/arm/logicnode/physics/LN_convex_cast.py
Also known as Convex Sweep Test in Bullet Physics;
Requires https://github.com/armory3d/haxebullet/pull/40
https://user-images.githubusercontent.com/55564981/204808156-46ff8aa3-1cdb-4434-925a-70398e6dd059.mp4
Thanks to @ triVoxel for requesting this feature on Discord
=> This PR implements Physics Convex Casting

blender/arm/logicnode/logic/LN_switch_output.py
Fixes https://github.com/armory3d/armory/issues/2686
Issue was accidentally created by me at https://github.com/armory3d/armory/commit/cf086d770ee6af9de0fa15c50876bc5f62198b0a#diff-7abac0ad65b654c84a154bda143a74bac8f5dbbfee09fa698fdc20c477274d47
Thanks to @JAWS81 for reporting this on Discord.
=> Fix inputs outputs

blender/arm/logicnode/logic/LN_function.py, blender/arm/logicnode/math/LN_screen_to_world_space.py, blender/arm/logicnode/math/LN_vector_math.py
Some more logic node cleanup:
1. Fixed remove outputs minimums detection.
2. Removed unused references.
3. Fixed whitespace [(x4 spaces)](https://github.com/armory3d/armory/wiki/Code-Style).
=> Socket output cleanup

Sources/armory/logicnode/GetPointVelocityNode.hx, Sources/armory/trait/physics/bullet/RigidBody.hx, blender/arm/logicnode/physics/LN_get_rb_point_velocity.py
This allow us to get the velocity of a point that is not the center of the mass of the rigid body. Useful to make custom vehicle physics, etc.
Also added a new node for this.
=> Add getPointVelocity method

blender/arm/logicnode/arm_nodes.py, blender/arm/logicnode/array/LN_array_add.py, blender/arm/logicnode/logic/LN_output_sequence.py, blender/arm/logicnode/logic/LN_select.py, blender/arm/logicnode/logic/LN_switch_output.py, blender/arm/logicnode/renderpath/LN_draw_camera.py, blender/arm/logicnode/renderpath/LN_draw_polygon.py
1. `LN_array_add.py` - Fixed remove sockets error.
2. `LN_switch_output.py` + `arm_nodes.py` - Corrected dynamic output naming to match  dynamic input naming + implement new output index method.
3. `LN_draw_camera.py` - Implemented missing minimum check.
4. `LN_draw_polygo.pyn` - Implemented missing minimum check.
5. `LN_output_sequence.py` - Implemented missing minimum check.
6. `LN_select.py` - Implemented missing minimum check.
<hr />
Sorry for so many pulls so far, I have created quite a bit lately.. for some reason, in the past, a lot of people seem to have copy-pasted code without copying over the minimum check condition code as well. Maybe back in the day that certain API code didn't exist or something? Of course, this is no excuse and I should have found that code earlier on, …
=> Fix misc nodes

Shaders/deferred_light/deferred_light.frag.glsl
=> Check if voxel AO enabled for deferred lighting

blender/arm/logicnode/array/LN_array_integer.py
to keep consistency among other array nodes that are variables
=> Add variable socket to array integer

blender/arm/logicnode/input/LN_mouse.py
Requires https://github.com/armory3d/iron/pull/178
Feature requested here: https://forums.armory3d.org/t/feature-request-add-side-mouse-buttons-to-mouse-logic-node/5083/1
=> Add extra mouse buttons

Sources/armory/logicnode/ArrayGetNextNode.hx, blender/arm/logicnode/array/LN_array_get_next.py
Every time this node is activated it retrieves an element of the array, looping through all the elements
=> Logic node: Array get next

blender/arm/logicnode/deprecated/LN_on_mouse.py, blender/arm/logicnode/input/LN_mouse.py, blender/arm/logicnode/physics/LN_pick_rb.py
Fixes https://github.com/armory3d/armory/issues/2714. I also updated the corresponding example at https://github.com/armory3d/armory_examples/pull/65.
=> Fix node version updates for mouse and pick RB nodes

Sources/armory/logicnode/RotateRenderTargetNode.hx, blender/arm/logicnode/renderpath/LN_rotate_render_target.py
New node to rotate the 2D render target.
=> Implement rotate render target node

blender/arm/exporter.py, blender/arm/make.py, blender/arm/write_probes.py
Always print `make.run_proc` calls. (https://github.com/armory3d/armory/issues/2693).
=> Always print calls to external tools

Sources/armory/logicnode/NetworkHostNode.hx
Try and catch to avoid crashing application
=> Persist server process

Sources/armory/logicnode/ParseIntNode.hx, Sources/armory/logicnode/StringReplaceNode.hx, blender/arm/logicnode/string/LN_parse_int.py, blender/arm/logicnode/string/LN_string_replace.py
=> add StringReplace and ParseInt nodes

Sources/armory/logicnode/CaseIndexNode.hx, Sources/armory/logicnode/IntFromBooleanNode.hx, blender/arm/logicnode/logic/LN_case_index.py, blender/arm/logicnode/miscellaneous/LN_boolean_to_int.py
=> add CaseIndex and BooleanToInt nodes

Sources/armory/logicnode/DrawTextAreaStringNode.hx
a = was missing from my original logic in case someone uses a text area with 1 word
=> little fix

Sources/armory/logicnode/CombineColorHSVNode.hx, Sources/armory/logicnode/SeparateColorHSVNode.hx, blender/arm/logicnode/math/LN_combine_hsv.py, blender/arm/logicnode/math/LN_separate_hsv.py
=> add Combine and Separate HSVA colors

.vscode/settings.json
1. This PR helps Armory contributors uphold the code styles described in: https://github.com/armory3d/armory/wiki/Code-Style
2. I will add a small section to the mentioned wiki page if this PR is merged, to indicate that in order for the config to be recognized the armsdk folder must be stated as a VSCode `Workspace`.
<hr />
A few questions for you @ Lubos
1. If it's not too much trouble, and to avoid numerous PRs, would you mind opening/saving all of the armsdk files to update their indentations? There will be a _**extremely**_ large diff, so it might be better if you're the one doing it anyhow to avoid any potential mishaps. **NOTE:** You don't have to open/import all of the files in VSCode by-hand _(that would be insane)_. Instead, you could uncollapse all of the folders/files in your …
=> Workspace config for code styles

blender/arm/logicnode/string/LN_string_replace.py
the node works but the color of the output socket was wrong.
=> StringReplace: fix output to string

Sources/armory/logicnode/RemoveTraitObjectNode.hx, blender/arm/logicnode/trait/LN_remove_trait_from_object.py
this node allows to remove a trait from a specific object (simil to the add trait to object node).
=> logic node: Remove Trait from Object

Sources/armory/logicnode/GetObjectGroupNode.hx, blender/arm/logicnode/scene/LN_get_object_collection.py
thanks @MoritzBrueckner for the comment.
=> logic node: get object collection add array collection output

Sources/armory/logicnode/ArrayConcatNode.hx, Sources/armory/logicnode/ArrayReverseNode.hx, blender/arm/logicnode/array/LN_array_concat.py, blender/arm/logicnode/array/LN_array_reverse.py
=> Logic nodes: Array Reverse and Array Concat

blender/arm/props.py, blender/arm/props_ui.py
Making it a bit clearer what this option does:
=> Rename "Khafile" option to "Append Khafile"

Sources/armory/logicnode/ArraySortNode.hx, blender/arm/logicnode/array/LN_array_sort.py
=> Logic Nodes: Array Sort Node

Sources/armory/logicnode/ArrayIndexNode.hx, blender/arm/logicnode/array/LN_array_index.py
beyond knowing if certain value is in the array, this node allows to know the exact position.
It could be used along with the array sort node, since values can change their initial index, to track index among other values.
=> logic node: Array Index

blender/arm/make.py, blender/arm/make_renderpath.py, blender/arm/props_renderpath.py, blender/arm/props_ui.py
Originally requested by _**projectBP**_ on Discord.
Special thanks to @ MoritzBrueckner for feedback and help.
<hr />
=> Custom lut naming

Sources/armory/logicnode/RandomStringNode.hx, blender/arm/logicnode/random/LN_random_string.py
This node could be used to generate random strings for numeric codes or alpha numeric codes... of a certain length.
=> Logic Node: Random String

Sources/armory/logicnode/RandomStringNode.hx
thanks @ MoritzBrueckner, i did the fix in the string declaration and changed the concatenation method to the buf type.
=> Fix Random String Node

Sources/armory/logicnode/ArrayCompareNode.hx, blender/arm/logicnode/array/LN_array_compare.py
=> Logic Node: Array Compare

Sources/armory/logicnode/ArrayCountNode.hx, Sources/armory/logicnode/ArrayDistinctNode.hx, blender/arm/logicnode/array/LN_array_count.py, blender/arm/logicnode/array/LN_array_distinct.py
Array Count Node: returns a 2D Array with every item count
Array Distinct Node: returns  both Array list of distinct and duplicated items
=> Logic Nodes: Array Count and Array Distinct

Sources/armory/logicnode/MathNode.hx, blender/arm/logicnode/math/LN_math.py
Same as in blender math node:
https://docs.blender.org/manual/en/latest/modeling/geometry_nodes/utilities/math.html
=> Math Node: add Ping-Pong property

Sources/armory/logicnode/CanvasGetTextNode.hx, blender/arm/logicnode/LN_get_canvas_text.py
Originally requested here: https://forums.armory3d.org/t/how-can-i-read-canvas-text/5157/1
=> Logic Node: Get Canvas Text

Sources/armory/logicnode/PlayActionFromNode.hx, blender/arm/logicnode/animation/LN_play_action_from.py
Closes: #2635 | Requires: https://github.com/armory3d/iron/pull/186
* NOTE: Bone animations do not yet support scaling. (@ QuantumCoderQC is working on a different branch to implement this.)
https://user-images.githubusercontent.com/69180012/218913568-f6dbad31-5810-42b0-810c-0022f203b387.mp4
<br />
Special thanks to @ MoritzBrueckner (help, review) @ QuantumCoderQC (help, review), @ t3du (early review).
=> End frame for "Play Action From" node

blender/arm/logicnode/math/LN_math.py
=> add replacement function for math node

blender/arm/logicnode/arm_node_group.py, blender/arm/logicnode/arm_nodes.py, blender/arm/logicnode/arm_sockets.py, blender/arm/logicnode/miscellaneous/LN_call_group.py, blender/arm/logicnode/miscellaneous/LN_group_input.py, blender/arm/logicnode/miscellaneous/LN_group_output.py, blender/arm/logicnode/replacement.py, blender/arm/logicnode/tree_variables.py, blender/arm/make_logic.py, blender/arm/nodes_logic.py
This PR improves the current node group system and makes the usage more Blender like.
A short preview of features:
https://www.youtube.com/watch?v=eGdXT1ndkcw
=> Improved Node Groups

Sources/armory/logicnode/ClearConsoleNode.hx, blender/arm/logicnode/native/LN_clear_console.py, blender/arm/props.py, blender/arm/props_ui.py
**Special thanks to:**
* @ SunDaw for pointing out the `Sys.command` method for Haxe.
* @ MoritzBrueckner for review and comments.
* @ QuantumCoderQC for review.
=> New clear console option + logic node

blender/arm/logicnode/canvas/LN_set_canvas_input_text.py, blender/arm/logicnode/canvas/LN_set_canvas_input_text_focus.py, blender/arm/logicnode/network/LN_network_client.py, blender/arm/logicnode/network/LN_network_close_connection.py, blender/arm/logicnode/network/LN_network_host.py, blender/arm/logicnode/network/LN_network_host_close_client.py, blender/arm/logicnode/network/LN_network_host_get_ip.py, blender/arm/logicnode/network/LN_network_http_request.py, blender/arm/logicnode/network/LN_network_message_parser.py, blender/arm/logicnode/network/LN_network_open.py
@ QuantumCoderQC is busy, so I'm commiting my own changes on their behalf with permission. (Thanks for the quick review too QC.)
All issues were caused by the same individual. (Possibly a copy-paste scenario, no one is perfect.)
=> Fix broken inits for various logic nodes

blender/arm/make_logic.py
Nested node groups were incorrectly parsed. This PR fixes this issue.
Thanks to @ BrahRah on Discord for reporting the issue and testing the fix.
=> Fix nested node group parsing

blender/arm/logicnode/input/LN_keyboard.py
Requires: https://github.com/armory3d/iron/pull/189
Closes: https://github.com/armory3d/armory/issues/906
```haxe
package arm;
import iron.system.Input;
class MyTrait extends iron.Trait {
public function new() {
super();
notifyOnUpdate(function() {
if (Input.getKeyboard().started("capslock")) trace("abc");
});
}
}
```
=> Implement "capslock" detection

blender/arm/material/make_overlay.py, blender/arm/props.py
Resolves #2694
Special thanks to @ MoritzBrueckner for review and suggestions.
=> Fix missing overlay emission color

blender/arm/material/cycles.py
The parsed data was not returned.
=> Fix parsing of custom shader data node

Sources/armory/logicnode/NetworkHttpRequestNode.hx, blender/arm/logicnode/network/LN_network_http_request.py
** Added the possibility to configure headers and parameters to the request using the new Map<String,String> node along with the option for byte data
=> Upgrade NetworkHttpRequestNode

Shaders/compositor_pass/compositor_pass.frag.glsl, Shaders/compositor_pass/compositor_pass.json, Sources/armory/logicnode/LetterboxGetNode.hx, Sources/armory/logicnode/LetterboxSetNode.hx, Sources/armory/renderpath/Postprocess.hx, blender/arm/logicnode/postprocess/LN_get_letterbox_settings.py, blender/arm/logicnode/postprocess/LN_set_letterbox_settings.py
Special thanks to @ MoritzBrueckner for tips and Haxe help.
=> New logic nodes - get/set letterbox settings logic

Sources/armory/logicnode/DrawArcNode.hx, Sources/armory/logicnode/DrawCircleNode.hx, Sources/armory/logicnode/DrawCurveNode.hx, Sources/armory/logicnode/DrawEllipseNode.hx, Sources/armory/logicnode/DrawPolygonNode.hx, Sources/armory/logicnode/DrawTextAreaStringNode.hx, Sources/armory/trait/VirtualGamepad.hx, Sources/armory/ui/Canvas.hx
Fixes https://github.com/armory3d/armory/issues/2868 and requires https://github.com/armory3d/zui/pull/164.
=> Fix canvas deprecation warnings

blender/arm/nodes_logic.py
Let me know if you want to keep the dot icon!
=> UI Node editor icon update

Sources/armory/logicnode/RotationMathNode.hx
=> Support JS Float Type

blender/arm/props_ui.py
=> Add "clean" button to 3D view topbar

Sources/armory/logicnode/MathExpressionNode.hx
Only the haxe-part at now but there is also some errorparsing-glitches at the python-side,
so functions like "cos" and "sin" etc. can not be used inside the math-expression:
blender/arm/logicnode/math/LN_math_expression.py
I am no py-expert so i am commented out all inside `def set_exp(self, value):` for testing.
(Formula-lib also gives good error-msg at runtime if there is something wrong into the math-expression or a missing variable etc.)
(^_^)
=> better param-bindings and upgrading to formula haxelib version 0.4.2

Sources/armory/trait/internal/UniformsManager.hx, blender/arm/material/make.py, blender/arm/material/shader.py
HL builds did not compile due to naming conflicts owing to https://github.com/HaxeFoundation/haxe/issues/11293
This PR fixes it by changing variable names.
Requires: https://github.com/armory3d/iron/pull/197
=> Change bind and shader constants names

blender/arm/logicnode/network/LN_network_close_connection.py
=> Draw missing property of Close Connection network node

Sources/armory/logicnode/OnRemoveNode.hx, blender/arm/logicnode/event/LN_on_remove.py
=> Add On Remove event

Sources/armory/logicnode/WaitForNode.hx, blender/arm/logicnode/logic/LN_wait_for.py
This node waits for all inputs to trigger the output once.
=> Wait For All Inputs Node

blender/arm/logicnode/math/LN_world_to_screen_space.py
Thanks to @ anniepoo on Discord for reporting this.
@luboslenco Would you mind updating the itch.io builds with this fix? Armory projects using SDK 23.11 don't compile at the moment.
=> [Hotfix/release broken] Fix Python indentation error

Sources/armory/trait/internal/DebugConsole.hx
=> Show object properties in debug console

Sources/armory/trait/WalkNavigation.hx
=> Keep WalkNavigation init function if arm_debug

blender/arm/logicnode/event/LN_on_event.py, blender/arm/logicnode/event/LN_send_event_to_object.py, blender/arm/logicnode/event/LN_send_global_event.py
=> Show event names in event node headers

blender/arm/logicnode/arm_node_group.py, blender/arm/nodes_logic.py
Thanks to @ BrahRah on Discord for proposing this idea!
=> Make node groups available from "Add node" menu

blender/arm/write_data.py
Resolves when ZUI module is disabled and debugging is enabled
=> Include ZUI when Debug Console is activated

Sources/armory/logicnode/GetHosekWilkiePropertiesNode.hx, Sources/armory/logicnode/GetNishitaPropertiesNode.hx, Sources/armory/logicnode/GetWorldStrengthNode.hx, Sources/armory/logicnode/SetHosekWilkiePropertiesNode.hx, Sources/armory/logicnode/SetNishitaPropertiesNode.hx, Sources/armory/logicnode/SetWorldStrengthNode.hx, blender/arm/logicnode/__init__.py, blender/arm/logicnode/world/LN_get_hosekwilkie_properties.py, blender/arm/logicnode/world/LN_get_nishita_properties.py, blender/arm/logicnode/world/LN_get_world_strength.py, blender/arm/logicnode/world/LN_set_hosekwilkie_properties.py, blender/arm/logicnode/world/LN_set_nishita_properties.py, blender/arm/logicnode/world/LN_set_world_strength.py, blender/arm/logicnode/world/__init__.py
These nodes allow to set and get world properties.
Strength and depending of the world used: Nishita or HosekWilkie properties.
=> World Logic Nodes

blender/arm/logicnode/sound/LN_play_sound.py
=> play sound node: fix update routine version

Sources/armory/trait/NavMesh.hx, blender/arm/props_traits.py
This PR implements the NavMesh preview in Blender
Requires: https://github.com/armory3d/haxerecast/pull/1
=> Implementing NavMesh preview

Sources/armory/logicnode/JsonStringifyNode.hx, Sources/armory/logicnode/ParseJsonNode.hx, Sources/armory/logicnode/SelectOutputNode.hx, Sources/armory/logicnode/SetMapFromArrayNode.hx, Sources/armory/logicnode/StringMapNode.hx, blender/arm/logicnode/logic/LN_select_output.py, blender/arm/logicnode/map/LN_json_parse.py, blender/arm/logicnode/map/LN_json_stringify.py, blender/arm/logicnode/map/LN_set_map_from_array.py, blender/arm/logicnode/map/LN_set_map_value.py, blender/arm/logicnode/map/LN_string_map.py
This PR introduces some new Map nodes, JSON nodes and a select output node:
=> New Map, JSON and Select Output Nodes

Sources/armory/logicnode/StringCharAtNode.hx, blender/arm/logicnode/string/LN_string_charat.py
Used for returning a character indexed within a string. Needed it to build a 3d text generator, should be useful for many other cases!
=> String CharAt node

blender/arm/exporter.py, blender/arm/logicnode/__init__.py, blender/arm/logicnode/arm_sockets.py, blender/arm/logicnode/logic/LN_select.py, blender/arm/material/cycles_nodes/nodes_shader.py, blender/arm/material/cycles_nodes/nodes_texture.py, blender/arm/material/node_meta.py, blender/arm/nodes_logic.py, blender/arm/write_data.py, blender/arm/write_probes.py
Managed to keep support for 3.6 to 4.3 using 4.1 as the reference where I believe the node socket interface was removed. Also added a responsive canvas which should actually replace the previous commit adding so many lines for resizing which does not seem to even work on debian linux firefox as it was.
=> Upgrading and testing on Blender 4.3

Sources/armory/network/WebSocket.hx, blender/arm/exporter.py, blender/arm/material/cycles_nodes/nodes_converter.py, blender/arm/material/cycles_nodes/nodes_shader.py, blender/arm/material/cycles_nodes/nodes_texture.py, blender/arm/material/node_meta.py, blender/arm/props_ui.py, blender/arm/utils.py
Clean up some node indexes and various features not available in different blender versions for better support. Also commented out QuantumCoderQC's bone animation support in the exporter for when he merges
=> Blender version support

Shaders/ssrefr_pass/ssrefr_pass.frag.glsl, Shaders/std/conetrace.glsl, Shaders/std/light.glsl, Shaders/voxel_light/voxel_light.comp.glsl, Shaders/voxel_offsetprev/voxel_offsetprev.comp.glsl, Shaders/voxel_sdf_jumpflood/voxel_sdf_jumpflood.comp.glsl, Shaders/voxel_temporal/voxel_temporal.comp.glsl, Sources/armory/renderpath/Inc.hx, Sources/armory/renderpath/RenderPathDeferred.hx, Sources/armory/renderpath/RenderPathForward.hx, blender/arm/material/cycles_nodes/nodes_shader.py, blender/arm/material/make_mesh.py
- Various fixes coming with the patch.
- Voxels shadows are used with voxels light.
- Fixed a normalize issue and wrong direction in the conetracer.
- Add option to make object contribute to lighting even if invisible.
=> Gi clipmaps

Sources/armory/logicnode/ArraySpliceNode.hx, blender/arm/logicnode/array/LN_array_display.py, blender/arm/logicnode/array/LN_array_filter.py, blender/arm/logicnode/array/LN_array_splice.py
Splice Array: array output 
I added the result of the splice function as an output array
I also fixed 2 array functions descriptions.
=> Splice Array: array output

Sources/armory/logicnode/DrawStringNode.hx, Sources/armory/logicnode/DrawTextAreaStringNode.hx, blender/arm/logicnode/draw/LN_draw_Text_Area_string.py, blender/arm/logicnode/draw/LN_draw_string.py
=> Draw string and text nodes: added angle and output parameters

Sources/armory/logicnode/ArrayAddNode.hx, Sources/armory/logicnode/ArrayInsertNode.hx, blender/arm/logicnode/array/LN_array_add.py, blender/arm/logicnode/array/LN_array_insert.py
I added the option in array add to add the element first (array unshift function instead of push)
I also added the insert node which inserts the value at the given index increasing the length of the array (array insert function)
=> Array Insert Node and Array Add Node: Add First option

Sources/armory/logicnode/RaycastRayNode.hx, blender/arm/logicnode/object/LN_raycast_ray.py
Raycast Ray Node for non physic objects allow to detect objects in the scene using the class Ray.hx.
Its an alternative in world space to the other Raycast Nodes from Camera.
=> Raycast Ray Node

armory/blender/arm/props_ui.py
=> 4.3 + Blender support

armory/blender/arm/material/cycles_nodes/nodes_shader.py, armory/blender/arm/material/node_meta.py
Glossy Shader update for blender 4.2 and 4.3, blender changed the node name and inputs.
=> Update glossy shader

armory/Sources/armory/logicnode/WriteFileNode.hx, armory/Sources/armory/logicnode/WriteJsonNode.hx
Removed a trace from WriteJson
For html5 now json or file gets downloaded so its not longer lost.
=> WriteJsonNode and WriteFileNode: add Html5 version

armory/Sources/armory/logicnode/DrawPolygonFromArrayNode.hx
fix node for changing array size of points... adding or removing points.
=> Fix DrawPolygonFromArrayNode

armory/blender/arm/material/cycles_nodes/nodes_texture.py
There was a missing ":" and I forgot to support the color socket for musgrave!
=> Updated noise to support color socket with fix

armory/Sources/armory/logicnode/DrawRoundedRectNode.hx, armory/blender/arm/logicnode/draw/LN_draw_rounded_rect.py
All examples with different radius and segments:
=> Draw rounded rect node

armory/Sources/armory/logicnode/ProbabilisticOutputNode.hx, armory/blender/arm/logicnode/random/LN_probabilistic_output.py
it allows to get a random output with different probabilities, it extends random output which is a balanced output.
This is useful for ai and randomization cases.
=> Probabilistic output node

armory/Sources/armory/logicnode/DistanceScreenToWorldSpaceNode.hx, armory/blender/arm/logicnode/math/LN_distance_screen_to_world_space.py
This node is useful to calculate distance from screen to point.
I can be used with screen to world space when one needs to know the distance of certain object.
=> Get distance world node

armory/Sources/armory/logicnode/GetMaterialsNode.hx, armory/blender/arm/logicnode/material/LN_get_object_materials.py
=> GetMaterialsNode

armory/Sources/armory/logicnode/LoadUrlNode.hx, armory/blender/arm/logicnode/native/LN_loadUrl.py
I extended the node to include the following updates:
- Option to open new page or redirect existing one.
- Option for width, height, left and top values for new pages.
- Output true or false is returned whether the window is opened or not.
- Added a htlm5 check.
=> LoadURLNode Update

armory/Sources/armory/logicnode/SetSoundNode.hx, armory/Sources/armory/logicnode/SetVolumeSoundNode.hx, armory/Sources/iron/object/SpeakerObject.hx, armory/blender/arm/logicnode/sound/LN_set_sound_speaker.py, armory/blender/arm/logicnode/sound/LN_set_volume_speaker.py
These functions allow to modify both sound and volume, so the same speaker can be reused with a different sound and volume.
So good now iron is included in the same repo!
[Using a Single Speaker to Play Multiple Sounds](https://forums.armory3d.org/t/using-a-single-speaker-to-play-multiple-sounds/5868/3)
=> SpeakerNodes: setSound and setVolume

armory/Sources/zui/Zui.hx
This enables proper touch input from mobile browsers
=> Enable touch input from mobile browsers

armory/Sources/armory/logicnode/ArrayIndexListNode.hx, armory/blender/arm/logicnode/array/LN_array_index_list.py
This node extends the functionality of Array Index Node, it returns a list of all indexes of a given value as an array,
=> Array Index List Node

armory/blender/arm/write_data.py
=> Fix HTML5 fullscreen

armory/Sources/armory/logicnode/DrawCameraTextureNode.hx, armory/blender/arm/logicnode/draw/LN_draw_camera_texture.py
node position was always 0 so I added a name string input instead
Texture image was inverted for html5 target
I also added renderTarget TextureFormat and DepthStencilFormat
=> Fix draw camera texture node

armory/Sources/armory/trait/physics/bullet/PhysicsWorld.hx, armory/Sources/iron/system/Time.hx
Closes #3014 for Krom Windows builds. Goes together with [this PR from Kha](https://github.com/armory3d/Kha/pull/5).
=> Get refresh rate from Monitor in Krom Windows builds

armory/Sources/armory/logicnode/AddParticleToObjectNode.hx, armory/Sources/armory/logicnode/GetParticleDataNode.hx, armory/Sources/armory/logicnode/GetParticleNode.hx, armory/Sources/armory/logicnode/RemoveParticleFromObjectNode.hx, armory/Sources/armory/logicnode/SetParticleDataNode.hx, armory/Sources/iron/object/ParticleSystem.hx
Set some fields in ParticleSystem private. Update logic nodes accordingly. This can keep the API cleaner.
=> Make some public fields in ParticleSystem private

armory/Sources/iron/App.hx, armory/Sources/iron/object/ParticleSystem.hx, armory/Sources/iron/system/Time.hx
Also protecting `iron.system.Time.delta` and `iron.system.Time.renderDelta` from writing.
=> Fix pausing and resuming updates

armory/Sources/armory/trait/physics/bullet/DebugDrawHelper.hx, armory/Sources/armory/trait/physics/bullet/PhysicsWorld.hx
- fix debug draw RayCast (they weren't displayed in fixedUpdate)
- fix RayCast Hit (multiple Hits had the same hit point and hit normal)
=> Raycast fixes

armory/Shaders/compositor_pass/compositor_pass.frag.glsl, armory/blender/arm/logicnode/postprocess/LN_get_camera_post_process.py, armory/blender/arm/logicnode/postprocess/LN_set_ca_settings.py, armory/blender/arm/logicnode/postprocess/LN_set_camera_post_process.py
Tonemapping could only be changed for boolean values (0, 1) and that did not allow to change it among the other tonemapping values (2, 3)
Now all values are available I added a text label for reference.
I also added reference for CA:
=> fix tonemapping var  from boolean to int

armory/Shaders/compositor_pass/compositor_pass.frag.glsl, armory/Sources/armory/renderpath/Postprocess.hx, armory/blender/arm/make_renderpath.py, armory/blender/arm/props_renderpath.py, armory/blender/arm/write_data.py
DoF reference was always taken from camera0 instead of the active camera of the scene
=> fix DoF references and small changes

armory/blender/arm/exporter.py
=> add export option for particles

armory/blender/arm/exporter.py
I changed the logic since particle systems name can be changed and then the reference to the modifier is lost. The modifier's name is the same when the particle system is created but then is an independent name.
=> Particle export: add logic for particle rename cases

armory/Sources/iron/Scene.hx, armory/blender/arm/exporter.py, armory/blender/arm/props_traits_props.py, armory/blender/arm/utils.py
=> Add TSceneFormat as Trait property type

armory/Sources/armory/logicnode/DrawStringNode.hx, armory/Sources/armory/trait/internal/DebugConsole.hx, armory/blender/arm/logicnode/camera/LN_set_camera_start_end.py, armory/blender/arm/logicnode/draw/LN_draw_Text_Area_string.py, armory/blender/arm/logicnode/draw/LN_draw_string.py
- fix label world debug console
- erase indentation in camera start end
- reorder width and height in draw string
- add version in text area string
=> minor updates

armory/Sources/armory/system/Signal.hx, armory/Sources/iron/object/ParticleSystemCPU.hx
Changes:
- fix for `ParticleSystemCPU` scale and scale over time with color ramp
- properly call `callbacks` from `Signal.emit()` when the array mutates
=> General fixes

armory/blender/arm/make_renderpath.py, armory/blender/arm/write_data.py
the condition must be in the same scene camera
=> fix dof condition

armory/blender/arm/logicnode/array/LN_array_splice.py, armory/blender/arm/logicnode/event/LN_on_event.py, armory/blender/arm/logicnode/input/LN_keyboard.py, armory/blender/arm/logicnode/input/LN_mouse.py, armory/blender/arm/logicnode/miscellaneous/LN_call_group.py
Labels are useful to find input nodes in the nodes editor search panel:
previous:
now:
I added them for keyboard, mouse and event.
added replacement routine for array splice
=> Labels for finding nodes

armory/Sources/iron/data/SceneFormat.hx, armory/Sources/iron/object/ParticleSystemCPU.hx
- fix lifetime for non-loop particles
- fix distribution along vertices and volume
- fix distribution when the emitter is rotated
=> CPU Particles small fixes
